function isReplicaOrigin(origin: string) { return /^https:\/\/pr-next-replica-fiel-[a-z0-9-]+-puntarollersapps-projects\.vercel\.app$/.test(origin); }
// Beta isolation: never initialize against another project.
if (Deno.env.get('SUPABASE_URL') !== 'https://azheisnfaedjqcuhiylo.supabase.co') throw new Error('PR NEXT beta isolation');
import 'jsr:@supabase/functions-js/edge-runtime.d.ts'
import { createClient } from 'npm:@supabase/supabase-js@2'

const ALLOWED_ORIGINS = new Set(['https://pr-next-replica-fiel-oahke3cf7-puntarollersapps-projects.vercel.app','https://puntarollers.com','https://www.puntarollers.com','http://localhost:5173'])
const TO_EMAIL = 'claudiofaccelli@gmail.com'
const FROM_EMAIL = 'Punta Rollers <onboarding@resend.dev>'
const BLOCKED_PINS = new Set(['https://pr-next-replica-fiel-oahke3cf7-puntarollersapps-projects.vercel.app','0000','1111','1234','4321','2222','3333','4444','5555','6666','7777','8888','9999'])
function cors(req: Request) { const origin=req.headers.get('origin')||''; return {'Access-Control-Allow-Origin':(ALLOWED_ORIGINS.has(origin) || isReplicaOrigin(origin))?origin:'https://www.puntarollers.com','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json','Vary':'Origin'} }
function json(req:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:cors(req)})}
function escapeHtml(v:unknown){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
Deno.serve(async(req)=>{
 if(req.method==='OPTIONS') return new Response('ok',{headers:cors(req)}); if(req.method!=='POST') return json(req,{error:'Method not allowed'},405)
 const origin=req.headers.get('origin')||''; if(origin&&!(ALLOWED_ORIGINS.has(origin) || isReplicaOrigin(origin))) return json(req,{error:'Origin not allowed'},403)
 let body:any; try{body=await req.json()}catch{return json(req,{error:'Datos inválidos.'},400)}
 const nombreCompleto=String(body?.nombre_completo||'').trim().replace(/\s+/g,' '); const parts=nombreCompleto.split(' '); const nombre=parts.shift()||''; const apellido=parts.join(' ')||'-'; const documento=String(body?.documento||'').replace(/\D/g,''); const telefono=String(body?.telefono||'').trim(); const email=String(body?.email||'').trim().toLowerCase(); const pin=String(body?.pin||'').trim()
 if(nombreCompleto.length<3||nombreCompleto.length>120)return json(req,{error:'Revisá tu nombre y apellido.'},400); if(!/^[0-9]{6,12}$/.test(documento))return json(req,{error:'Ingresá un documento válido, solo con números.'},400); if(telefono.length<6||telefono.length>30)return json(req,{error:'Ingresá un WhatsApp válido.'},400); if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json(req,{error:'Ingresá un email válido.'},400); if(!/^\d{4}$/.test(pin))return json(req,{error:'El PIN debe tener exactamente 4 números.'},400); if(BLOCKED_PINS.has(pin))return json(req,{error:'Elegí un PIN menos fácil de adivinar.'},400)
 const secretKeys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}'); const serviceKey=secretKeys.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'); const supabaseUrl=Deno.env.get('SUPABASE_URL')||''; if(!serviceKey||!supabaseUrl)return json(req,{error:'Servicio temporalmente no disponible.'},503); const supabase=createClient(supabaseUrl,serviceKey)
 const {data:existingProfile}=await supabase.from('profiles').select('id').eq('documento',documento).maybeSingle(); if(existingProfile)return json(req,{error:'Este documento ya tiene un perfil en Punta Rollers. Si necesitás ayuda con tu acceso, escribinos por WhatsApp.'},409)
 const {data:existingRequest}=await supabase.from('student_access_requests').select('id,status').eq('documento',documento).in('status',['pending','profile_created']).maybeSingle(); if(existingRequest)return json(req,{ok:true,already_exists:true,id:existingRequest.id,status:existingRequest.status})
 const {data:row,error}=await supabase.from('student_access_requests').insert({nombre,apellido,documento,telefono,email,pin,status:'pending'}).select('id,created_at').single(); if(error||!row){console.error('insert request failed',error);return json(req,{error:'No pudimos guardar tu solicitud. Probá nuevamente.'},500)}
 let emailSent=false; const resendKey=(undefined as string | undefined); if(resendKey){const createdAt=new Date(row.created_at).toLocaleString('es-UY',{timeZone:'America/Montevideo'}); const html=`<div style="font-family:Arial,sans-serif;background:#0b0b0c;padding:24px;color:#f6f6f6"><div style="max-width:620px;margin:auto;background:#151517;border-radius:20px;padding:28px;border:1px solid #29292d"><div style="font-size:12px;font-weight:800;color:#ff3b30;letter-spacing:.12em;text-transform:uppercase">Punta Rollers · Accesos</div><h1>Nuevo alumno listo para crear usuario</h1><p><strong>Nombre:</strong> ${escapeHtml(nombreCompleto)}</p><p><strong>Documento:</strong> ${escapeHtml(documento)}</p><p><strong>WhatsApp:</strong> ${escapeHtml(telefono)}</p><p><strong>Email:</strong> ${escapeHtml(email)}</p><p><strong>Registro:</strong> ${escapeHtml(createdAt)}</p><p>Entrá al panel Admin → Nuevos accesos para importar el perfil.</p></div></div>`; try{const rr=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${resendKey}`,'Content-Type':'application/json'},body:JSON.stringify({from:FROM_EMAIL,to:[TO_EMAIL],subject:`🛼 Nuevo acceso PR — ${nombreCompleto}`,html})}); emailSent=rr.ok; if(!rr.ok)console.error('resend failed',rr.status,await rr.text())}catch(e){console.error('email error',e)}}
 return json(req,{ok:true,id:row.id,email_sent:emailSent},201)
})
