import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../../lib/supabase'
function nameOf(p){return p?.nombre_completo||p?.display_name||[p?.nombre,p?.apellido].filter(Boolean).join(' ')||'Integrante PR'}
function photoOf(p){return p?.foto_url||p?.photo_url||p?.avatar_url||p?.foto||''}
function parts(p){const m=Number(p?.cumple_mes),d=Number(p?.cumple_dia);if(m&&d)return{m,d};const v=p?.fecha_nacimiento||p?.fechaNacimiento||p?.birth_date||p?.birthday;if(!v)return null;const x=String(v).match(/^(?:\d{4})-(\d{2})-(\d{2})/);if(x)return{m:Number(x[1]),d:Number(x[2])};const dt=new Date(v);return Number.isNaN(dt.getTime())?null:{m:dt.getMonth()+1,d:dt.getDate()}}
export default function CommunityBirthdays(){
 const[rows,setRows]=useState([]);const[loading,setLoading]=useState(true)
 useEffect(()=>{let live=true;(async()=>{const{data}=await supabase.from('profiles_feed').select('*').limit(500);if(live){setRows(data||[]);setLoading(false)}})().catch(()=>live&&setLoading(false));return()=>{live=false}},[])
 const upcoming=useMemo(()=>{const now=new Date(),base=new Date(now.getFullYear(),now.getMonth(),now.getDate(),12);return rows.map(p=>{const b=parts(p);if(!b)return null;let dt=new Date(now.getFullYear(),b.m-1,b.d,12);if(dt<base)dt=new Date(now.getFullYear()+1,b.m-1,b.d,12);const days=Math.round((dt-base)/86400000);return{p,dt,days}}).filter(Boolean).sort((a,b)=>a.days-b.days).slice(0,4)},[rows])
 return <section className="rounded-[28px] border border-white/[.07] bg-white/[.025] p-5"><div className="flex items-center justify-between"><div><p className="text-[8px] font-black tracking-[.18em] text-white/25">CUMPLEAÑOS PR</p><h2 className="mt-1 text-xl font-black">Celebramos a los nuestros.</h2></div><span className="text-2xl opacity-50">✦</span></div>
  {loading?<p className="mt-4 text-[9px] text-white/25">Cargando próximos cumpleaños…</p>:upcoming.length?<div className="mt-4 space-y-2">{upcoming.map(({p,dt,days})=><article key={p.id} className="flex items-center gap-3 rounded-[18px] border border-white/[.06] bg-black/20 p-3"><div className="h-10 w-10 overflow-hidden rounded-full border border-white/10 bg-white/[.04]">{photoOf(p)?<img src={photoOf(p)} alt="" className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-[10px] font-black text-white/40">{nameOf(p).slice(0,1)}</div>}</div><div className="min-w-0 flex-1"><p className="truncate text-[10px] font-black">{nameOf(p)}</p><p className="mt-1 text-[8px] text-white/25">{dt.toLocaleDateString('es-UY',{day:'numeric',month:'long'})}</p></div><span className="rounded-full border border-violet-300/10 bg-violet-300/[.05] px-3 py-1 text-[8px] font-black text-violet-100/55">{days===0?'HOY':days===1?'MAÑANA':days+' DÍAS'}</span></article>)}</div>:<p className="mt-4 rounded-[18px] border border-dashed border-white/10 p-4 text-center text-[9px] text-white/20">No hay cumpleaños próximos para mostrar.</p>}</section>
}