import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../../lib/supabase'

function ProgressBar({ value, max }) { const percent=Math.max(0,Math.min(100,(Number(value||0)/max)*100));return <div className="relative mt-3 h-2.5 overflow-hidden rounded-full border border-white/[.07] bg-black/35"><div className="h-full rounded-full bg-gradient-to-r from-emerald-400 via-lime-300 to-amber-300 transition-all duration-700" style={{width:`${percent}%`}}/></div> }
function RewardPill({unlocked,children}){return <span className={`rounded-full border px-2.5 py-1 text-[8px] font-black uppercase tracking-[.1em] ${unlocked?'border-emerald-300/30 bg-emerald-400/15 text-emerald-200':'border-white/[.08] bg-white/[.035] text-white/32'}`}>{unlocked?'✓ ':'○ '}{children}</span>}

export default function AmigosPRCard({ profileId, compact=false }) {
  const[code,setCode]=useState(''),[copied,setCopied]=useState(false),[expanded,setExpanded]=useState(!compact)
  const[progress,setProgress]=useState({confirmed_total:0,confirmed_last_12m:0,reward_50_status:null,reward_free_status:null})
  useEffect(()=>{let active=true;async function load(){if(!profileId)return;const[codeResult,progressResult]=await Promise.all([supabase.rpc('ensure_pr_referral_code',{p_profile_id:profileId}),supabase.rpc('pr_referral_progress',{p_profile_id:profileId})]);if(!active)return;if(!codeResult.error&&codeResult.data)setCode(String(codeResult.data));if(!progressResult.error&&Array.isArray(progressResult.data)&&progressResult.data[0])setProgress(progressResult.data[0])}load();return()=>{active=false}},[profileId])
  async function copyCode(){if(!code)return;try{await navigator.clipboard.writeText(code)}catch{return}setCopied(true);window.setTimeout(()=>setCopied(false),1800)}
  const total=Number(progress.confirmed_total)||0,last12=Number(progress.confirmed_last_12m)||0,firstGoalValue=Math.min(total,5),secondGoalValue=Math.min(last12,10),firstUnlocked=total>=5||Boolean(progress.reward_50_status),secondUnlocked=last12>=10||Boolean(progress.reward_free_status)
  const headline=useMemo(()=>secondUnlocked?'¡Desbloqueaste 1 mes gratis!':firstUnlocked?`Vas ${secondGoalValue}/10 · próximo premio: 1 mes gratis`:`Vas ${firstGoalValue}/5 · próximo premio: 50% OFF`,[firstUnlocked,secondUnlocked,firstGoalValue,secondGoalValue])

  if(compact)return <section className="overflow-hidden rounded-[24px] border border-emerald-300/15 bg-gradient-to-br from-emerald-500/[.07] via-white/[.02] to-transparent">
    <button type="button" onClick={()=>setExpanded(v=>!v)} className="flex min-h-[72px] w-full items-center justify-between gap-3 px-4 text-left active:bg-white/[.025]">
      <div className="min-w-0"><p className="text-[8px] font-black uppercase tracking-[.16em] text-emerald-300">AMIGOS PR</p><p className="mt-1 truncate text-sm font-black text-white">{headline}</p><p className="mt-1 text-[9px] text-white/30">Tu código y beneficios siguen funcionando.</p></div><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl border border-emerald-300/15 bg-emerald-400/[.07] text-emerald-200 transition-transform ${expanded?'rotate-180':''}`}>⌄</span>
    </button>
    {expanded&&<div className="border-t border-white/[.06] p-4">
      <div className="rounded-[20px] border border-white/[.07] bg-black/25 p-3.5"><p className="text-[8px] font-black uppercase tracking-[.14em] text-white/30">TU CÓDIGO PERSONAL</p><div className="mt-2 flex gap-2"><div className="min-w-0 flex-1 rounded-2xl border border-emerald-300/15 bg-emerald-400/[.07] px-4 py-3 font-display text-lg tracking-[.05em] text-emerald-200">{code||'CREANDO…'}</div><button type="button" disabled={!code} onClick={copyCode} className="rounded-2xl border border-white/[.08] bg-white/[.04] px-4 text-[9px] font-black text-white/65 disabled:opacity-40">{copied?'✓ Copiado':'Copiar'}</button></div></div>
      {!firstUnlocked?<><ProgressBar value={firstGoalValue} max={5}/><div className="mt-2 flex justify-between text-[8px] font-bold text-white/32"><span>{firstGoalValue} amigos</span><span>{Math.max(0,5-firstGoalValue)} para 50% OFF</span></div></>:<><ProgressBar value={secondGoalValue} max={10}/><div className="mt-2 flex justify-between text-[8px] font-bold text-white/32"><span>{secondGoalValue}/10 en 12 meses</span><span>{secondUnlocked?'Meta completa':`${Math.max(0,10-secondGoalValue)} para mes gratis`}</span></div></>}
      <div className="mt-3 flex flex-wrap gap-2"><RewardPill unlocked={firstUnlocked}>5 amigos · 50% OFF</RewardPill><RewardPill unlocked={secondUnlocked}>10 amigos · mes gratis</RewardPill></div>
      <div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-2xl border border-orange-300/12 bg-orange-400/[.05] p-3"><p className="text-[8px] font-black text-orange-200">TU AMIGO</p><p className="mt-1 text-xs font-black text-white">10% OFF</p></div><div className="rounded-2xl border border-emerald-300/12 bg-emerald-400/[.05] p-3"><p className="text-[8px] font-black text-emerald-200">VOS</p><p className="mt-1 text-xs font-black text-white">10% OFF × 2 meses</p></div></div>
      <p className="mt-3 text-[8px] leading-4 text-white/25">Solo cuentan referidos con inscripción y pago confirmados. La lógica de premios continúa administrada por el sistema de referidos PR.</p>
    </div>}
  </section>

  return <section className="relative mx-auto w-full max-w-3xl overflow-hidden rounded-[28px] border border-emerald-300/20 bg-gradient-to-br from-emerald-500/[.10] via-[#111217] to-orange-400/[.06] p-5 shadow-[0_18px_55px_rgba(16,185,129,.06)]"><div className="relative"><p className="text-[9px] font-black uppercase tracking-[.18em] text-emerald-300/75">Beneficio de comunidad</p><h2 className="mt-1 font-display text-[29px] leading-none text-white">AMIGOS PR</h2><p className="mt-2 text-[11px] leading-5 text-white/45">Invitá a un amigo a Punta Rollers y compartile tu código personal.</p><div className="mt-4 rounded-[20px] border border-white/[.08] bg-black/25 p-4"><div className="flex gap-2"><div className="min-w-0 flex-1 rounded-2xl border border-emerald-300/20 bg-emerald-400/[.08] px-4 py-3 font-display text-[22px] text-emerald-200">{code||'CREANDO…'}</div><button type="button" disabled={!code} onClick={copyCode} className="rounded-2xl border border-white/10 bg-white/[.05] px-4 text-[10px] font-black text-white/70">{copied?'✓ Copiado':'Copiar'}</button></div></div><div className="mt-4 rounded-[22px] border border-emerald-300/15 bg-emerald-400/[.05] p-4"><p className="text-[13px] font-black text-white">{headline}</p>{!firstUnlocked?<ProgressBar value={firstGoalValue} max={5}/>:<ProgressBar value={secondGoalValue} max={10}/>}<div className="mt-3 flex flex-wrap gap-2"><RewardPill unlocked={firstUnlocked}>5 amigos · 50% OFF</RewardPill><RewardPill unlocked={secondUnlocked}>10 amigos · 1 mes gratis</RewardPill></div></div></div></section>
}
