import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../../lib/supabase'
const EVENT='shifter-marathon-2026'
export default function TasksLiveBridge({profileId}){
 const[state,setState]=useState({loading:true,error:false,category:null,tasks:[],results:[]})
 useEffect(()=>{let live=true;(async()=>{if(!profileId)return;const e=await supabase.from('pr_training_enrollments').select('category,active').eq('profile_id',profileId).eq('event_slug',EVENT).maybeSingle();if(!live)return;if(!e.data?.category||e.data.category==='NO'){setState({loading:false,error:false,category:null,tasks:[],results:[]});return}const[t,r]=await Promise.all([supabase.from('pr_training_tasks').select('id,category,title,description,rule_type,target_value,sort_order').eq('event_slug',EVENT).eq('active',true).order('sort_order'),supabase.from('pr_training_task_results').select('task_id,status,progress_value,completed_at,updated_at').eq('profile_id',profileId)]);if(live)setState({loading:false,error:Boolean(t.error||r.error),category:e.data.category,tasks:(t.data||[]).filter(x=>x.category==='ALL'||x.category===e.data.category),results:r.data||[]})})().catch(()=>live&&setState(x=>({...x,loading:false,error:true,tasks:[],results:[]})));return()=>{live=false}},[profileId])
 const rows=useMemo(()=>state.tasks.map(t=>({...t,result:state.results.find(r=>r.task_id===t.id)})),[state]),done=rows.filter(x=>x.result?.status==='completed').length
 if(state.loading)return <section className="rounded-[26px] border border-white/[.07] bg-white/[.02] p-5"><p className="text-[9px] text-white/25">Conectando tu entrenamiento…</p></section>
 if(state.error)return <section className="rounded-[26px] border border-amber-200/12 bg-amber-200/[.03] p-5"><p className="text-[8px] font-black tracking-[.18em] text-amber-100/45">LECTURA INCOMPLETA</p><h2 className="mt-2 text-xl font-black">Tus tareas siguen ahí.</h2><p className="mt-2 text-[9px] leading-5 text-white/28">No pudimos leer el programa completo con confianza. Para evitar mostrar progreso incorrecto, esta vista queda en espera y no inventa estados.</p></section>
 if(!state.category)return <section className="rounded-[26px] border border-white/[.07] bg-white/[.02] p-5"><p className="text-[8px] font-black tracking-[.18em] text-white/25">TAREAS ACTIVAS</p><h2 className="mt-2 text-xl font-black">Tu próxima etapa se arma acá.</h2><p className="mt-2 text-[10px] leading-5 text-white/30">No tenés un programa activo heredado de Shifter. Cuando se publiquen las tareas mensuales de PR NEXT van a aparecer en este espacio.</p></section>
 return <section className="rounded-[28px] border border-violet-300/15 bg-violet-300/[.035] p-5"><div className="flex items-end justify-between gap-4"><div><p className="text-[8px] font-black tracking-[.2em] text-violet-200/55">PUENTE ACTIVO · SHIFTER</p><h2 className="mt-1 text-xl font-black">Tu entrenamiento ya está conectado.</h2></div><span className="rounded-full border border-violet-200/15 px-3 py-1 text-[8px] font-black text-violet-100/55">{done}/{rows.length}</span></div><p className="mt-2 text-[9px] leading-4 text-white/28">Hasta el cierre de Shifter, Tareas 2.0 lee tu programa actual sin modificarlo. Después queda guardado como capítulo histórico.</p><div className="mt-4 grid grid-cols-3 gap-2"><Mini v={done} l="COMPLETADAS"/><Mini v={Math.max(rows.length-done,0)} l="PENDIENTES"/><Mini v={rows.length} l="TOTAL"/></div><div className="mt-4 space-y-2">{rows.slice(0,4).map((t,i)=><article key={t.id} className="flex items-center gap-3 rounded-[18px] border border-white/[.06] bg-black/20 p-3"><div className={'grid h-8 w-8 shrink-0 place-items-center rounded-full border text-[8px] font-black '+(t.result?.status==='completed'?'border-emerald-300/20 bg-emerald-300/[.07] text-emerald-200':'border-white/10 text-white/25')}>{t.result?.status==='completed'?'✓':String(i+1).padStart(2,'0')}</div><div className="min-w-0 flex-1"><p className="truncate text-[9px] font-black">{t.title}</p><p className="mt-1 text-[8px] text-white/23">{t.result?.status==='completed'?'Completada':'En curso'} · {String(t.rule_type||'tarea').replaceAll('_',' ')}</p></div></article>)}</div><Link to="/app/deberes" className="mt-4 inline-flex text-[8px] font-black tracking-wider text-violet-200/60">ABRIR PROGRAMA COMPLETO →</Link></section>
}
function Mini({v,l}){return <div className="rounded-[16px] border border-white/[.055] bg-black/15 p-3 text-center"><p className="text-sm font-black">{v}</p><p className="mt-1 text-[6px] font-black tracking-[.1em] text-white/20">{l}</p></div>}
