import {useMemo,useState} from 'react'
import {useAuth} from '../../lib/auth'
import {supabase} from '../../lib/supabase'
import ExplorerMap from './ExplorerMap'

const hav=(a,b)=>{const R=6371000,r=x=>x*Math.PI/180,d=r(b.lat-a.lat),g=r(b.lng-a.lng),q=Math.sin(d/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(g/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
const labels={calle:'Calle',rambla:'Rambla',ciclovia:'Ciclovía',parque:'Parque',pista:'Pista',circuito:'Circuito',inicial:'Inicial',intermedio:'Intermedio',avanzado:'Avanzado',excelente:'Excelente',buena:'Bueno',irregular:'Irregular',mala:'Malo',bajo:'Bajo',medio:'Medio',alto:'Alto',si:'Buena',parcial:'Parcial',no:'Sin iluminación'}
function Select({label,value,onChange,values}){return <label>{label}<select value={value} onChange={e=>onChange(e.target.value)}>{values.map(x=><option value={x} key={x}>{labels[x]||x}</option>)}</select></label>}
export default function ExplorerPreview({onClose}){
 const{user}=useAuth(),[pts,setPts]=useState([]),[step,setStep]=useState('map'),[saving,setSaving]=useState(false),[done,setDone]=useState(false),[error,setError]=useState(''),[photos,setPhotos]=useState([])
 const[f,setF]=useState({name:'',route_type:'calle',level:'intermedio',surface:'buena',traffic:'bajo',lighting:'si',description:'',city:user?.ciudad||'',hazards:[]})
 const dist=useMemo(()=>pts.slice(1).reduce((n,p,i)=>n+hav(pts[i],p),0),[pts])
 function hazard(h){setF(v=>({...v,hazards:v.hazards.includes(h)?v.hazards.filter(x=>x!==h):[...v.hazards,h]}))}
 function choosePhotos(e){const incoming=[...e.target.files].filter(x=>x.type.startsWith('image/')&&x.size<=5*1024*1024).slice(0,3-photos.length);setPhotos(p=>[...p,...incoming].slice(0,3));e.target.value=''}
 async function uploadPhotos(routeId){
   if(!photos.length)return
   const{data:{user:authUser}}=await supabase.auth.getUser()
   if(!authUser?.id)throw new Error('No encontramos una sesión segura para subir las fotos.')
   for(let i=0;i<photos.length;i++){
     const file=photos[i],ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg'
     const path=`${authUser.id}/${routeId}/${crypto.randomUUID()}.${ext}`
     const{error:upError}=await supabase.storage.from('pr-rollermap-images').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type||'image/jpeg'})
     if(upError)throw upError
     const{data:urlData}=supabase.storage.from('pr-rollermap-images').getPublicUrl(path)
     const{error:dbError}=await supabase.from('pr_rollermap_route_photos').insert({route_id:routeId,created_by:user.id,image_url:urlData.publicUrl,storage_path:path,sort_order:i,status:'pending'})
     if(dbError)throw dbError
   }
 }
 async function submit(){
   if(!user?.id)return
   setSaving(true);setError('')
   const{data:route,error:e}=await supabase.from('pr_rollermap_routes').insert({created_by:user.id,name:f.name.trim(),description:f.description.trim()||null,route_type:f.route_type,level:f.level,surface:f.surface,traffic:f.traffic,lighting:f.lighting,city:f.city.trim()||null,path:pts.map(({lng,lat})=>({lng,lat})),distance_m:Math.round(dist),hazards:f.hazards,status:'pending'}).select('id').single()
   if(e){setSaving(false);setError(e.message);return}
   try{await uploadPhotos(route.id);setDone(true)}catch(photoError){setError(`El recorrido quedó guardado, pero una foto no pudo subirse: ${photoError.message}`)}
   setSaving(false)
 }
 if(done)return <div className="rx-shell"><header className="rx-top"><button onClick={onClose}>←</button><div><small>ROLLERMAP</small><strong>EXPLORER <i>✦</i></strong></div><span>PREVIEW PRIVADA</span></header><div className="rx-success"><span>✦</span><small>APORTE ENVIADO</small><h2>Ahora pasa por revisión.</h2><p>El recorrido y sus fotos quedaron guardados como pendientes. Todavía no aparecen en ningún mapa público.</p><button onClick={onClose}>Volver a RollerMap</button></div></div>
 return <div className="rx-shell"><header className="rx-top"><button onClick={onClose}>←</button><div><small>ROLLERMAP</small><strong>EXPLORER <i>✦</i></strong></div><span>PREVIEW PRIVADA</span></header>
 <section className="rx-hero"><small>MAPA COLABORATIVO PARA PATINADORES</small><h1>La calle también<br/>se aprende.</h1><p>No buscamos “lugares lindos”. Buscamos información roller útil: piso, tránsito, luz, dificultad y alertas reales.</p></section>
 <nav className="rx-progress"><span className={step==='map'?'on':''}>1 · Trazado</span><span className={step==='details'?'on':''}>2 · Datos</span><span className={step==='review'?'on':''}>3 · Revisión</span></nav>
 {step==='map'&&<><section className="rx-guide"><b>{pts.length===0?'01 · MARCÁ EL INICIO':pts.length===1?'02 · MARCÁ EL SIGUIENTE PUNTO':'03 · DIBUJÁ EL TRAMO REAL'}</b><span>{pts.length<2?'Tocá directamente sobre la calle.':'Podés sumar tantos puntos como necesites para seguir curvas, cruces o cambios de calle.'}</span></section><ExplorerMap points={pts} onChange={setPts}/><div className="rx-mapbar"><div><small>DISTANCIA</small><strong>{dist>=1000?(dist/1000).toFixed(2)+' km':Math.round(dist)+' m'}</strong></div><div><small>PUNTOS</small><strong>{pts.length}</strong></div><button disabled={!pts.length} onClick={()=>setPts(p=>p.slice(0,-1))}>Deshacer</button><button disabled={!pts.length} onClick={()=>setPts([])}>Limpiar</button></div><button className="rx-primary" disabled={pts.length<2} onClick={()=>setStep('details')}>Continuar con los datos →</button></>}
 {step==='details'&&<section className="rx-form"><button className="rx-back" onClick={()=>setStep('map')}>← Editar trazado</button><small>TRAMO · {dist>=1000?(dist/1000).toFixed(2)+' KM':Math.round(dist)+' M'}</small><h2>Contanos cómo se patina.</h2><p className="rx-formlead">Queremos que otra persona pueda decidir si ese tramo le sirve antes de llegar.</p><label>Nombre del tramo<input value={f.name} onChange={e=>setF({...f,name:e.target.value})} placeholder="Ej. Rambla Mansa · Parada 5 → Puerto"/></label><div className="rx-two"><Select label="Tipo" value={f.route_type} onChange={v=>setF({...f,route_type:v})} values={['calle','rambla','ciclovia','parque','pista','circuito']}/><Select label="Nivel sugerido" value={f.level} onChange={v=>setF({...f,level:v})} values={['inicial','intermedio','avanzado']}/></div><div className="rx-two"><Select label="Estado del piso" value={f.surface} onChange={v=>setF({...f,surface:v})} values={['excelente','buena','irregular','mala']}/><Select label="Tránsito" value={f.traffic} onChange={v=>setF({...f,traffic:v})} values={['bajo','medio','alto']}/></div><Select label="Iluminación de noche" value={f.lighting} onChange={v=>setF({...f,lighting:v})} values={['si','parcial','no']}/><label>Ciudad<input value={f.city} onChange={e=>setF({...f,city:e.target.value})} placeholder="Maldonado"/></label><fieldset><legend>¿Hay algo que otro patinador debería saber?</legend><div className="rx-tags">{['Bajada pronunciada','Cruce peligroso','Pavimento roto','Mucho tránsito','Arena / piedras','Sin iluminación'].map(h=><button type="button" className={f.hazards.includes(h)?'on':''} onClick={()=>hazard(h)} key={h}>{h}</button>)}</div></fieldset><label>Tu experiencia<textarea rows="4" value={f.description} onChange={e=>setF({...f,description:e.target.value})} placeholder="Ej. piso muy liso, cuidado al cruzar la rotonda, de noche hay buena luz…"/></label><label className="rx-photo"><span>＋</span><div><b>Fotos del tramo</b><small>Hasta 3 imágenes · JPG/PNG/WebP · máximo 5 MB cada una.</small></div><input hidden type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={choosePhotos}/></label>{photos.length>0&&<div className="rx-photo-list">{photos.map((p,i)=><div key={p.name+i}><img src={URL.createObjectURL(p)} alt=""/><button onClick={()=>setPhotos(v=>v.filter((_,n)=>n!==i))}>×</button></div>)}</div>}<button className="rx-primary" disabled={f.name.trim().length<3} onClick={()=>setStep('review')}>Revisar antes de enviar →</button></section>}
 {step==='review'&&<section className="rx-form"><button className="rx-back" onClick={()=>setStep('details')}>← Corregir datos</button><small>PREVISUALIZACIÓN DEL APORTE</small><h2>{f.name||'Tu recorrido'}</h2><div className="rx-previewcard"><div className="rx-previewtop"><span>✦ EXPLORER</span><b>{dist>=1000?(dist/1000).toFixed(2)+' km':Math.round(dist)+' m'}</b></div><div className="rx-previewmeta"><span>{labels[f.route_type]}</span><span>{labels[f.level]}</span><span>Piso {labels[f.surface]}</span><span>Tránsito {labels[f.traffic]}</span><span>Luz {labels[f.lighting]}</span></div>{photos.length>0&&<div className="rx-previewphotos">{photos.map((p,i)=><img key={i} src={URL.createObjectURL(p)} alt="Vista previa del tramo"/>)}</div>}{f.description&&<p>{f.description}</p>}{f.hazards.length>0&&<div className="rx-warning"><b>Atención</b>{f.hazards.join(' · ')}</div>}<small>Recomendado por {user?.nombre||'Perfil PR'} · Pendiente de aprobación</small></div><div className="rx-review"><small>CONTROL DE CALIDAD PR</small><p>Antes de aparecer en Explorer, el aporte será revisado. Podemos corregir datos, pedir más información o rechazarlo si no es suficientemente claro o seguro.</p></div>{error&&<div className="rx-submiterror">{error}</div>}<button className="rx-primary" disabled={saving} onClick={submit}>{saving?'Guardando aporte…':'Enviar a revisión →'}</button></section>}
 </div>
}
