import { useEffect, useState } from 'react'
import { supabase } from '../../lib/supabase'

export default function WelcomeEmailSettings() {
  const [config,setConfig]=useState(null),[message,setMessage]=useState(''),[preview,setPreview]=useState(''),[busy,setBusy]=useState(false)
  useEffect(()=>{let active=true;supabase.from('pr_rollermap_email_config').select('*').eq('id',1).single().then(({data,error})=>{if(active){setConfig(data);if(error)setMessage(error.message)}});return()=>{active=false}},[])
  async function save(){if(!config.subject.trim()||!config.intro.trim()){setMessage('Completá el asunto y la presentación.');return}setBusy(true);const {error}=await supabase.from('pr_rollermap_email_config').update({subject:config.subject.trim(),intro:config.intro.trim(),updated_at:new Date().toISOString()}).eq('id',1);setMessage(error?error.message:'Configuración guardada para las próximas bienvenidas.');setBusy(false);setPreview('')}
  async function showPreview(){setBusy(true);const {data,error}=await supabase.functions.invoke('pr-rollermap-admin',{body:{action:'preview'}});setBusy(false);if(error||data?.error){setMessage(data?.error||error.message);return}setPreview(data.html);setMessage(data.resend_configured?'Resend está configurado. Esta vista previa no envía correos.':'Falta configurar Resend. Esta vista previa no envía correos.')}
  return <details style={{margin:16,padding:16,border:'1px solid var(--line)',borderRadius:16}}><summary style={{cursor:'pointer',fontWeight:700}}>Correo de bienvenida de RollerMap</summary>{config&&<div style={{display:'grid',gap:12,marginTop:16}}><p style={{fontSize:12,color:'var(--muted)'}}>Se envía al aprobar un lugar. Los registros importados no reciben correos automáticamente.</p><label>Asunto<input className="rm-input" value={config.subject} maxLength={180} onChange={e=>setConfig({...config,subject:e.target.value})}/></label><label>Presentación<textarea className="rm-textarea" value={config.intro} maxLength={1500} onChange={e=>setConfig({...config,intro:e.target.value})}/></label><p style={{fontSize:11,color:'var(--muted)'}}>Remitente: {config.sender}</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button disabled={busy} className="rm-btn rm-btn--primary" onClick={save}>Guardar configuración</button><button disabled={busy} className="rm-btn rm-btn--secondary" onClick={showPreview}>Ver correo guardado</button></div></div>}{message&&<p role="status" style={{marginTop:12,fontSize:12}}>{message}</p>}{preview&&<iframe title="Vista previa de bienvenida RollerMap" srcDoc={preview} sandbox="" style={{marginTop:16,border:0,width:'100%',height:640,borderRadius:16}}/>}</details>
}
