import { useEffect,useState } from 'react'
import { useParams } from 'react-router-dom'
import AppLayout from '../layouts/AppLayout'
import ProfileAvatar from '../components/ProfileAvatar'
import { supabase } from '../lib/supabase'
import { loadStudentReport } from '../lib/studentReport'
import { exportStudentExcel,exportStudentPdf } from '../lib/studentReportExport'

const periods=[['30d','30 días'],['90d','90 días'],['6m','6 meses'],['1y','1 año'],['all','Histórico']]
const fmt=(n,d=1)=>Number(n||0).toLocaleString('es-UY',{maximumFractionDigits:d})
const duration=(s)=>{s=Number(s||0);const h=Math.floor(s/3600),m=Math.floor((s%3600)/60);return h?`${h} h ${m} min`:`${m} min`}
const groupTitle=g=>g?.titulo||g?.nombre||''

export default function AdminAlumnoFicha(){
  const{id}=useParams()
  const[period,setPeriod]=useState('90d'),[report,setReport]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[exporting,setExporting]=useState(''),[refresh,setRefresh]=useState(0)
  useEffect(()=>{let live=true;setLoading(true);setError('');loadStudentReport(id,period).then(r=>live&&setReport(r)).catch(e=>live&&setError(e?.message||'No pude cargar la ficha.')).finally(()=>live&&setLoading(false));return()=>{live=false}},[id,period,refresh])
  async function download(type){if(!report||exporting)return;setExporting(type);setError('');try{if(type==='pdf')await exportStudentPdf(report);else await exportStudentExcel(report)}catch(e){setError(`No pude generar el ${type==='pdf'?'PDF':'Excel'}: ${e?.message||'error inesperado'}`)}finally{setExporting('')}}
  const p=report?.profile||{},s=report?.summary||{}
  return <AppLayout title="Ficha Deportiva PR" showBack><div className="pr-page space-y-5 pb-14">
    <section className="rounded-[32px] border border-amber-300/15 bg-gradient-to-br from-amber-300/[.11] via-white/[.025] to-transparent p-5"><div className="flex items-center gap-4"><ProfileAvatar profile={p} className="h-16 w-16 shrink-0" rounded="rounded-full"/><div className="min-w-0"><p className="text-[9px] font-black uppercase tracking-[.22em] text-amber-200">EXPEDIENTE DEPORTIVO</p><h1 className="mt-1 truncate text-2xl font-black">{[p.nombre,p.apellido].filter(Boolean).join(' ')||'Alumno PR'}</h1><p className="mt-1 text-[10px] text-white/35">{(p.grupos_info||[]).map(groupTitle).filter(Boolean).join(' · ')||p.ciudad||'Punta Rollers'}</p></div></div><div className="mt-5 flex gap-2 overflow-x-auto pb-1">{periods.map(([v,l])=><button key={v} onClick={()=>setPeriod(v)} className={`shrink-0 rounded-full px-3 py-2 text-[9px] font-black ${period===v?'bg-amber-300 text-black':'border border-white/10 text-white/40'}`}>{l}</button>)}</div></section>
    {loading&&<div className="rounded-2xl bg-white/[.03] p-6 text-center text-xs text-white/30">Construyendo expediente…</div>}
    {error&&<div className="rounded-2xl border border-red-300/15 bg-red-400/[.06] p-4 text-xs text-red-100">{error}</div>}
    {report&&!loading&&<>
      <section className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric v={`${fmt(s.km)} km`} l="Patinaje inline"/><Metric v={s.activities} l="Actividades"/><Metric v={duration(s.movingSeconds)} l="En movimiento"/><Metric v={`${fmt(s.elevationMeters,0)} m`} l="Desnivel"/><Metric v={s.avgSpeedKmh==null?'—':`${fmt(s.avgSpeedKmh)} km/h`} l="Vel. media"/><Metric v={s.maxSpeedKmh==null?'—':`${fmt(s.maxSpeedKmh)} km/h`} l="Vel. máxima"/><Metric v={s.tasksCompleted} l="Deberes hechos"/><Metric v={s.classesDone} l="Clases realizadas"/></section>
      <StudentEditor profile={p} onSaved={()=>setRefresh(x=>x+1)} />
      <GroupsEditor profile={p} onSaved={()=>setRefresh(x=>x+1)} />
      <Block title="Resumen deportivo"><div className="grid grid-cols-2 gap-3 text-xs"><Datum l="Estado" v={p.estado||'Activo'}/><Datum l="Ciudad" v={p.ciudad||'—'}/><Datum l="Instagram" v={p.instagram||'—'}/><Datum l="Calorías Strava" v={s.calories==null?'No disponible':fmt(s.calories,0)}/></div></Block>
      <Block title="Últimas actividades · Strava"><div className="space-y-2">{report.activities.slice(0,8).map(a=><div key={a.id||a.strava_activity_id} className="rounded-2xl border border-white/[.06] bg-black/20 p-3"><div className="flex justify-between gap-3"><div className="min-w-0"><p className="truncate text-xs font-black">{a.nombre||'Patinaje en línea'}</p><p className="mt-1 text-[9px] text-white/30">{a.fecha_inicio?new Date(a.fecha_inicio).toLocaleDateString('es-UY'):'—'} · {a.deporte_strava||'Inline skate'}</p></div><p className="shrink-0 text-sm font-black text-amber-200">{fmt(Number(a.distancia_metros||0)/1000)} km</p></div></div>)}{!report.activities.length&&<Empty t="No hay actividades inline en este período."/>}</div></Block>
      <Block title="Deberes"><p className="mb-3 text-[10px] text-white/30">{s.tasksCompleted} completados · {report.trainingResults.length} registros</p>{report.trainingResults.slice(0,6).map(r=><Row key={r.id} a={r.pr_training_tasks?.title||'Deber PR'} b={r.status||'Pendiente'}/>)}{!report.trainingResults.length&&<Empty t="Sin deberes registrados."/>}</Block>
      <Block title="Tomas de tiempo"><div className="space-y-2">{report.takes.slice(0,6).map(t=><Row key={t.id} a={`${t.distancia_km||'—'} km · Toma ${t.numero_toma||'—'}`} b={t.tiempo_segundos?duration(t.tiempo_segundos):'—'}/>)}{!report.takes.length&&<Empty t="Sin tomas en el período."/>}</div></Block>
      <Block title="Objetivos y observaciones"><div className="space-y-2">{report.goals.slice(0,4).map(g=><Row key={g.id} a={g.titulo||'Objetivo'} b={g.estado||'Activo'}/>)}{report.notes.slice(0,4).map(n=><div key={n.id} className="rounded-2xl bg-white/[.035] p-3 text-[11px] leading-5 text-white/55">{n.body}</div>)}{!report.goals.length&&!report.notes.length&&<Empty t="Sin objetivos u observaciones registradas."/>}</div></Block>
      <section><p className="mb-3 text-[9px] font-black uppercase tracking-[.18em] text-white/25">EXPORTAR INFORME · DATOS REALES</p><div className="grid grid-cols-2 gap-3"><button disabled={!!exporting} onClick={()=>download('pdf')} className="rounded-2xl border border-red-300/15 bg-red-300/[.07] py-4 text-xs font-black text-red-100 disabled:opacity-40">{exporting==='pdf'?'GENERANDO…':'DESCARGAR PDF'}</button><button disabled={!!exporting} onClick={()=>download('xlsx')} className="rounded-2xl border border-emerald-300/15 bg-emerald-300/[.07] py-4 text-xs font-black text-emerald-100 disabled:opacity-40">{exporting==='xlsx'?'GENERANDO…':'DESCARGAR EXCEL'}</button></div><p className="mt-2 text-[9px] leading-4 text-white/25">Se genera desde los datos del expediente. No es una captura de esta pantalla.</p></section>
    </>}
  </div></AppLayout>
}

function StudentEditor({profile,onSaved}){
  const[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[msg,setMsg]=useState('')
  const[form,setForm]=useState({})
  useEffect(()=>setForm({nombre:profile.nombre||'',apellido:profile.apellido||'',email:profile.email||'',telefono:profile.telefono||'',ciudad:profile.ciudad||'',instagram:profile.instagram||'',fecha_nacimiento:profile.fecha_nacimiento||'',estado:profile.estado||'Activo'}),[profile.id,profile.updated_at])
  const set=(k,v)=>setForm(x=>({...x,[k]:v}))
  async function save(){try{setSaving(true);setMsg('');if(!form.nombre?.trim())throw new Error('El nombre no puede quedar vacío.');const safe={nombre:form.nombre.trim(),apellido:form.apellido?.trim()||'',email:form.email?.trim()||'',telefono:form.telefono?.trim()||'',ciudad:form.ciudad?.trim()||'',instagram:form.instagram?.trim()||'',fecha_nacimiento:form.fecha_nacimiento||'',estado:form.estado,updated_at:new Date().toISOString()};const{error}=await supabase.from('profiles').update(safe).eq('id',profile.id);if(error)throw error;setMsg('Datos actualizados. Login y PIN no fueron modificados.');onSaved?.()}catch(e){setMsg(`No se pudo guardar: ${e.message}`)}finally{setSaving(false)}}
  return <Block title="Datos del alumno"><button onClick={()=>setOpen(v=>!v)} className="w-full rounded-2xl border border-white/10 bg-white/[.04] px-4 py-3 text-left text-xs font-black">{open?'CERRAR EDICIÓN':'EDITAR FICHA'}</button>{open&&<div className="mt-4 space-y-3"><div className="grid grid-cols-2 gap-2"><Input label="Nombre" value={form.nombre} onChange={v=>set('nombre',v)}/><Input label="Apellido" value={form.apellido} onChange={v=>set('apellido',v)}/></div><Input label="Email" value={form.email} onChange={v=>set('email',v)} type="email"/><Input label="Teléfono" value={form.telefono} onChange={v=>set('telefono',v)}/><div className="grid grid-cols-2 gap-2"><Input label="Ciudad" value={form.ciudad} onChange={v=>set('ciudad',v)}/><Input label="Instagram" value={form.instagram} onChange={v=>set('instagram',v)}/></div><Input label="Nacimiento" value={form.fecha_nacimiento} onChange={v=>set('fecha_nacimiento',v)} type="date"/><label className="block"><span className="mb-1 block text-[9px] font-black uppercase tracking-wider text-white/30">Estado</span><select value={form.estado||'Activo'} onChange={e=>set('estado',e.target.value)} className="w-full rounded-2xl border border-white/10 bg-black/30 px-3 py-3 text-xs text-white"><option>Activo</option><option>Pausado</option><option>Inactivo</option></select></label><div className="rounded-2xl border border-emerald-300/10 bg-emerald-300/[.04] p-3 text-[9px] leading-4 text-emerald-100/60">Zona segura: esta ficha no edita documento, PIN, rol ni cuenta de autenticación.</div>{msg&&<p className="text-[10px] text-amber-100/70">{msg}</p>}<button disabled={saving} onClick={save} className="w-full rounded-2xl bg-amber-300 py-3 text-xs font-black text-black disabled:opacity-40">{saving?'GUARDANDO…':'GUARDAR DATOS'}</button></div>}</Block>
}

function GroupsEditor({profile,onSaved}){
  const[catalog,setCatalog]=useState([]),[selected,setSelected]=useState([]),[saving,setSaving]=useState(false),[msg,setMsg]=useState('')
  useEffect(()=>{const current=(profile.grupos_info||[]).map(g=>g.group_id||groupTitle(g)).filter(Boolean);setSelected(current);supabase.from('pr_groups').select('*').eq('activo',true).order('nombre').then(({data,error})=>{if(!error)setCatalog(data||[])})},[profile.id,profile.updated_at])
  function checked(g){return selected.includes(g.id)||selected.includes(g.nombre)}
  function toggle(g){setSelected(x=>checked(g)?x.filter(v=>v!==g.id&&v!==g.nombre):[...x,g.id])}
  async function save(){try{setSaving(true);setMsg('');const grupos_info=catalog.filter(checked).map(g=>({group_id:g.id,titulo:g.nombre,link:g.link||''}));const{error}=await supabase.from('profiles').update({grupos_info,updated_at:new Date().toISOString()}).eq('id',profile.id);if(error)throw error;setMsg('Grupos actualizados sin duplicados.');onSaved?.()}catch(e){setMsg(`No se pudo guardar: ${e.message}`)}finally{setSaving(false)}}
  return <Block title="Grupos PR"><p className="mb-3 text-[10px] leading-4 text-white/30">Asignación desde el catálogo central. No modifica reservas, pagos ni acceso.</p><div className="space-y-2">{catalog.map(g=><button key={g.id} onClick={()=>toggle(g)} className={`flex w-full items-center justify-between rounded-2xl border p-3 text-left ${checked(g)?'border-amber-300/25 bg-amber-300/[.08]':'border-white/[.06] bg-black/20'}`}><span className="text-[11px] font-bold text-white/70">{g.nombre}</span><span className={`rounded-full px-2 py-1 text-[8px] font-black ${checked(g)?'bg-amber-300 text-black':'bg-white/[.06] text-white/30'}`}>{checked(g)?'ASIGNADO':'AGREGAR'}</span></button>)}{!catalog.length&&<Empty t="No hay grupos activos en el catálogo."/>}</div>{msg&&<p className="mt-3 text-[10px] text-amber-100/70">{msg}</p>}<button disabled={saving} onClick={save} className="mt-3 w-full rounded-2xl border border-amber-300/20 bg-amber-300/[.09] py-3 text-xs font-black text-amber-100 disabled:opacity-40">{saving?'GUARDANDO…':'GUARDAR GRUPOS'}</button></Block>
}

function Input({label,value,onChange,type='text'}){return <label className="block"><span className="mb-1 block text-[9px] font-black uppercase tracking-wider text-white/30">{label}</span><input type={type} value={value||''} onChange={e=>onChange(e.target.value)} className="w-full rounded-2xl border border-white/10 bg-black/30 px-3 py-3 text-xs text-white outline-none focus:border-amber-300/30"/></label>}
function Metric({v,l}){return <div className="rounded-[20px] border border-white/[.07] bg-white/[.025] p-3"><p className="text-lg font-black">{v}</p><p className="mt-1 text-[8px] uppercase tracking-wider text-white/30">{l}</p></div>}
function Block({title,children}){return <section className="rounded-[26px] border border-white/[.07] bg-white/[.025] p-4"><h2 className="mb-4 text-base font-black">{title}</h2>{children}</section>}
function Datum({l,v}){return <div><p className="text-[8px] font-black uppercase tracking-wider text-white/25">{l}</p><p className="mt-1 break-words text-white/70">{v}</p></div>}
function Row({a,b}){return <div className="mb-2 flex items-center justify-between gap-3 rounded-2xl bg-black/20 p-3"><p className="text-[11px] font-bold text-white/65">{a}</p><p className="shrink-0 text-[9px] font-black uppercase text-amber-200">{b}</p></div>}
function Empty({t}){return <p className="rounded-2xl bg-black/20 p-3 text-[10px] text-white/25">{t}</p>}
