import { useEffect,useState } from 'react'
import { useNavigate,useParams } from 'react-router-dom'
import AppLayout from '../layouts/AppLayout'
import ProfileAvatar from '../components/ProfileAvatar'
import { loadStudentReport } from '../lib/studentReport'

const periods=[['30d','30 días'],['90d','90 días'],['6m','6 meses'],['1y','1 año'],['all','Histórico']]
const fmt=(n,d=1)=>Number(n||0).toLocaleString('es-UY',{maximumFractionDigits:d})
const duration=(s)=>{s=Number(s||0);const h=Math.floor(s/3600),m=Math.floor((s%3600)/60);return h?`${h} h ${m} min`:`${m} min`}
export default function AdminAlumnoFicha(){
 const {id}=useParams(),navigate=useNavigate(),[period,setPeriod]=useState('90d'),[report,setReport]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{let live=true;setLoading(true);setError('');loadStudentReport(id,period).then(r=>live&&setReport(r)).catch(e=>live&&setError(e?.message||'No pude cargar la ficha.')).finally(()=>live&&setLoading(false));return()=>{live=false}},[id,period])
 const p=report?.profile||{},s=report?.summary||{}
 return <AppLayout title="Ficha Deportiva PR" showBack><div className="pr-page space-y-5 pb-14">
  <section className="rounded-[32px] border border-amber-300/15 bg-gradient-to-br from-amber-300/[.11] via-white/[.025] to-transparent p-5"><div className="flex items-center gap-4"><ProfileAvatar profile={p} className="h-16 w-16 shrink-0" rounded="rounded-full"/><div className="min-w-0"><p className="text-[9px] font-black uppercase tracking-[.22em] text-amber-200">EXPEDIENTE DEPORTIVO</p><h1 className="mt-1 truncate text-2xl font-black">{[p.nombre,p.apellido].filter(Boolean).join(' ')||'Alumno PR'}</h1><p className="mt-1 text-[10px] text-white/35">{(p.grupos_info||[]).map(g=>g.titulo||g.nombre).filter(Boolean).join(' · ')||p.ciudad||'Punta Rollers'}</p></div></div><div className="mt-5 flex gap-2 overflow-x-auto pb-1">{periods.map(([v,l])=><button key={v} onClick={()=>setPeriod(v)} className={`shrink-0 rounded-full px-3 py-2 text-[9px] font-black ${period===v?'bg-amber-300 text-black':'border border-white/10 text-white/40'}`}>{l}</button>)}</div></section>
  {loading&&<div className="rounded-2xl bg-white/[.03] p-6 text-center text-xs text-white/30">Construyendo expediente…</div>}{error&&<div className="rounded-2xl border border-red-300/15 bg-red-400/[.06] p-4 text-xs text-red-100">{error}</div>}
  {report&&!loading&&<><section className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric v={`${fmt(s.km)} km`} l="Patinaje inline"/><Metric v={s.activities} l="Actividades"/><Metric v={duration(s.movingSeconds)} l="En movimiento"/><Metric v={`${fmt(s.elevationMeters,0)} m`} l="Desnivel"/><Metric v={s.avgSpeedKmh==null?'—':`${fmt(s.avgSpeedKmh)} km/h`} l="Vel. media"/><Metric v={s.maxSpeedKmh==null?'—':`${fmt(s.maxSpeedKmh)} km/h`} l="Vel. máxima"/><Metric v={s.tasksCompleted} l="Deberes hechos"/><Metric v={s.classesDone} l="Clases realizadas"/></section>
  <Block title="Resumen deportivo"><div className="grid grid-cols-2 gap-3 text-xs"><Datum l="Estado" v={p.estado||'Activo'}/><Datum l="Ciudad" v={p.ciudad||'—'}/><Datum l="Instagram" v={p.instagram||'—'}/><Datum l="Calorías Strava" v={s.calories==null?'No disponible':fmt(s.calories,0)}/></div></Block>
  <Block title="Últimas actividades · Strava"><div className="space-y-2">{report.activities.slice(0,8).map(a=><div key={a.id||a.strava_activity_id} className="rounded-2xl border border-white/[.06] bg-black/20 p-3"><div className="flex justify-between gap-3"><div className="min-w-0"><p className="truncate text-xs font-black">{a.nombre||'Patinaje en línea'}</p><p className="mt-1 text-[9px] text-white/30">{a.fecha_inicio?new Date(a.fecha_inicio).toLocaleDateString('es-UY'):'—'} · {a.deporte_strava||'Inline skate'}</p></div><p className="shrink-0 text-sm font-black text-amber-200">{fmt(Number(a.distancia_metros||0)/1000)} km</p></div></div>)}{!report.activities.length&&<Empty t="No hay actividades inline en este período."/>}</div></Block>
  <Block title="Deberes"><p className="mb-3 text-[10px] text-white/30">{s.tasksCompleted} completados · {report.trainingResults.length} registros</p>{report.trainingResults.slice(0,6).map(r=><Row key={r.id} a={r.pr_training_tasks?.title||'Deber PR'} b={r.status||'Pendiente'}/>)}{!report.trainingResults.length&&<Empty t="Sin deberes registrados."/>}</Block>
  <Block title="Tomas de tiempo"><div className="space-y-2">{report.takes.slice(0,6).map(t=><Row key={t.id} a={`${t.distancia_km||'—'} km · Toma ${t.numero_toma||'—'}`} b={t.tiempo_segundos?duration(t.tiempo_segundos):'—'}/>)}{!report.takes.length&&<Empty t="Sin tomas en el período."/>}</div></Block>
  <Block title="Objetivos y observaciones"><div className="space-y-2">{report.goals.slice(0,4).map(g=><Row key={g.id} a={g.titulo||'Objetivo'} b={g.estado||'Activo'}/>)}{report.notes.slice(0,4).map(n=><div key={n.id} className="rounded-2xl bg-white/[.035] p-3 text-[11px] leading-5 text-white/55">{n.body}</div>)}{!report.goals.length&&!report.notes.length&&<Empty t="Sin objetivos u observaciones registradas."/>}</div></Block>
  <section className="grid grid-cols-2 gap-3"><button onClick={()=>navigate(`/admin/alumnos/${id}/exportar?format=pdf&period=${period}`)} className="rounded-2xl border border-red-300/15 bg-red-300/[.07] py-4 text-xs font-black text-red-100">DESCARGAR PDF</button><button onClick={()=>navigate(`/admin/alumnos/${id}/exportar?format=xlsx&period=${period}`)} className="rounded-2xl border border-emerald-300/15 bg-emerald-300/[.07] py-4 text-xs font-black text-emerald-100">DESCARGAR EXCEL</button></section></>}
 </div></AppLayout>
}
function Metric({v,l}){return <div className="rounded-[20px] border border-white/[.07] bg-white/[.025] p-3"><p className="text-lg font-black">{v}</p><p className="mt-1 text-[8px] uppercase tracking-wider text-white/30">{l}</p></div>}
function Block({title,children}){return <section className="rounded-[26px] border border-white/[.07] bg-white/[.025] p-4"><h2 className="mb-4 text-base font-black">{title}</h2>{children}</section>}
function Datum({l,v}){return <div><p className="text-[8px] font-black uppercase tracking-wider text-white/25">{l}</p><p className="mt-1 break-words text-white/70">{v}</p></div>}
function Row({a,b}){return <div className="mb-2 flex items-center justify-between gap-3 rounded-2xl bg-black/20 p-3"><p className="text-[11px] font-bold text-white/65">{a}</p><p className="shrink-0 text-[9px] font-black uppercase text-amber-200">{b}</p></div>}
function Empty({t}){return <p className="rounded-2xl bg-black/20 p-3 text-[10px] text-white/25">{t}</p>}
