import {useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {supabase} from '../lib/supabase'
export default function AdminKidsSolicitudes(){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState('')
 async function invoke(body){const {data,error}=await supabase.functions.invoke('pr-kids-family-access',{body});if(error||data?.error)throw Error(data?.error||error?.message||'No se pudo completar la operación');return data}
 async function load(){setLoading(true);try{const r=await invoke({action:'list'});setRows(r.requests||[]);setError('')}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 async function reject(id){if(!window.confirm('¿Rechazar esta solicitud?'))return;setBusy(id);try{await invoke({action:'reject',id});await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 return <main className="min-h-screen bg-[#090b13] px-4 py-8 text-white"><div className="mx-auto max-w-4xl"><Link to="/admin" className="text-sm font-bold text-white/60">← Administración</Link><p className="mt-8 text-xs font-black uppercase tracking-widest text-[#c2afff]">Punta Rollers · PR Kids Manager</p><h1 className="mt-2 text-4xl font-black">Solicitudes familiares</h1><p className="mt-3 text-sm leading-6 text-white/50">Solicitudes enviadas desde /kids. Verificá la identidad del adulto y su vínculo con el niño antes de habilitar cualquier acceso. La activación automática aún no está disponible.</p><button onClick={load} className="mt-5 rounded-xl border border-white/20 px-4 py-2 text-sm font-bold">Actualizar</button>{error&&<p className="mt-4 text-red-300">{error}</p>}{loading?<p className="mt-8 text-white/50">Cargando…</p>:<div className="mt-7 space-y-3">{rows.length===0&&<p className="rounded-xl bg-white/5 p-6 text-white/50">No hay solicitudes todavía.</p>}{rows.map(r=><article key={r.id} className="rounded-2xl border border-white/10 bg-[#1b2235] p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-black">{Array.isArray(r.hijos)&&r.hijos.length>1?`${r.hijos.length} hermanos`:r.nombre_nino}</h2><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">{r.estado}</span></div>{Array.isArray(r.hijos)&&r.hijos.length>0&&<div className="mt-3 flex flex-wrap gap-2">{r.hijos.map((h,i)=><span key={i} className="rounded-xl border border-violet-300/20 bg-violet-300/10 px-3 py-2 text-xs font-bold text-violet-100">{h.nombre}</span>)}</div>}<p className="mt-2 text-sm text-white/75">Tutor: {r.nombre_tutor} · {r.vinculo}</p><p className="mt-1 text-sm text-white/60">Documento: {r.documento_tutor}</p><p className="mt-1 break-all text-sm text-white/60">{r.email_tutor} · {r.telefono_tutor}</p><p className="mt-1 text-xs text-white/40">{r.es_alumno?'Indica que ya es alumno':'Indica que no es alumno'} · {new Date(r.created_at).toLocaleDateString('es-UY')}</p>{r.estado==='pendiente'&&<div className="mt-4 flex flex-wrap gap-2"><span className="rounded-lg bg-amber-300/10 px-3 py-2 text-xs font-bold text-amber-200">Pendiente de verificación y vinculación</span><button disabled={Boolean(busy)} onClick={()=>reject(r.id)} className="rounded-lg border border-red-300/20 px-3 py-2 text-xs font-bold text-red-200">Rechazar</button></div>}</article>)}</div>}</div></main>
}