import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import AppLayout from '../layouts/AppLayout'
import ProfileAvatar from '../components/ProfileAvatar'
import { supabase } from '../lib/supabase'

function isStudent(p){return p?.role==='alumno'||p?.participa_como_alumno===true}
function fullName(p){return [p?.nombre,p?.apellido].filter(Boolean).join(' ')||'Patinador PR'}
function groupNames(p){return (Array.isArray(p?.grupos_info)?p.grupos_info:[]).map(g=>g?.titulo||g?.nombre).filter(Boolean)}

export default function AdminAlumnos(){
 const navigate=useNavigate(),[rows,setRows]=useState([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{let alive=true;(async()=>{const {data,error}=await supabase.from('profiles').select('id,nombre,apellido,foto,role,participa_como_alumno,estado,email,ciudad,instagram,verificado,prcard_activa,tracking_activo,grupos_info,mensualidad_hasta,exento_mensualidad').order('nombre');if(error)throw error;if(alive)setRows((data||[]).filter(isStudent))})().catch(()=>alive&&setError('No pude cargar los alumnos.')).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[])
 const filtered=useMemo(()=>{const needle=q.trim().toLowerCase();if(!needle)return rows;return rows.filter(p=>[fullName(p),p.email,p.ciudad,p.instagram,...groupNames(p)].filter(Boolean).join(' ').toLowerCase().includes(needle))},[rows,q])
 const active=rows.filter(p=>String(p.estado||'Activo').toLowerCase()!=='inactivo').length
 return <AppLayout title="Alumnos"><div className="pr-page space-y-5 pb-14">
  <section className="rounded-[32px] border border-amber-300/15 bg-gradient-to-br from-amber-300/[.10] via-white/[.025] to-transparent p-5"><p className="text-[9px] font-black uppercase tracking-[.24em] text-amber-200">PR CONTROL · PERSONAS</p><h1 className="mt-2 text-3xl font-black">Alumnos</h1><p className="mt-2 text-sm leading-6 text-white/40">Una vista limpia para encontrar personas, ver su situación y entrar a su seguimiento sin mezclar toda la administración.</p><div className="mt-5 grid grid-cols-3 gap-2"><Stat n={loading?'—':rows.length} l="Patinadores"/><Stat n={loading?'—':active} l="Activos"/><Stat n={loading?'—':rows.filter(p=>groupNames(p).length).length} l="Con grupo"/></div></section>
  <section className="rounded-[28px] border border-white/[.075] bg-white/[.025] p-4"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por nombre, grupo, ciudad…" className="w-full rounded-2xl border border-white/10 bg-black/25 px-4 py-3 text-sm text-white outline-none placeholder:text-white/25"/>{error&&<p className="mt-3 text-xs text-amber-200">{error}</p>}<div className="mt-4 space-y-2">{loading?<p className="p-4 text-xs text-white/30">Cargando alumnos…</p>:filtered.map(p=><article key={p.id} className="rounded-[22px] border border-white/[.07] bg-black/20 p-3"><div className="flex items-center gap-3"><ProfileAvatar profile={p} className="h-12 w-12 shrink-0" rounded="rounded-full"/><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-sm font-black">{fullName(p)}</p>{p.verificado&&<span className="text-[8px] font-black text-amber-200">PR</span>}</div><p className="mt-1 truncate text-[10px] text-white/35">{groupNames(p).join(' · ')||p.ciudad||'Sin grupo asignado'}</p></div><span className={`rounded-full px-2 py-1 text-[8px] font-black uppercase ${String(p.estado||'Activo').toLowerCase()==='inactivo'?'bg-white/[.06] text-white/30':'bg-emerald-300/10 text-emerald-200'}`}>{p.estado||'Activo'}</span></div><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>navigate(`/admin/alumnos/${encodeURIComponent(p.id)}`)} className="rounded-xl border border-amber-300/15 bg-amber-300/[.06] py-2.5 text-[10px] font-black text-amber-100">FICHA DEPORTIVA</button><button onClick={()=>navigate('/admin/performance')} className="rounded-xl border border-violet-300/15 bg-violet-300/[.07] py-2.5 text-[10px] font-black text-violet-200">RENDIMIENTO</button></div></article>)}{!loading&&!filtered.length&&<p className="p-4 text-xs text-white/30">No encontré alumnos con esa búsqueda.</p>}</div></section>
  <section className="grid grid-cols-2 gap-3"><button onClick={()=>navigate('/admin/nuevos-accesos')} className="rounded-[22px] border border-cyan-300/15 bg-cyan-300/[.055] p-4 text-left"><p className="text-[8px] font-black uppercase tracking-[.18em] text-cyan-200">ACCESOS</p><p className="mt-2 text-sm font-black">Nuevas solicitudes</p></button><button onClick={()=>navigate('/admin/legacy')} className="rounded-[22px] border border-white/[.08] bg-white/[.025] p-4 text-left"><p className="text-[8px] font-black uppercase tracking-[.18em] text-white/30">RESPALDO</p><p className="mt-2 text-sm font-black">Gestión avanzada</p></button></section>
 </div></AppLayout>
}
function Stat({n,l}){return <div className="rounded-[18px] border border-white/[.07] bg-black/20 p-3"><p className="text-xl font-black">{n}</p><p className="mt-1 text-[8px] uppercase tracking-wider text-white/30">{l}</p></div>}
