import { useEffect, useMemo, useState } from 'react'
import AppLayout from '../layouts/AppLayout'
import { useAuth } from '../lib/auth'
import { PR_SEASON_ASSETS } from '../lib/prSeason'
import { supabase } from '../lib/supabase'
export default function AttendanceNext(){
 const{user}=useAuth(),name=[user?.nombre,user?.apellido].filter(Boolean).join(' ')||'Alumno Punta Rollers';const[idReady,setIdReady]=useState(true),[rows,setRows]=useState([]),[supported,setSupported]=useState(true),[loading,setLoading]=useState(true)
 useEffect(()=>{let alive=true;(async()=>{if(!user?.id)return;const r=await supabase.from('pr_check_records').select('id,status,source,checked_at,note,session_id').eq('profile_id',user.id).order('checked_at',{ascending:false}).limit(60);if(!alive)return;if(r.error){setSupported(false);setRows([])}else setRows(r.data||[]);setLoading(false)})().catch(()=>{if(alive){setSupported(false);setLoading(false)}});return()=>{alive=false}},[user?.id])
 const stats=useMemo(()=>({present:rows.filter(x=>x.status==='presente').length,justified:rows.filter(x=>x.status==='justificado').length,total:rows.length}),[rows])
 return <AppLayout title="Asistencia"><main className="mx-auto w-full max-w-[720px] space-y-4 px-4 pb-32 pt-4 text-white">
  <section className="relative overflow-hidden rounded-[36px] border border-cyan-300/15 bg-[#090d10] p-6"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-cyan-400/10 blur-3xl"/><div className="absolute -bottom-20 left-8 h-48 w-48 rounded-full bg-violet-500/10 blur-3xl"/><div className="relative"><div className="flex items-center justify-between"><p className="text-[8px] font-black tracking-[.24em] text-cyan-200">PR CHECK · TU IDENTIDAD</p><span className="rounded-full border border-cyan-200/10 px-3 py-1 text-[7px] font-black text-cyan-100/35">ID PERSONAL</span></div><h1 className="mt-3 text-[32px] font-black tracking-[-.04em]">Tu entrada a Punta Rollers.</h1><p className="mt-3 max-w-[480px] text-[11px] leading-5 text-white/38">Un solo PR ID para clases, eventos y experiencias. Cada check válido se transforma en parte de tu historia.</p></div></section>
  <section className="rounded-[32px] border border-white/[.07] bg-[#101015] p-5"><div className="flex items-center justify-between"><div><p className="text-[8px] font-black tracking-[.18em] text-white/25">PR MEMBER</p><h2 className="mt-1 text-xl font-black">{name}</h2></div><span className="rounded-full border border-emerald-300/15 bg-emerald-300/[.06] px-3 py-1 text-[8px] font-black text-emerald-200">ACTIVO</span></div><div className="mt-5 grid place-items-center rounded-[26px] border border-cyan-300/10 bg-cyan-300/[.035] p-5">{idReady?<img src={PR_SEASON_ASSETS.qrIdLogo} onError={()=>setIdReady(false)} alt="PR ID" className="max-h-[330px] w-full max-w-[260px] object-contain"/>:<div className="grid min-h-[220px] w-full max-w-[260px] place-items-center rounded-[22px] border border-dashed border-white/10 p-6 text-center"><div><p className="text-[9px] font-black text-cyan-200/65">PR ID</p><p className="mt-2 text-[9px] leading-4 text-white/25">Identidad preparada. El recurso visual oficial todavía no está disponible en este build.</p></div></div>}</div><p className="mt-4 text-center text-[8px] font-black uppercase tracking-[.16em] text-white/20">Mostrá este ID al profesor para registrar tu asistencia</p></section>
  <section className="grid grid-cols-3 gap-2"><Mini v={loading?'—':supported?stats.present:'—'} l="PRESENTE"/><Mini v={loading?'—':supported?stats.justified:'—'} l="JUSTIFICADAS"/><Mini v={loading?'—':supported?stats.total:'—'} l="REGISTROS"/></section>
  <section className="rounded-[28px] border border-white/[.07] bg-white/[.02] p-5"><div className="flex items-end justify-between"><div><p className="text-[8px] font-black tracking-[.18em] text-white/25">HISTORIAL</p><h2 className="mt-1 text-xl font-black">Tu asistencia, sin inventar nada.</h2></div>{supported&&rows.length>0&&<span className="text-[7px] font-black text-cyan-200/45">PR CHECK</span>}</div>{loading?<p className="mt-4 text-[9px] text-white/25">Buscando registros…</p>:!supported?<p className="mt-4 text-[10px] leading-5 text-white/30">La interfaz ya está preparada. El historial se activará cuando la estructura PR Check pase el QA de base de datos.</p>:rows.length===0?<div className="mt-4 rounded-[20px] border border-dashed border-white/[.08] p-5 text-center"><p className="text-[9px] font-black text-white/35">TODAVÍA NO HAY CHECKS</p><p className="mt-2 text-[9px] text-white/22">Tu primer registro aparecerá acá.</p></div>:<div className="mt-4 space-y-2">{rows.map(r=><div key={r.id} className="flex items-center justify-between rounded-[18px] border border-white/[.06] bg-black/15 p-3"><div><p className="text-[9px] font-black capitalize">{r.status}</p><p className="mt-1 text-[8px] text-white/25">{new Date(r.checked_at).toLocaleDateString('es-UY',{day:'2-digit',month:'short',year:'numeric'})} · {r.source==='qr'?'QR ID':'Registro '+r.source}</p></div><span className={'h-2 w-2 rounded-full '+(r.status==='presente'?'bg-emerald-300':'bg-white/20')}/></div>)}</div>}</section>
 </main></AppLayout>}
function Mini({v,l}){return <div className="rounded-[20px] border border-white/[.07] bg-black/20 p-4 text-center"><p className="text-xl font-black">{v}</p><p className="mt-1 text-[7px] font-black tracking-[.12em] text-white/22">{l}</p></div>}
