import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import AppLayout from '../layouts/AppLayout'
import { supabase } from '../lib/supabase'
import VerifiedBadge from '../components/VerifiedBadge'
import ProfileAvatar from '../components/ProfileAvatar'
import CommunitySocial from '../components/community/CommunitySocial'

const tabs=[{id:'explorar',label:'Descubrir',icon:'✦'},{id:'solicitudes',label:'Solicitudes',icon:'◌'},{id:'amigos',label:'Amigos',icon:'◎'}]
const fullName=p=>[p?.nombre,p?.apellido].filter(Boolean).join(' ').trim()||'Roller PR'
const clean=v=>String(v||'').trim()
function Pill({children}){return <span className="rounded-full border border-white/10 bg-white/[.05] px-2 py-1 text-[8px] font-black uppercase tracking-[.12em] text-white/45">{children}</span>}
function ProfileCard({profile,busy,onSendRequest,onCancelRequest,onAcceptRequest,onRejectRequest,onRemoveFriend,onMessageFriend,onViewProfile}){const r=profile.relationship_status||'none';const canOpen=r==='friend';return <article onClick={()=>canOpen&&onViewProfile(profile.id)} className={`group relative overflow-hidden rounded-[28px] border border-white/[.08] bg-gradient-to-br from-white/[.055] to-white/[.015] p-4 ${canOpen?'cursor-pointer active:scale-[.99]':''}`}><div className="absolute -right-16 -top-20 h-36 w-36 rounded-full bg-orange-500/10 blur-3xl"/><div className="relative flex gap-3"><ProfileAvatar profile={profile} className="h-16 w-16" rounded="rounded-[22px]"/><div className="min-w-0 flex-1"><div className="flex items-center gap-1.5"><h3 className="truncate text-[15px] font-black text-white">{fullName(profile)}</h3>{profile.verificado&&<VerifiedBadge size={18}/>}</div><div className="mt-1.5 flex flex-wrap gap-1.5">{profile.ciudad&&<Pill>{profile.ciudad}</Pill>}{r==='friend'&&<span className="rounded-full border border-orange-300/15 bg-orange-400/[.08] px-2 py-1 text-[8px] font-black uppercase tracking-[.12em] text-orange-200">EN TU CÍRCULO</span>}</div>{profile.sobre_mi&&<p className="mt-2 line-clamp-2 text-[11px] leading-5 text-white/38">{profile.sobre_mi}</p>}</div>{canOpen&&<span className="mt-1 text-xl text-white/20">›</span>}</div><div className="relative mt-3" onClick={e=>e.stopPropagation()}>{r==='incoming'&&<div className="grid grid-cols-2 gap-2"><button disabled={busy} onClick={()=>onRejectRequest(profile.request_id)} className="rounded-2xl border border-white/10 py-3 text-xs font-bold text-white/50">Ahora no</button><button disabled={busy} onClick={()=>onAcceptRequest(profile.request_id)} className="rounded-2xl bg-orange-500 py-3 text-xs font-black text-black">Aceptar</button></div>}{r==='outgoing'&&<button disabled={busy} onClick={()=>onCancelRequest(profile.request_id)} className="w-full rounded-2xl border border-white/10 py-3 text-xs font-bold text-white/55">Solicitud enviada · cancelar</button>}{r==='friend'&&<div className="flex gap-2"><button onClick={()=>onViewProfile(profile.id)} className="flex-1 rounded-2xl border border-orange-300/15 bg-orange-500/[.08] py-3 text-[10px] font-black text-orange-100">VER PERFIL</button><button onClick={()=>onMessageFriend(profile.id)} className="rounded-2xl bg-white/[.07] px-4 text-sm">💬</button><button onClick={()=>onRemoveFriend(profile.id)} className="rounded-2xl bg-white/[.04] px-3 text-white/30">···</button></div>}{r==='none'&&<button disabled={busy} onClick={()=>onSendRequest(profile.id)} className="w-full rounded-2xl bg-gradient-to-r from-orange-500 to-amber-300 py-3 text-xs font-black text-black">＋ SUMAR A MI CÍRCULO</button>}</div></article>}
function Empty({title,text}){return <div className="rounded-[28px] border border-dashed border-white/10 bg-white/[.02] p-8 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-white/[.04] text-xl">✦</div><h3 className="mt-3 font-display text-2xl text-white">{title}</h3><p className="mx-auto mt-2 max-w-[280px] text-xs leading-5 text-white/35">{text}</p></div>}
export default function CommunityPage(){const navigate=useNavigate();const[activeTab,setActiveTab]=useState('explorar');const[query,setQuery]=useState('');const[directory,setDirectory]=useState([]);const[suggestions,setSuggestions]=useState([]);const[incomingRequests,setIncomingRequests]=useState([]);const[outgoingRequests,setOutgoingRequests]=useState([]);const[friends,setFriends]=useState([]);const[loading,setLoading]=useState(true);const[searching,setSearching]=useState(false);const[busyId,setBusyId]=useState('');const[message,setMessage]=useState('');const requestCount=incomingRequests.length
async function loadCommunity(){setLoading(true);const{data,error}=await supabase.rpc('community_get_dashboard');if(error){setMessage(`No pudimos cargar Comunidad: ${error.message}`);setLoading(false);return}const p=data||{};setIncomingRequests(Array.isArray(p.incoming_requests)?p.incoming_requests:[]);setOutgoingRequests(Array.isArray(p.outgoing_requests)?p.outgoing_requests:[]);setFriends(Array.isArray(p.friends)?p.friends:[]);setLoading(false)}
async function loadSuggestions(){const{data}=await supabase.rpc('community_search_profiles',{search_text:''});const rows=Array.isArray(data)?data:[];setSuggestions([...rows].sort((a,b)=>Number(Boolean(b.foto))-Number(Boolean(a.foto))).filter(p=>(p.relationship_status||'none')!=='friend').slice(0,8))}
async function searchProfiles(value){const q=clean(value);if(q.length<2){setDirectory([]);setSearching(false);return}setSearching(true);const{data,error}=await supabase.rpc('community_search_profiles',{search_text:q});if(error){setMessage(`No pudimos buscar perfiles: ${error.message}`);setDirectory([])}else setDirectory(Array.isArray(data)?data:[]);setSearching(false)}
useEffect(()=>{loadCommunity();loadSuggestions()},[]);useEffect(()=>{const id=setTimeout(()=>searchProfiles(query),300);return()=>clearTimeout(id)},[query])
async function runAction(name,args,success,target){setBusyId(target||name);setMessage('');const{data,error}=await supabase.rpc(name,args);if(error||data?.success===false){setMessage(data?.error||error?.message||'No pudimos completar la acción.');setBusyId('');return}setMessage(success);await Promise.all([loadCommunity(),loadSuggestions(),query.length>=2?searchProfiles(query):Promise.resolve()]);setBusyId('')}
const sendRequest=id=>runAction('community_send_friend_request',{target_profile_id:id},'Solicitud enviada.',id),cancelRequest=id=>runAction('community_cancel_friend_request',{request_id_value:id},'Solicitud cancelada.',id),acceptRequest=id=>runAction('community_accept_friend_request',{request_id_value:id},'Ahora son amigos.',id),rejectRequest=id=>runAction('community_reject_friend_request',{request_id_value:id},'Solicitud rechazada.',id),messageFriend=id=>navigate(`/app/mensajes?with=${encodeURIComponent(id)}`),viewProfile=id=>navigate(`/app/comunidad/perfil/${encodeURIComponent(id)}`),removeFriend=id=>{if(window.confirm('¿Eliminar esta amistad?'))runAction('community_remove_friend',{target_profile_id:id},'Amistad eliminada.',id)}
const list=useMemo(()=>activeTab==='amigos'?friends:activeTab==='solicitudes'?incomingRequests:directory,[activeTab,friends,incomingRequests,directory]);const props={busy:Boolean(busyId),onSendRequest:sendRequest,onCancelRequest:cancelRequest,onAcceptRequest:acceptRequest,onRejectRequest:rejectRequest,onRemoveFriend:removeFriend,onMessageFriend:messageFriend,onViewProfile:viewProfile}
return <AppLayout title="Comunidad" showBack><div className="pr-page space-y-5 pb-12 animate-page-enter">
<section className="relative overflow-hidden rounded-[36px] border border-orange-300/15 bg-[#09090d] p-5"><div className="absolute -left-20 top-6 h-48 w-48 animate-pulse rounded-full bg-violet-500/10 blur-3xl"/><div className="absolute -right-16 -top-10 h-52 w-52 animate-pulse rounded-full bg-orange-500/15 blur-3xl"/><div className="relative"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-400"/><p className="text-[9px] font-black uppercase tracking-[.24em] text-white/45">PR SOCIAL · EN MOVIMIENTO</p></div><span className="rounded-full border border-white/10 bg-white/[.04] px-3 py-1.5 text-[8px] font-black text-white/35">SOLO PR</span></div><h1 className="mt-5 font-display text-[42px] leading-[.9] text-white">Tu gente.<br/><span className="bg-gradient-to-r from-orange-300 via-orange-500 to-violet-400 bg-clip-text text-transparent">Tu mundo sobre ruedas.</span></h1><p className="mt-4 max-w-[330px] text-[12px] leading-5 text-white/38">Perfiles, fotos, rolleadas y conversaciones. Todo lo que pasa entre ustedes, en un mismo lugar.</p><div className="mt-5 flex gap-2 overflow-hidden"><div className="animate-[pulse_3s_ease-in-out_infinite] rounded-2xl border border-orange-300/10 bg-orange-500/[.08] px-4 py-3"><b className="text-xl text-white">{friends.length}</b><p className="text-[8px] font-black tracking-wider text-white/30">TU CÍRCULO</p></div><button onClick={()=>setActiveTab('solicitudes')} className="rounded-2xl border border-violet-300/10 bg-violet-500/[.07] px-4 py-3 text-left"><b className="text-xl text-violet-200">{requestCount}</b><p className="text-[8px] font-black tracking-wider text-white/30">SOLICITUDES</p></button><button onClick={()=>navigate('/app/mensajes')} className="flex-1 rounded-2xl border border-white/[.07] bg-white/[.035] px-4 py-3 text-left"><b className="text-lg text-white">↗</b><p className="text-[8px] font-black tracking-wider text-white/30">PR CHAT</p></button></div></div></section>
<CommunitySocial/>{message&&<div className="rounded-2xl border border-orange-300/15 bg-orange-400/[.07] p-3 text-xs text-orange-100/80">{message}</div>}
{!loading&&friends.length>0&&<section className="overflow-hidden rounded-[30px] border border-white/[.07] bg-gradient-to-br from-white/[.045] to-transparent p-4"><div className="flex items-center justify-between"><div><p className="text-[8px] font-black uppercase tracking-[.22em] text-orange-300">TU CÍRCULO</p><h2 className="mt-1 font-display text-[27px] leading-none text-white">En tu órbita</h2><p className="mt-2 text-[10px] text-white/30">Tocá una persona y entrá directo a su perfil.</p></div><button onClick={()=>setActiveTab('amigos')} className="rounded-full border border-white/10 px-3 py-2 text-[9px] font-black text-white/55">VER TODOS</button></div><div className="mt-4 flex gap-3 overflow-x-auto pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{friends.slice(0,10).map(f=><button key={f.id} onClick={()=>viewProfile(f.id)} className="w-[76px] shrink-0 text-center active:scale-95"><div className="relative mx-auto w-fit rounded-[24px] bg-gradient-to-br from-orange-400 via-amber-200 to-violet-500 p-[2px]"><ProfileAvatar profile={f} className="h-[68px] w-[68px]" rounded="rounded-[22px]"/><span className="absolute -bottom-1 -right-1 h-4 w-4 rounded-full border-[3px] border-[#101014] bg-emerald-400"/></div><p className="mt-2 truncate text-[10px] font-black text-white/70">{f.nombre}</p></button>)}</div></section>}
<section className="sticky top-2 z-20 rounded-[25px] border border-white/[.08] bg-[#101014]/90 p-1.5 shadow-2xl backdrop-blur-xl"><div className="grid grid-cols-3 gap-1">{tabs.map(t=><button key={t.id} onClick={()=>setActiveTab(t.id)} className={`relative min-h-12 rounded-[19px] text-[10px] font-black transition ${activeTab===t.id?'bg-white text-black shadow-lg':'text-white/35'}`}><span className="mr-1">{t.icon}</span>{t.label}{t.id==='solicitudes'&&requestCount>0&&<span className="absolute right-2 top-2 rounded-full bg-orange-500 px-1.5 py-0.5 text-[8px] text-black">{requestCount}</span>}</button>)}</div></section>
{activeTab==='explorar'&&<><section><div className="rounded-[25px] border border-white/[.09] bg-[#0d0e13] p-2 shadow-[0_20px_70px_rgba(0,0,0,.35)]"><div className="flex items-center gap-2"><span className="pl-3 text-lg text-orange-300">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar personas en PR…" className="min-h-13 flex-1 bg-transparent px-2 text-sm text-white outline-none placeholder:text-white/25"/>{query&&<button onClick={()=>setQuery('')} className="px-3 text-white/30">×</button>}</div></div></section>{query.length<2&&suggestions.length>0&&<section><div className="mb-3"><p className="text-[8px] font-black uppercase tracking-[.22em] text-violet-300">DESCUBRIR</p><h2 className="mt-1 font-display text-[27px] text-white">Personas que quizá conozcas</h2></div><div className="grid gap-3">{suggestions.map(p=><ProfileCard key={p.id} profile={p}{...props}/>)}</div></section>}</>}
{loading?<div className="py-10 text-center text-xs text-white/30">Cargando tu círculo…</div>:activeTab==='explorar'&&query.length<2?null:searching?<div className="py-10 text-center text-xs text-white/30">Buscando…</div>:list.length?<section className="space-y-3">{list.map(p=><ProfileCard key={`${p.id}-${p.request_id||''}`} profile={p}{...props}/>)}</section>:<Empty title={activeTab==='amigos'?'Tu círculo empieza acá':activeTab==='solicitudes'?'Todo al día':'Sin coincidencias'} text={activeTab==='amigos'?'Buscá personas y sumalas a tu círculo PR.':activeTab==='solicitudes'?'No tenés solicitudes pendientes.':'Probá con otro nombre.'}/>} </div></AppLayout>}
