import { Link } from 'react-router-dom'
import AppLayout from '../layouts/AppLayout'
import CommunitySocial from '../components/community/CommunitySocial'

export default function CommunityNext(){return <AppLayout title="Comunidad"><main className="mx-auto w-full max-w-[760px] space-y-4 px-4 pb-32 pt-4 text-white">
<section className="relative overflow-hidden rounded-[36px] border border-violet-300/15 bg-[#0a0910] p-6"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-violet-600/20 blur-3xl"/><div className="absolute -bottom-20 left-0 h-48 w-48 rounded-full bg-orange-400/10 blur-3xl"/><div className="relative"><div className="flex items-center justify-between"><p className="text-[8px] font-black tracking-[.24em] text-violet-300">COMUNIDAD PR</p><span className="rounded-full border border-white/10 bg-white/[.04] px-3 py-1 text-[8px] font-black tracking-wider text-white/35">SOLO PR</span></div><h1 className="mt-7 text-[34px] font-black leading-[.98] tracking-[-.045em]">Las personas<br/><span className="text-white/45">detrás de los patines.</span></h1><p className="mt-4 max-w-[430px] text-[12px] leading-6 text-white/38">Tu círculo, cumpleaños, momentos, mensajes y todo lo que conecta a Punta Rollers fuera de la pista.</p></div></section>
<section className="grid grid-cols-2 gap-2"><Link to="/app/mensajes" className="rounded-[25px] border border-cyan-300/15 bg-cyan-300/[.045] p-5"><p className="text-[8px] font-black tracking-[.18em] text-cyan-200/60">PR CHAT</p><h2 className="mt-2 text-lg font-black">Mensajes</h2><p className="mt-2 text-[9px] leading-4 text-white/30">Conversaciones con tu comunidad.</p><span className="mt-5 block text-cyan-200/70">→</span></Link><Link to="/app/moments" className="rounded-[25px] border border-violet-300/15 bg-violet-300/[.045] p-5"><p className="text-[8px] font-black tracking-[.18em] text-violet-200/60">PR MOMENTS</p><h2 className="mt-2 text-lg font-black">Momentos</h2><p className="mt-2 text-[9px] leading-4 text-white/30">Fotos y recuerdos de la comunidad.</p><span className="mt-5 block text-violet-200/70">→</span></Link></section>
<section className="rounded-[28px] border border-white/[.07] bg-white/[.025] p-5"><div className="flex items-center justify-between"><div><p className="text-[8px] font-black tracking-[.18em] text-white/25">CUMPLEAÑOS PR</p><h2 className="mt-1 text-xl font-black">Celebramos a los nuestros.</h2></div><span className="text-2xl opacity-50">✦</span></div><p className="mt-3 text-[10px] leading-5 text-white/30">Los próximos cumpleaños van a vivir acá, sin mezclarse con RollerFeed.</p><div className="mt-4 rounded-[18px] border border-dashed border-white/10 p-4 text-center text-[9px] font-bold uppercase tracking-wider text-white/20">Próximos cumpleaños</div></section>
<section><div className="mb-3"><p className="text-[8px] font-black tracking-[.2em] text-orange-200/55">TU CÍRCULO</p><h2 className="mt-1 text-xl font-black">Personas PR</h2></div><CommunitySocial/></section>
<section className="rounded-[28px] border border-white/[.07] bg-gradient-to-br from-white/[.035] to-transparent p-5"><p className="text-[8px] font-black tracking-[.2em] text-white/25">PR VOICE</p><h2 className="mt-2 text-xl font-black">Tu voz también construye PR.</h2><p className="mt-2 text-[10px] leading-5 text-white/32">Sugerencias, ideas y devoluciones con un espacio claro y confidencial cuando corresponda.</p><span className="mt-4 inline-flex rounded-full border border-white/10 px-4 py-2 text-[8px] font-black tracking-wider text-white/35">PRÓXIMAMENTE →</span></section>
</main></AppLayout>}
