import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import AppLayout from '../layouts/AppLayout'
import { useAuth } from '../lib/auth'
import { supabase } from '../lib/supabase'
import { calculatePRProgression, PR_PROGRESSION_IS_BETA } from '../lib/prProgression'
function fmt(n){return Number(n||0).toLocaleString('es-UY',{maximumFractionDigits:1})}
export default function EvolutionNext(){
 const{user}=useAuth();const[id]=useState(()=>user?.id);const[data,setData]=useState({loading:true,acts:[],badges:[],goals:[],takes:[],events:[]})
 useEffect(()=>{let alive=true;(async()=>{if(!id)return;const[a,b,g,t,e]=await Promise.all([
  supabase.from('pr_inline_skate_activities').select('id,distancia_metros,fecha_inicio,tiempo_movimiento_segundos').eq('alumno_id',id).eq('fuente','strava').eq('eliminada',false).order('fecha_inicio',{ascending:false}).limit(2000),
  supabase.from('actividad_pr').select('id,tipo,titulo,fecha').eq('alumno_id',id).or('eliminado.is.null,eliminado.eq.false').order('fecha',{ascending:false}).limit(500),
  supabase.from('pr_performance_objetivos').select('*').eq('alumno_id',id).eq('eliminado',false).order('creado_en',{ascending:false}),
  supabase.from('pr_performance_tomas_calculadas').select('id,numero_toma,distancia_km,tiempo_segundos,fecha').eq('alumno_id',id).order('numero_toma',{ascending:false}).limit(100),
  supabase.from('actividad_pr').select('id,tipo,titulo,fecha').eq('alumno_id',id).eq('tipo','Evento').or('eliminado.is.null,eliminado.eq.false').order('fecha',{ascending:false}).limit(100)
 ]);if(!alive)return;setData({loading:false,acts:a.data||[],badges:(b.data||[]).filter(x=>x.tipo==='Insignia'),goals:g.data||[],takes:t.data||[],events:e.data||[]})})().catch(()=>alive&&setData(x=>({...x,loading:false})));return()=>{alive=false}},[id])
 const x=useMemo(()=>{const km=data.acts.reduce((n,a)=>n+(Number(a.distancia_metros)||0)/1000,0),sessions=data.acts.length,completed=data.goals.filter(g=>String(g.estado).toLowerCase()==='completado').length,milestones=data.badges.length;return{km,sessions,completed,milestones,...calculatePRProgression({km,sessions,completedGoals:completed,milestones,takes:data.takes.length})}},[data])
 const name=(user?.nombre||'Patinador').split(' ')[0]
 return <AppLayout title="Evolución"><main className="mx-auto w-full max-w-[800px] space-y-4 px-4 pb-32 pt-4 text-white">
  <section className="relative overflow-hidden rounded-[36px] border border-violet-300/15 bg-[#09080d] p-6 shadow-[0_28px_100px_rgba(0,0,0,.5)]"><div className="absolute -right-24 -top-24 h-80 w-80 rounded-full bg-violet-600/20 blur-3xl"/><div className="absolute -bottom-24 left-8 h-56 w-56 rounded-full bg-cyan-400/10 blur-3xl"/><div className="relative"><div className="flex items-center justify-between"><p className="text-[8px] font-black tracking-[.25em] text-violet-200/70">EVOLUCIÓN 2.0</p><span className="rounded-full border border-white/10 bg-white/[.04] px-3 py-1 text-[7px] font-black text-white/35">{PR_PROGRESSION_IS_BETA?'MODELO BETA · PERSONAL':'PERSONAL · NO COMPETITIVO'}</span></div><h1 className="mt-7 text-[36px] font-black leading-[.95] tracking-[-.05em]">Tu progreso no es un ranking.<br/><span className="text-white/45">Es una historia.</span></h1><p className="mt-4 max-w-[520px] text-[11px] leading-5 text-white/36">{name}, acá juntamos lo que ya existe de vos en PR: entrenamientos, kilómetros, objetivos, tomas e hitos. Sin inventar datos.</p></div></section>
  <section className="overflow-hidden rounded-[30px] border border-cyan-300/15 bg-gradient-to-br from-cyan-300/[.07] via-white/[.02] to-violet-400/[.05] p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[8px] font-black tracking-[.2em] text-cyan-200/65">NIVEL {x.level.n} · PR LEVELS</p><h2 className="mt-2 text-[26px] font-black tracking-[-.035em]">{data.loading?'Leyendo tu historia…':x.level.name}</h2><p className="mt-2 text-[9px] leading-4 text-white/30">Los niveles representan tu recorrido personal. No ordenan alumnos ni crean competencia entre compañeros.</p></div><div className="grid h-16 w-16 shrink-0 place-items-center rounded-[22px] border border-cyan-200/20 bg-black/25 text-2xl font-black text-cyan-100">{data.loading?'—':x.level.n}</div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-gradient-to-r from-violet-400 to-cyan-300 transition-all duration-700" style={{width:(data.loading?0:x.progress)+'%'}}/></div><div className="mt-2 flex justify-between text-[7px] font-black tracking-wider text-white/22"><span>{data.loading?'—':x.score+' PR'}</span><span>{x.next?'SIGUIENTE · '+x.next.name.toUpperCase():'NIVEL MÁXIMO ACTUAL'}</span></div></section>
  <section className="grid grid-cols-4 gap-2"><Metric v={data.loading?'—':x.sessions} l="ENTRENOS"/><Metric v={data.loading?'—':fmt(x.km)} l="KM"/><Metric v={data.loading?'—':x.completed} l="OBJETIVOS"/><Metric v={data.loading?'—':x.milestones} l="HITOS"/></section>
  <section className="rounded-[30px] border border-white/[.07] bg-[#101015] p-5"><div className="flex items-end justify-between"><div><p className="text-[8px] font-black tracking-[.2em] text-white/25">PR PASSPORT</p><h2 className="mt-1 text-xl font-black">Tu pasaporte dentro de PR.</h2></div><span className="text-xl text-violet-200/55">⌁</span></div><p className="mt-2 text-[10px] leading-5 text-white/32">No es una colección artificial de medallas. Es el registro de capítulos que realmente viviste.</p><div className="mt-4 grid grid-cols-2 gap-2"><Passport title="Entrenamiento" value={x.sessions?x.sessions+' registros':'Sin registros aún'} active={x.sessions>0}/><Passport title="Objetivos" value={x.completed?x.completed+' completados':'En construcción'} active={x.completed>0}/><Passport title="Hitos" value={x.milestones?x.milestones+' guardados':'Tu historia recién empieza'} active={x.milestones>0}/><Passport title="Eventos" value={data.events.length?data.events.length+' vividos':'Sin eventos registrados'} active={data.events.length>0}/></div></section>
  <section className="rounded-[30px] border border-amber-200/12 bg-amber-200/[.035] p-5"><p className="text-[8px] font-black tracking-[.2em] text-amber-100/50">MI HISTORIA · SEASONS</p><h2 className="mt-2 text-xl font-black">Cada etapa queda. Ninguna desaparece.</h2><div className="mt-4 grid gap-2"><Season tag="2026 · CAPÍTULO" title="Shifter Marathon" text="Entrenamiento, tareas y preparación del primer gran capítulo." to="/app/historia/shifter-2026"/><Season tag="2026 · AHORA" title="Nueva etapa" text="Tu vida cotidiana dentro de Punta Rollers empieza a convertirse en historia." to="/app/mi-pr"/><Season tag="DICIEMBRE · PRÓXIMAMENTE" title="Temporada de cierre" text="Awards, Wrapped y cierre anual, siempre con datos reales."/></div></section>
  <section className="grid grid-cols-2 gap-2"><Link to="/app/tareas" className="rounded-[24px] border border-violet-300/12 bg-violet-300/[.04] p-4"><p className="text-[8px] font-black text-violet-200/60">AHORA</p><h3 className="mt-2 text-sm font-black">Tareas + objetivos</h3><p className="mt-2 text-[9px] leading-4 text-white/28">Lo que estás construyendo hoy.</p></Link><Link to="/app/mi-pr" className="rounded-[24px] border border-cyan-300/12 bg-cyan-300/[.04] p-4"><p className="text-[8px] font-black text-cyan-200/60">IDENTIDAD</p><h3 className="mt-2 text-sm font-black">Volver a Mi PR</h3><p className="mt-2 text-[9px] leading-4 text-white/28">Tu identidad, asistencia e historia.</p></Link></section>
 </main></AppLayout>
}
function Metric({v,l}){return <div className="rounded-[20px] border border-white/[.07] bg-black/20 p-3 text-center"><p className="text-lg font-black">{v}</p><p className="mt-1 text-[6px] font-black tracking-[.1em] text-white/22">{l}</p></div>}
function Passport({title,value,active}){return <div className={'rounded-[20px] border p-4 '+(active?'border-violet-300/15 bg-violet-300/[.045]':'border-white/[.06] bg-black/15')}><div className={'mb-3 h-2 w-2 rounded-full '+(active?'bg-cyan-300 shadow-[0_0_14px_rgba(103,232,249,.7)]':'bg-white/15')}/><p className="text-[10px] font-black">{title}</p><p className="mt-1 text-[8px] leading-4 text-white/27">{value}</p></div>}
function Season({tag,title,text,to}){const body=<div className="rounded-[20px] border border-white/[.06] bg-black/15 p-4"><p className="text-[7px] font-black tracking-[.15em] text-amber-100/35">{tag}</p><div className="mt-1 flex items-center justify-between"><h3 className="text-sm font-black">{title}</h3>{to&&<span className="text-amber-100/45">→</span>}</div><p className="mt-2 text-[9px] leading-4 text-white/28">{text}</p></div>;return to?<Link to={to}>{body}</Link>:body}
