import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import AppLayout from '../layouts/AppLayout'
import { useAuth } from '../lib/auth'
import { supabase } from '../lib/supabase'
const EVENT='shifter-marathon-2026'
export default function HistoryNext(){const{user}=useAuth();const[s,setS]=useState({loading:true,shifter:false,acts:[],events:[],badges:[]})
 useEffect(()=>{let alive=true;(async()=>{if(!user?.id)return;const[e,a,v,b]=await Promise.all([supabase.from('pr_training_enrollments').select('category').eq('profile_id',user.id).eq('event_slug',EVENT).maybeSingle(),supabase.from('pr_inline_skate_activities').select('id,distancia_metros,fecha_inicio').eq('alumno_id',user.id).eq('fuente','strava').eq('eliminada',false).order('fecha_inicio',{ascending:false}).limit(2000),supabase.from('actividad_pr').select('id,tipo,titulo,fecha').eq('alumno_id',user.id).eq('tipo','Evento').or('eliminado.is.null,eliminado.eq.false').order('fecha',{ascending:false}).limit(100),supabase.from('actividad_pr').select('id,tipo,titulo,fecha').eq('alumno_id',user.id).eq('tipo','Insignia').or('eliminado.is.null,eliminado.eq.false').order('fecha',{ascending:false}).limit(100)]);if(alive)setS({loading:false,shifter:Boolean(e.data?.category&&e.data.category!=='NO'),acts:a.data||[],events:v.data||[],badges:b.data||[]})})().catch(()=>alive&&setS(x=>({...x,loading:false})));return()=>{alive=false}},[user?.id])
 const total=useMemo(()=>s.acts.reduce((n,x)=>n+(Number(x.distancia_metros)||0)/1000,0),[s.acts]);const yearActs=s.acts.filter(x=>String(x.fecha_inicio||'').startsWith('2026'));const yearKm=yearActs.reduce((n,x)=>n+(Number(x.distancia_metros)||0)/1000,0)
 return <AppLayout title="Mi Historia"><main className="mx-auto w-full max-w-[780px] space-y-4 px-4 pb-32 pt-4 text-white"><section className="relative overflow-hidden rounded-[38px] border border-white/[.08] bg-[#09090d] p-6"><div className="absolute -right-20 -top-24 h-72 w-72 rounded-full bg-violet-600/15 blur-3xl"/><div className="absolute -bottom-20 left-8 h-52 w-52 rounded-full bg-amber-300/[.07] blur-3xl"/><div className="relative"><p className="text-[8px] font-black tracking-[.25em] text-white/35">MI HISTORIA · PUNTA ROLLERS</p><h1 className="mt-4 text-[38px] font-black leading-[.94] tracking-[-.055em]">No empezás de cero.<br/><span className="text-white/38">Seguís escribiendo.</span></h1><p className="mt-4 max-w-[510px] text-[11px] leading-5 text-white/34">Acá viven las etapas que realmente atravesaste. Eventos, entrenamientos e hitos quedan como capítulos; la app cambia, tu historia no.</p></div></section><section className="grid grid-cols-3 gap-2"><Metric v={s.loading?'—':yearActs.length} l="ENTRENOS · 2026"/><Metric v={s.loading?'—':yearKm.toLocaleString('es-UY',{maximumFractionDigits:1})} l="KM · 2026"/><Metric v={s.loading?'—':s.badges.length} l="HITOS"/></section><section className="rounded-[30px] border border-white/[.07] bg-[#101015] p-5"><p className="text-[8px] font-black tracking-[.2em] text-white/25">SEASONS · 2026</p><h2 className="mt-2 text-xl font-black">Tus capítulos.</h2><div className="mt-4 space-y-2">{s.shifter?<Chapter to="/app/historia/shifter-2026" tag="CAPÍTULO 01 · SHIFTER" title="Road to Shifter 2026" text="Preparación, deberes y registros reales de tu camino hacia la carrera." accent="amber"/>:<Chapter tag="CAPÍTULO 01" title="Tu historia recién empieza" text="Shifter no aparece porque tu cuenta no figura como participante. No agregamos recuerdos que no te corresponden."/>}<Chapter to="/app/evolucion" tag="CAPÍTULO ACTUAL · NUEVA ETAPA" title="Tu vida dentro de PR" text="Entrenamientos, objetivos, asistencia, hitos y experiencias empiezan a construir este capítulo." accent="violet"/><Chapter to="/app/historia/wrapped-2026" tag="DICIEMBRE · CIERRE 2026" title="Wrapped + PR Awards" text="Tu cierre anual se prepara con información real. Antes de diciembre permanece bloqueado." accent="cyan"/></div></section><section className="rounded-[28px] border border-violet-300/12 bg-violet-300/[.035] p-5"><p className="text-[8px] font-black tracking-[.18em] text-violet-200/55">ARCHIVO PERSONAL</p><div className="mt-3 grid grid-cols-2 gap-2"><Metric v={s.loading?'—':s.acts.length} l="ENTRENOS TOTALES"/><Metric v={s.loading?'—':total.toLocaleString('es-UY',{maximumFractionDigits:1})+' km'} l="DISTANCIA REGISTRADA"/><Metric v={s.loading?'—':s.events.length} l="EVENTOS"/><Metric v={s.loading?'—':s.badges.length} l="INSIGNIAS"/></div></section></main></AppLayout>}
function Metric({v,l}){return <div className="rounded-[20px] border border-white/[.07] bg-black/20 p-4 text-center"><p className="text-lg font-black">{v}</p><p className="mt-1 text-[6px] font-black tracking-[.1em] text-white/22">{l}</p></div>}
function Chapter({to,tag,title,text,accent}){const cls=accent==='amber'?'border-amber-200/15 bg-amber-200/[.035]':accent==='violet'?'border-violet-300/15 bg-violet-300/[.04]':accent==='cyan'?'border-cyan-300/12 bg-cyan-300/[.03]':'border-white/[.06] bg-black/15';const body=<article className={'rounded-[22px] border p-4 '+cls}><div className="flex items-start justify-between gap-4"><div><p className="text-[7px] font-black tracking-[.16em] text-white/28">{tag}</p><h3 className="mt-2 text-sm font-black">{title}</h3><p className="mt-2 text-[9px] leading-4 text-white/28">{text}</p></div>{to&&<span className="mt-5 text-white/35">→</span>}</div></article>;return to?<Link to={to}>{body}</Link>:body}