import { useEffect, useMemo, useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import AppLayout from '../layouts/AppLayout'
import { useAuth } from '../lib/auth'
import { supabase } from '../lib/supabase'
import { MiEvolucionContent } from './MiEvolucion'

function savedUser(){try{return JSON.parse(localStorage.getItem('pr_user')||'{}')}catch{return{}}}
function km(meters){return(Number(meters)||0)/1000}
function duration(seconds){const total=Math.max(0,Math.round(Number(seconds)||0)),h=Math.floor(total/3600),m=Math.floor((total%3600)/60);return h?`${h}h ${m}m`:`${m} min`}
function dateLabel(value){if(!value)return'';return new Date(value).toLocaleDateString('es-UY',{day:'2-digit',month:'short'})}
function timeLabel(value){if(!value)return'';return new Date(value).toLocaleTimeString('es-UY',{hour:'2-digit',minute:'2-digit'})}
function pctChange(current,previous){if(previous<=0)return current>0?100:0;return((current-previous)/previous)*100}
function mondayKey(value){const d=new Date(value),utc=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())),day=utc.getUTCDay()||7;utc.setUTCDate(utc.getUTCDate()-day+1);return utc.toISOString().slice(0,10)}
function weeklyStreak(rows){const weeks=[...new Set(rows.filter(r=>r.fecha_inicio).map(r=>mondayKey(r.fecha_inicio)))].sort().reverse();if(!weeks.length)return 0;let streak=1,cursor=new Date(`${weeks[0]}T00:00:00Z`);for(let i=1;i<weeks.length;i++){const expected=new Date(cursor);expected.setUTCDate(expected.getUTCDate()-7);if(weeks[i]!==expected.toISOString().slice(0,10))break;streak++;cursor=expected}return streak}

export default function MyActivity(){
 const location=useLocation(),{user}=useAuth(),base={...savedUser(),...user},profileId=base.id
 const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[historyOpen,setHistoryOpen]=useState(false)
 useEffect(()=>{if(location.hash!=='#evolucion-deportiva')return;const t=setTimeout(()=>document.getElementById('evolucion-deportiva')?.scrollIntoView({behavior:'smooth',block:'start'}),250);return()=>clearTimeout(t)},[location.hash])
 useEffect(()=>{let alive=true;async function load(){const activity=await supabase.from('pr_inline_skate_activities').select('*').eq('alumno_id',profileId).eq('eliminada',false).order('fecha_inicio',{ascending:false}).limit(250);if(!alive)return;if(!activity.error)setRows(activity.data||[]);setLoading(false)}if(profileId)load();return()=>{alive=false}},[profileId])
 const stats=useMemo(()=>{const stravaRows=rows.filter(r=>r.fuente==='strava'),totalKm=rows.reduce((s,r)=>s+km(r.distancia_metros),0),totalSeconds=rows.reduce((s,r)=>s+(Number(r.tiempo_movimiento_segundos)||0),0),now=Date.now(),day=86400000,recent=(from,to=0)=>stravaRows.filter(r=>{const age=now-new Date(r.fecha_inicio).getTime();return age>=to*day&&age<from*day}),this7=recent(7),prev7=recent(14,7),last30=recent(30),prev30=recent(60,30),weekKm=this7.reduce((s,r)=>s+km(r.distancia_metros),0),prevWeekKm=prev7.reduce((s,r)=>s+km(r.distancia_metros),0),monthKm=last30.reduce((s,r)=>s+km(r.distancia_metros),0),prevMonthKm=prev30.reduce((s,r)=>s+km(r.distancia_metros),0),longest=stravaRows.reduce((b,r)=>!b||km(r.distancia_metros)>km(b.distancia_metros)?r:b,null),fastest=stravaRows.reduce((b,r)=>Number(r.velocidad_promedio_kmh)>Number(b?.velocidad_promedio_kmh||0)?r:b,null),streak=weeklyStreak(stravaRows),weekDelta=pctChange(weekKm,prevWeekKm),monthDelta=pctChange(monthKm,prevMonthKm),insights=[];if(this7.length&&prev7.length){if(weekDelta>=8)insights.push({icon:'↗',title:'Tu volumen está subiendo',text:`Esta semana llevás ${weekKm.toFixed(1)} km, ${Math.round(weekDelta)}% más que la anterior.`});else if(weekDelta<=-8)insights.push({icon:'↘',title:'Semana más liviana',text:`Llevás ${weekKm.toFixed(1)} km, ${Math.abs(Math.round(weekDelta))}% menos que la semana anterior.`});else insights.push({icon:'≈',title:'Ritmo estable',text:'Tu volumen semanal se mantiene muy parecido al de la semana anterior.'})}else if(this7.length)insights.push({icon:'⚡',title:'Semana en movimiento',text:`Ya sumaste ${weekKm.toFixed(1)} km en ${this7.length} entrenamiento${this7.length===1?'':'s'}.`});if(streak>=2)insights.push({icon:'🔥',title:`${streak} semanas seguidas entrenando`,text:'Tu constancia ya está formando una racha.'});if(longest)insights.push({icon:'🏁',title:'Tu sesión más larga',text:`${km(longest.distancia_metros).toFixed(1)} km · ${dateLabel(longest.fecha_inicio)}.`});if(fastest&&Number(fastest.velocidad_promedio_kmh)>0)insights.push({icon:'⚡',title:'Mejor promedio registrado',text:`${Number(fastest.velocidad_promedio_kmh).toFixed(1)} km/h en ${dateLabel(fastest.fecha_inicio)}.`});return{totalKm,totalSeconds,this7,last30,weekKm,monthKm,prevWeekKm,prevMonthKm,weekDelta,monthDelta,streak,longest,fastest,insights:insights.slice(0,4)}},[rows])
 return <AppLayout title="Rendimiento"><div className="pr-page space-y-4 animate-page-enter pb-9">
  <section className="relative overflow-hidden rounded-[34px] border border-violet-300/15 bg-gradient-to-br from-[#190d2b] via-[#0c0c12] to-[#07070a] p-5"><div className="absolute -right-20 -top-20 h-60 w-60 rounded-full bg-violet-500/15 blur-3xl"/><div className="relative"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-violet-300 shadow-[0_0_12px_rgba(196,181,253,.8)]"/><p className="text-[9px] font-black uppercase tracking-[.2em] text-violet-300">RENDIMIENTO PR</p></div><h1 className="mt-3 font-display text-[39px] leading-[.92] text-white">Todo lo que<br/><span className="text-violet-300">venís creciendo.</span></h1><p className="mt-3 max-w-[310px] text-xs leading-5 text-white/40">Actividad, evolución, objetivos, marcas y preparación deportiva reunidos en un solo lugar.</p><div className="mt-5 grid grid-cols-3 divide-x divide-white/[.07] rounded-[24px] border border-white/[.07] bg-black/25"><Metric value={rows.length} label="Entrenos"/><Metric value={stats.totalKm.toLocaleString('es-UY',{maximumFractionDigits:1})} label="Km" accent/><Metric value={stats.streak||'—'} label="Racha sem."/></div></div></section>
  <section className="grid grid-cols-2 gap-2"><Jump href="#evolucion-deportiva" label="Mi evolución" sub="Marcas + objetivos"/><Jump href="#historial-actividad" label="Actividad" sub="Strava + PR"/><Link to="/app/deberes" className="rounded-[22px] border border-violet-300/12 bg-violet-400/[.06] p-4 active:scale-[.98]"><p className="text-[8px] font-black uppercase tracking-[.14em] text-violet-300">PLAN</p><p className="mt-2 text-sm font-black text-white">Shifter + deberes</p><p className="mt-1 text-[9px] text-white/30">Tu preparación activa →</p></Link><Jump href="#pulse" label="PR Pulse" sub="Lectura de tu ritmo"/></section>
  <section className="rounded-[29px] border border-white/[.08] bg-[#0d0d12] p-4"><div className="flex items-end justify-between gap-3"><div><p className="text-[8px] font-black uppercase tracking-[.16em] text-violet-300">ÚLTIMOS 30 DÍAS</p><h2 className="mt-1 font-display text-[27px] text-white">Ritmo reciente</h2></div><span className="rounded-full border border-violet-300/15 bg-violet-400/[.07] px-3 py-1 text-[9px] font-black text-violet-200">{stats.last30.length} sesiones</span></div><div className="mt-4 grid grid-cols-2 gap-2"><StatCard title="Esta semana" value={`${stats.weekKm.toFixed(1)} km`} detail={`${stats.this7.length} entrenos${stats.prevWeekKm>0?` · ${stats.weekDelta>=0?'+':''}${Math.round(stats.weekDelta)}%`:''}`}/><StatCard title="Este mes" value={`${stats.monthKm.toFixed(1)} km`} detail={`${stats.last30.length} entrenos${stats.prevMonthKm>0?` · ${stats.monthDelta>=0?'+':''}${Math.round(stats.monthDelta)}%`:''}`}/></div><div className="mt-4 rounded-[22px] border border-white/[.06] bg-black/20 p-4"><p className="text-[8px] uppercase tracking-[.13em] text-white/25">FUENTE DE DATOS</p><p className="mt-2 text-sm font-bold text-white">Strava + registros PR</p><p className="mt-1 text-[10px] leading-5 text-white/34">Tus sesiones sincronizadas y tus registros oficiales alimentan este centro sin duplicar información.</p></div></section>
  {stats.insights.length>0&&<section id="pulse" className="scroll-mt-24 rounded-[30px] border border-emerald-300/15 bg-gradient-to-br from-emerald-400/[.07] via-white/[.02] to-cyan-400/[.04] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[8px] font-black uppercase tracking-[.18em] text-emerald-300">PR PULSE · LIVE</p><h2 className="mt-1 font-display text-[29px] leading-none text-white">Tu semana te está diciendo algo.</h2></div><span className="rounded-full border border-emerald-300/15 bg-emerald-400/[.07] px-3 py-1 text-[9px] font-black text-emerald-200">LIVE</span></div><div className="mt-4 grid gap-2">{stats.insights.map(item=><article key={item.title} className="rounded-[22px] border border-white/[.07] bg-black/20 p-4"><div className="flex gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl border border-emerald-300/12 bg-emerald-400/[.07] text-lg">{item.icon}</div><div><p className="text-sm font-black text-white">{item.title}</p><p className="mt-1 text-[10px] leading-5 text-white/38">{item.text}</p></div></div></article>)}</div></section>}
  <section id="evolucion-deportiva" className="scroll-mt-24 rounded-[30px] border border-orange-300/15 bg-gradient-to-br from-orange-400/[.07] via-white/[.025] to-violet-400/[.05] p-4"><p className="text-[8px] font-black uppercase tracking-[.18em] text-orange-300">TU CENTRO DE EVOLUCIÓN</p><h2 className="mt-1 font-display text-[29px] leading-none text-white">Performance y objetivos.</h2><p className="mt-2 text-[10px] leading-5 text-white/36">Acá viven tus tomas, metas, devoluciones y progresión histórica.</p></section>
  <MiEvolucionContent embedded/>
  <section id="historial-actividad" className="scroll-mt-24"><div className="mb-3 flex items-end justify-between gap-3"><div><p className="text-[8px] font-black uppercase tracking-[.16em] text-white/25">HISTORIAL</p><h2 className="mt-1 font-display text-[27px] text-white">Últimas sesiones</h2></div><span className="text-[9px] font-black text-violet-300">Strava + PR</span></div><div className="space-y-2">{loading?[0,1,2].map(i=><div key={i} className="h-24 animate-pulse rounded-[22px] bg-white/[.04]"/>):rows.length?(historyOpen?rows:rows.slice(0,3)).map(row=><article key={row.id} className="rounded-[22px] border border-white/[.07] bg-white/[.025] p-4"><div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-[16px] border border-violet-300/12 bg-violet-400/[.07] text-violet-300"><ActivityIcon/></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-black text-white">{row.nombre||row.tipo||'Entrenamiento'}</p><p className="mt-1 text-[9px] text-white/27">{dateLabel(row.fecha_inicio)} · {timeLabel(row.fecha_inicio)} · {row.fuente==='strava'?'Strava':'PR'}</p></div><p className="shrink-0 font-display text-[20px] text-violet-300">{km(row.distancia_metros).toFixed(1)} km</p></div><div className="mt-3 flex gap-4 border-t border-white/[.05] pt-2 text-[9px] text-white/34"><span>{duration(row.tiempo_movimiento_segundos)}</span>{Number(row.velocidad_promedio_kmh)>0&&<span>{Number(row.velocidad_promedio_kmh).toFixed(1)} km/h prom.</span>}</div></div></div></article>):<div className="rounded-[25px] border border-white/[.08] bg-white/[.025] p-6 text-center"><p className="font-bold text-white">Tu historial empieza con tu próxima vuelta.</p><Link to="/app/perfil" className="mt-4 inline-flex min-h-11 items-center rounded-2xl border border-violet-300/15 bg-violet-400/[.08] px-4 text-[10px] font-black text-violet-200">Revisar conexión Strava →</Link></div>}{!loading&&rows.length>3&&<button type="button" onClick={()=>setHistoryOpen(v=>!v)} className="min-h-12 w-full rounded-[20px] border border-violet-300/15 bg-violet-400/[.07] px-4 text-[10px] font-black text-violet-200">{historyOpen?'Mostrar solamente las últimas 3 ↑':`Ver ${rows.length-3} sesiones más ↓`}</button>}</div></section>
 </div></AppLayout>
}
function Metric({value,label,accent=false}){return <div className="min-w-0 px-2 py-4 text-center"><p className={`truncate font-display text-[24px] leading-none ${accent?'text-violet-300':'text-white'}`}>{value}</p><p className="mt-2 text-[7px] font-black uppercase tracking-[.12em] text-white/25">{label}</p></div>}
function StatCard({title,value,detail}){return <div className="rounded-[21px] border border-white/[.06] bg-white/[.025] p-4"><p className="text-[8px] font-black uppercase tracking-[.12em] text-white/25">{title}</p><p className="mt-2 font-display text-[27px] text-white">{value}</p><p className="mt-1 text-[9px] text-white/28">{detail}</p></div>}
function Jump({href,label,sub}){return <a href={href} className="rounded-[22px] border border-white/[.07] bg-white/[.025] p-4 active:scale-[.98]"><p className="text-[8px] font-black uppercase tracking-[.14em] text-violet-300">ACCESO</p><p className="mt-2 text-sm font-black text-white">{label}</p><p className="mt-1 text-[9px] text-white/30">{sub} ↓</p></a>}
function ActivityIcon(){return <svg viewBox="0 0 24 24" className="h-6 w-6" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M4 18V8"/><path d="M9 18v-5"/><path d="M14 18V5"/><path d="M19 18v-8"/><path d="m4 8 5 5 5-8 5 5"/></svg>}
