import { Link } from 'react-router-dom'
import AppLayout from '../layouts/AppLayout'
import { useAuth } from '../lib/auth'

const tools=[
 ['PR Card','Beneficios y membresía','/app/prcard','CARD'],
 ['RollerMap','Lugares para rodar','/app/rollermap','MAP'],
 ['PR Tracking','Tus equipos y Track ID','/app/tracking','NFC'],
 ['PR Music','Tu música para rodar','/app/musica','♪'],
]
export default function MyPRNext(){const{user}=useAuth();const name=[user?.nombre,user?.apellido].filter(Boolean).join(' ')||'Alumno Punta Rollers';const photo=user?.foto||user?.foto_url||'';return <AppLayout title="Mi PR"><main className="mx-auto w-full max-w-[760px] space-y-4 px-4 pb-32 pt-4 text-white">
<section className="relative overflow-hidden rounded-[36px] border border-violet-300/15 bg-[#0a0910] px-5 pb-6 pt-5"><div className="absolute -right-16 -top-20 h-60 w-60 rounded-full bg-violet-600/20 blur-3xl"/><div className="absolute -bottom-20 -left-12 h-48 w-48 rounded-full bg-cyan-400/10 blur-3xl"/><div className="relative"><div className="flex items-center justify-between"><p className="text-[8px] font-black tracking-[.24em] text-violet-300">MI IDENTIDAD PR</p><span className="rounded-full border border-emerald-300/20 bg-emerald-300/[.07] px-3 py-1 text-[8px] font-black tracking-wider text-emerald-200">ACTIVO</span></div><div className="mt-7 flex flex-col items-center text-center"><div className="relative"><div className="h-[104px] w-[104px] overflow-hidden rounded-full border border-violet-300/30 bg-gradient-to-br from-violet-400/20 to-white/[.03] p-1 shadow-[0_0_45px_rgba(139,92,246,.18)]">{photo?<img src={photo} alt="" className="h-full w-full rounded-full object-cover"/>:<div className="grid h-full w-full place-items-center rounded-full bg-black/35 text-3xl font-black text-white/45">{name.slice(0,1)}</div>}</div><span className="absolute -bottom-1 left-1/2 -translate-x-1/2 rounded-full border border-violet-200/20 bg-[#16101f] px-3 py-1 text-[7px] font-black tracking-[.16em] text-violet-200">PR MEMBER</span></div><h1 className="mt-5 text-[28px] font-black tracking-[-.035em]">{name}</h1><p className="mt-1 text-[10px] uppercase tracking-[.18em] text-white/28">Punta Rollers · 2026</p></div><div className="mt-6 grid grid-cols-3 gap-2"><Mini v="—" l="NIVEL"/><Mini v="—" l="ASISTENCIAS"/><Mini v="—" l="KM PR"/></div></div></section>
<Link to="/app/tracking" className="block overflow-hidden rounded-[28px] border border-cyan-300/15 bg-gradient-to-br from-cyan-300/[.09] via-white/[.02] to-transparent p-5"><div className="flex items-center justify-between gap-5"><div><p className="text-[8px] font-black tracking-[.2em] text-cyan-200/70">PR ID · ASISTENCIA</p><h2 className="mt-2 text-xl font-black">Tu acceso a Punta Rollers.</h2><p className="mt-2 text-[10px] leading-5 text-white/36">Tu identidad PR será la base para registrar asistencia, eventos y experiencias.</p></div><div className="grid h-[74px] w-[74px] shrink-0 place-items-center rounded-[22px] border border-cyan-200/20 bg-black/25"><div className="grid grid-cols-3 gap-[3px] opacity-75">{Array.from({length:25}).map((_,i)=><i key={i} className={`h-[5px] w-[5px] ${[0,1,2,5,7,10,11,12,14,17,20,22,23,24,6,18].includes(i)?'bg-cyan-100':'bg-white/10'}`}/>)}</div></div></div><div className="mt-4 flex items-center justify-between border-t border-white/[.06] pt-4"><span className="text-[8px] font-bold uppercase tracking-wider text-white/25">QR ID · Próximamente PR Check</span><span className="text-cyan-200">→</span></div></Link>
<section className="rounded-[28px] border border-amber-300/15 bg-amber-300/[.045] p-5"><p className="text-[8px] font-black tracking-[.2em] text-amber-200/65">MI HISTORIA</p><div className="mt-2 flex items-end justify-between gap-4"><div><h2 className="text-xl font-black">Shifter 2026</h2><p className="mt-2 text-[10px] leading-5 text-white/35">Tu primer capítulo de entrenamiento queda guardado para siempre.</p></div><Link to="/app/deberes" className="shrink-0 rounded-full border border-amber-200/15 px-4 py-2 text-[8px] font-black text-amber-100">ABRIR →</Link></div></section>
<section><div className="mb-3"><p className="text-[8px] font-black tracking-[.2em] text-white/25">ECOSISTEMA</p><h2 className="mt-1 text-xl font-black">Todo lo tuyo, en un lugar.</h2></div><div className="grid grid-cols-2 gap-2">{tools.map(([a,b,to,mark])=><Link key={a} to={to} className="relative min-h-[145px] overflow-hidden rounded-[25px] border border-white/[.07] bg-[#101015] p-4 active:scale-[.98]"><span className="absolute right-3 top-2 text-[30px] font-black text-violet-300/[.08]">{mark}</span><p className="relative text-sm font-black">{a}</p><p className="relative mt-2 max-w-[120px] text-[9px] leading-4 text-white/30">{b}</p><span className="absolute bottom-4 left-4 text-violet-300/65">→</span></Link>)}</div></section>
<section className="grid grid-cols-2 gap-2"><Link to="/app/tareas" className="rounded-[24px] border border-violet-300/15 bg-violet-400/[.055] p-4"><p className="text-[8px] font-black tracking-wider text-violet-200/65">PROGRESO</p><h3 className="mt-2 font-black">Tareas y objetivos</h3><p className="mt-2 text-[9px] leading-4 text-white/30">Lo que estás construyendo ahora.</p></Link><Link to="/app/insignias" className="rounded-[24px] border border-white/[.07] bg-white/[.025] p-4"><p className="text-[8px] font-black tracking-wider text-white/30">HITOS</p><h3 className="mt-2 font-black">Insignias</h3><p className="mt-2 text-[9px] leading-4 text-white/30">Momentos que forman tu historia.</p></Link></section>
</main></AppLayout>}
function Mini({v,l}){return <div className="rounded-[18px] border border-white/[.07] bg-black/20 p-3 text-center"><p className="text-lg font-black">{v}</p><p className="mt-1 text-[7px] font-black tracking-[.12em] text-white/25">{l}</p></div>}
