import { Link } from 'react-router-dom'
import AppLayout from '../layouts/AppLayout'
import { PR_SEASON_ASSETS } from '../lib/prSeason'
import AwardsParticipationBeta from '../components/awards/AwardsParticipationBeta'

const previewCategories=[
 ['Asistencia de Acero','Constancia que se sostuvo durante todo el año.'],
 ['Mejor Compañero/a','Esa persona que hace mejor al grupo.'],
 ['La Radio PR','Porque una clase en silencio tampoco sería Punta Rollers.'],
 ['Premio Piso Conocido','Caerse, levantarse y seguir rodando también cuenta.'],
 ['Superación 2026','El progreso que merece ser reconocido.'],
 ['Espíritu Punta Rollers','La esencia de lo que significa pertenecer.'],
]
export default function PRAwards(){return <AppLayout title="PR Awards"><main className="mx-auto w-full max-w-[760px] space-y-5 px-4 pb-32 pt-4 text-white">
<section className="relative overflow-hidden rounded-[38px] border border-amber-200/20 bg-[#09090b] px-5 pb-7 pt-5 shadow-[0_26px_90px_rgba(0,0,0,.48)]"><div className="absolute -right-16 -top-20 h-72 w-72 rounded-full bg-amber-300/[.12] blur-3xl"/><div className="absolute -bottom-20 -left-10 h-56 w-56 rounded-full bg-violet-500/[.09] blur-3xl"/><div className="relative"><div className="flex items-center justify-between"><p className="text-[8px] font-black tracking-[.26em] text-amber-200/70">PUNTA ROLLERS · 2026</p><span className="rounded-full border border-amber-200/15 bg-amber-200/[.06] px-3 py-1 text-[8px] font-black tracking-wider text-amber-100/60">PR AWARDS</span></div><div className="mx-auto mt-5 flex min-h-[155px] max-w-[280px] items-center justify-center"><img src={PR_SEASON_ASSETS.awardsLogo} alt="PR Awards 2026" className="max-h-[180px] max-w-full object-contain drop-shadow-[0_16px_34px_rgba(251,191,36,.16)]" onError={e=>{e.currentTarget.style.display='none'}}/></div><div className="mt-2 text-center"><h1 className="text-[31px] font-black leading-[.98] tracking-[-.045em]">Un año sobre ruedas<br/><span className="text-amber-100/55">merece su cierre.</span></h1><p className="mx-auto mt-4 max-w-[440px] text-[11px] leading-5 text-white/38">Personas, momentos y progresos que hicieron especial este 2026. Elegidos por la comunidad Punta Rollers.</p><div className="mt-5 inline-flex rounded-full border border-amber-200/20 bg-amber-300/[.07] px-4 py-2 text-[8px] font-black uppercase tracking-[.18em] text-amber-100">Votación · 1 DIC</div></div></div></section>
<section><div className="flex items-end justify-between px-1"><div><p className="text-[8px] font-black tracking-[.2em] text-amber-200/50">PRIMER ADELANTO</p><h2 className="mt-1 text-xl font-black">Seis categorías reveladas.</h2></div><p className="text-right text-[8px] leading-4 text-white/22">El resto<br/>sigue en secreto</p></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{previewCategories.map(([title,text],i)=><article key={title} className="group relative overflow-hidden rounded-[24px] border border-white/[.07] bg-[#101014] p-4"><span className="absolute right-3 top-1 text-[38px] font-black text-amber-200/[.045]">{String(i+1).padStart(2,'0')}</span><div className="relative"><div className="grid h-8 w-8 place-items-center rounded-full border border-amber-200/15 bg-amber-200/[.055] text-[8px] font-black text-amber-100/65">{i+1}</div><h3 className="mt-4 text-[14px] font-black">{title}</h3><p className="mt-2 max-w-[250px] text-[9px] leading-4 text-white/30">{text}</p></div></article>)}</div></section>
<section className="rounded-[28px] border border-violet-300/12 bg-gradient-to-br from-violet-400/[.075] to-white/[.015] p-5"><p className="text-[8px] font-black tracking-[.2em] text-violet-200/55">LA COMUNIDAD TAMBIÉN ELIGE</p><h2 className="mt-2 text-xl font-black">¿Qué premio no puede faltar?</h2><p className="mt-2 text-[10px] leading-5 text-white/32">Antes de abrir la votación vas a poder proponer categorías. Los votos serán privados y los resultados se revelarán en el cierre.</p><div className="mt-5 flex items-center justify-between border-t border-white/[.06] pt-4"><span className="text-[8px] font-black tracking-wider text-white/22">SUGERENCIAS · PRÓXIMAMENTE</span><Link to="/app/comunidad" className="rounded-full border border-white/10 px-4 py-2 text-[8px] font-black text-white/55">COMUNIDAD →</Link></div></section>
<AwardsParticipationBeta/></main></AppLayout>}
