import PublicLayout from '../layouts/PublicLayout'

const passportImages=[
 '/pasaporte-kids/01-presentacion-pasaporte-pr-kids.jpg',
 '/pasaporte-kids/02-como-funciona-pasaporte-pr-kids.jpg',
 '/pasaporte-kids/03-experiencia-pasaporte-pr-kids.jpg',
]
const pasos=[['01','JUNTÁ','Cada clase, esfuerzo y desafío puede sumar sellos a tu Pasaporte PR Kids.'],['02','ELEGÍ','Explorá los premios disponibles y elegí qué querés desbloquear.'],['03','COMPROBÁ','Fotografiá la página completa del pasaporte para que podamos validar tus sellos.'],['04','CANJEÁ','Enviá la solicitud. Validamos el pasaporte y preparamos el premio para una próxima clase.']]
const premios=[{nivel:'MINI',nombre:'Primeros premios',texto:'Pequeñas recompensas para celebrar el camino.'},{nivel:'PLUS',nombre:'Premios especiales',texto:'Accesorios, sorpresas y recompensas PR Kids.'},{nivel:'LEGEND',nombre:'Grandes desbloqueos',texto:'Las recompensas más especiales de la temporada.'}]
function Stamp({delay=0}){return <span style={{animationDelay:`${delay}ms`}} className="prk-stamp grid h-12 w-12 place-items-center rounded-full border-2 border-dashed border-fuchsia-200/35 bg-fuchsia-300/[.08] text-[18px]">✦</span>}
export default function PRKidsSellos(){return <PublicLayout><main className="mx-auto max-w-[620px] px-4 py-5 pb-16 text-white">
<section className="relative overflow-hidden rounded-[38px] border border-fuchsia-200/20 bg-[radial-gradient(circle_at_85%_12%,rgba(244,114,182,.23),transparent_30%),radial-gradient(circle_at_10%_90%,rgba(34,211,238,.13),transparent_32%),linear-gradient(145deg,#160b1a,#0b0b12_55%,#071315)] p-5 shadow-[0_28px_90px_rgba(0,0,0,.42)]"><div className="prk-orbit absolute -right-10 -top-12 h-44 w-44 rounded-full border border-fuchsia-200/10"/><div className="relative"><p className="text-[9px] font-black uppercase tracking-[.23em] text-fuchsia-100/65">PASAPORTE PR KIDS · TEMPORADA 2026</p><p className="mt-4 text-[10px] font-black uppercase tracking-[.18em] text-cyan-200/55">PUNTA ROLLERS PRESENTA</p><h1 className="mt-2 font-display text-[44px] leading-[.86]">Club de<br/><span className="bg-gradient-to-r from-fuchsia-300 via-violet-200 to-cyan-200 bg-clip-text text-transparent">Sellos.</span></h1><p className="mt-5 max-w-[360px] text-[13px] leading-6 text-white/48">Tu pasaporte cuenta tu historia. Ahora, tus sellos también desbloquean recompensas.</p></div><div className="relative mt-6 flex gap-2"><Stamp/><Stamp delay={180}/><Stamp delay={360}/><div className="ml-auto grid h-12 place-items-center rounded-[18px] border border-white/10 bg-black/25 px-3 text-[8px] font-black tracking-[.12em] text-white/35">SELLÁ · SUMÁ<br/><span className="text-fuchsia-200/70">DESBLOQUEÁ</span></div></div></section>

<section className="mt-4 overflow-hidden rounded-[32px] border border-white/[.08] bg-[#0c0c12]"><div className="relative"><img src={passportImages[0]} alt="Pasaporte PR Kids oficial" className="block w-full"/><div className="absolute inset-x-0 bottom-0 h-24 bg-gradient-to-t from-[#0c0c12] to-transparent"/></div><div className="p-5 pt-2"><p className="text-[9px] font-black uppercase tracking-[.2em] text-fuchsia-200/55">EL PASAPORTE ES EL CORAZÓN</p><h2 className="mt-2 text-[24px] font-black">Lo que pasa en clase, sigue creciendo acá.</h2><p className="mt-2 text-[11px] leading-5 text-white/38">Participación, esfuerzo, desafíos y progreso se transforman en sellos. El Club de Sellos suma una nueva forma de celebrar ese recorrido, sin comparaciones entre niños.</p></div></section>

<section className="mt-4 rounded-[30px] border border-white/[.07] bg-white/[.025] p-5"><p className="text-[9px] font-black uppercase tracking-[.2em] text-fuchsia-200/60">ASÍ DE FÁCIL</p><h2 className="mt-2 text-[25px] font-black">Juntá → comprobá → canjeá.</h2><div className="mt-5 space-y-2">{pasos.map(([n,t,x])=><div key={n} className="flex gap-3 rounded-[22px] border border-white/[.06] bg-black/20 p-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-fuchsia-300/10 text-[10px] font-black text-fuchsia-200">{n}</div><div><p className="text-[10px] font-black tracking-[.08em]">{t}</p><p className="mt-1 text-[10px] leading-4 text-white/36">{x}</p></div></div>)}</div></section>

<section className="mt-4 grid grid-cols-2 gap-2"><div className="overflow-hidden rounded-[24px] border border-white/[.07] bg-black"><img src={passportImages[1]} alt="Cómo funciona el Pasaporte PR Kids" className="h-full w-full object-cover"/></div><div className="overflow-hidden rounded-[24px] border border-white/[.07] bg-black"><img src={passportImages[2]} alt="Experiencia Pasaporte PR Kids" className="h-full w-full object-cover"/></div></section>

<section className="mt-5"><div className="mb-3 flex items-end justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-cyan-200/55">PRIZE DROP</p><h2 className="mt-1 text-[24px] font-black">Premios para desbloquear</h2></div><span className="rounded-full border border-white/10 bg-white/[.035] px-3 py-1.5 text-[8px] font-black text-white/35">MUY PRONTO</span></div><div className="flex snap-x gap-3 overflow-x-auto pb-2">{premios.map((p,i)=><article key={p.nivel} className="min-w-[76%] snap-center overflow-hidden rounded-[28px] border border-white/[.07] bg-[#0d0d14]"><div className={`relative aspect-[16/10] ${i===0?'bg-[radial-gradient(circle,rgba(244,114,182,.18),transparent_42%),#120d15]':i===1?'bg-[radial-gradient(circle,rgba(167,139,250,.18),transparent_42%),#100e18]':'bg-[radial-gradient(circle,rgba(34,211,238,.16),transparent_42%),#091416]'}`}><div className="absolute inset-0 grid place-items-center"><div className="grid h-20 w-20 place-items-center rounded-[28px] border border-dashed border-white/15 text-3xl text-white/22">?</div></div><span className="absolute left-4 top-4 rounded-full border border-white/10 bg-black/35 px-3 py-1.5 text-[8px] font-black tracking-[.12em] text-white/55">{p.nivel}</span></div><div className="p-4"><p className="text-lg font-black">{p.nombre}</p><p className="mt-2 text-[10px] leading-4 text-white/35">{p.texto}</p><p className="mt-4 text-[8px] font-black text-white/22">FOTO · SELLOS · STOCK PENDIENTES</p></div></article>)}</div></section>

<section className="mt-4 overflow-hidden rounded-[30px] border border-cyan-200/15 bg-[linear-gradient(135deg,rgba(34,211,238,.08),rgba(244,114,182,.06))] p-5"><div className="flex gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-[20px] border border-cyan-200/15 bg-cyan-300/[.06] text-2xl">📷</div><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-cyan-100/60">COMPROBACIÓN DE SELLOS</p><h2 className="mt-1 text-xl font-black">Tu pasaporte es la prueba.</h2><p className="mt-2 text-[10px] leading-5 text-white/38">Al canjear podrás abrir la cámara del celular o elegir fotos de la galería. La página completa y todos los sellos utilizados deben verse claramente.</p></div></div><div className="mt-4 rounded-[20px] border border-white/[.07] bg-black/20 p-4"><p className="text-[9px] font-black text-white/60">IMPORTANTE PARA EL RETIRO</p><p className="mt-1 text-[9px] leading-4 text-white/30">Conservá el pasaporte físico. Punta Rollers validará y marcará presencialmente los sellos utilizados al entregar el premio.</p></div></section>

<section className="mt-4 rounded-[30px] border border-fuchsia-200/15 bg-fuchsia-300/[.045] p-5"><p className="text-[9px] font-black uppercase tracking-[.18em] text-fuchsia-200/60">PASAPORTE 2027</p><h2 className="mt-2 text-[22px] font-black">La historia continúa.</h2><p className="mt-2 text-[11px] leading-5 text-white/40">Cuando completes tu pasaporte actual, guardalo. Te entregaremos la nueva edición del Pasaporte PR Kids para continuar tu aventura en 2027.</p></section>
<section className="mt-4 rounded-[30px] border border-white/[.07] bg-black/20 p-5 text-center"><p className="text-[8px] font-black uppercase tracking-[.22em] text-white/25">SISTEMA OFICIAL DE RECOMPENSAS</p><p className="mt-2 font-display text-[26px]">PR Kids · Punta Rollers</p><p className="mt-2 text-[9px] text-white/25">Aprender · intentar · avanzar · celebrar.</p></section>
<style>{`.prk-stamp{animation:stampFloat 3s ease-in-out infinite}.prk-orbit{animation:orbitFloat 7s ease-in-out infinite}@keyframes stampFloat{0%,100%{transform:translateY(0) rotate(-4deg)}50%{transform:translateY(-5px) rotate(4deg)}}@keyframes orbitFloat{50%{transform:translate(-8px,9px) scale(1.08)}}@media(prefers-reduced-motion:reduce){.prk-stamp,.prk-orbit{animation:none!important}}`}</style></main></PublicLayout>}
