import PublicLayout from '../layouts/PublicLayout'

const pasos=[
  ['01','JUNTÁ','Cada clase, esfuerzo y desafío puede sumar nuevos sellos a tu Pasaporte PR Kids.'],
  ['02','ELEGÍ','Explorá los premios disponibles y elegí el que querés desbloquear.'],
  ['03','COMPROBÁ','Sacá una foto clara de la página del pasaporte donde están tus sellos.'],
  ['04','CANJEÁ','Enviá la solicitud. Punta Rollers valida los sellos y prepara el premio para una próxima clase.'],
]
const premios=[
  {nivel:'MINI',sellos:'—',nombre:'Primeros premios',texto:'Muy pronto vas a encontrar acá los primeros premios para canjear.'},
  {nivel:'PLUS',sellos:'—',nombre:'Premios especiales',texto:'Accesorios, sorpresas y recompensas PR Kids.'},
  {nivel:'LEGEND',sellos:'—',nombre:'Premios épicos',texto:'Los grandes desbloqueos del Club de Sellos.'},
]

function Stamp({delay=0}){return <span style={{animationDelay:`${delay}ms`}} className="prk-stamp grid h-12 w-12 place-items-center rounded-full border-2 border-dashed border-fuchsia-200/35 bg-fuchsia-300/[.08] text-[18px] shadow-[inset_0_0_18px_rgba(244,114,182,.08)]">✦</span>}

export default function PRKidsSellos(){
 return <PublicLayout><main className="mx-auto max-w-[620px] px-4 py-5 pb-16 text-white">
  <section className="prk-hero relative overflow-hidden rounded-[38px] border border-fuchsia-200/20 bg-[radial-gradient(circle_at_85%_12%,rgba(244,114,182,.23),transparent_30%),radial-gradient(circle_at_10%_90%,rgba(34,211,238,.13),transparent_32%),linear-gradient(145deg,#160b1a,#0b0b12_55%,#071315)] p-5 shadow-[0_28px_90px_rgba(0,0,0,.42)]">
   <div className="prk-orbit absolute -right-10 -top-12 h-44 w-44 rounded-full border border-fuchsia-200/10"/><div className="prk-orbit prk-orbit-b absolute right-8 top-10 h-20 w-20 rounded-full border border-cyan-200/10"/>
   <div className="relative"><div className="flex items-center gap-2"><span className="h-2 w-2 animate-pulse rounded-full bg-fuchsia-300"/><p className="text-[9px] font-black uppercase tracking-[.23em] text-fuchsia-100/65">PASAPORTE PR KIDS · TEMPORADA 2026</p></div><p className="mt-4 text-[11px] font-black uppercase tracking-[.18em] text-cyan-200/55">PUNTA ROLLERS PRESENTA</p><h1 className="mt-2 font-display text-[44px] leading-[.86] text-white">Club de<br/><span className="bg-gradient-to-r from-fuchsia-300 via-violet-200 to-cyan-200 bg-clip-text text-transparent">Sellos.</span></h1><p className="mt-5 max-w-[340px] text-[13px] leading-6 text-white/48">Cada sello cuenta una parte de tu aventura. Juntalos, desbloqueá recompensas y seguí rodando.</p></div>
   <div className="relative mt-6 flex gap-2"><Stamp/><Stamp delay={180}/><Stamp delay={360}/><div className="ml-auto grid h-12 min-w-24 place-items-center rounded-[18px] border border-white/10 bg-black/25 px-3"><p className="text-[8px] font-black uppercase tracking-[.15em] text-white/35">SELLÁ · SUMÁ<br/><span className="text-fuchsia-200/70">DESBLOQUEÁ</span></p></div></div>
  </section>

  <section className="mt-4 rounded-[30px] border border-white/[.07] bg-white/[.025] p-5"><p className="text-[9px] font-black uppercase tracking-[.2em] text-fuchsia-200/60">¿CÓMO FUNCIONA?</p><h2 className="mt-2 text-[25px] font-black leading-tight">Tu pasaporte se convierte en premios.</h2><div className="mt-5 space-y-2">{pasos.map(([n,t,x])=><div key={n} className="flex gap-3 rounded-[22px] border border-white/[.06] bg-black/20 p-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-fuchsia-300/10 text-[10px] font-black text-fuchsia-200">{n}</div><div><p className="text-[10px] font-black tracking-[.08em] text-white">{t}</p><p className="mt-1 text-[10px] leading-4 text-white/36">{x}</p></div></div>)}</div></section>

  <section className="mt-4"><div className="mb-3 flex items-end justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-cyan-200/55">PRIZE DROP</p><h2 className="mt-1 text-[24px] font-black">Premios para desbloquear</h2></div><span className="rounded-full border border-white/10 bg-white/[.035] px-3 py-1.5 text-[8px] font-black text-white/35">PRÓXIMAMENTE</span></div><div className="flex snap-x gap-3 overflow-x-auto pb-2">{premios.map((p,i)=><article key={p.nivel} className="min-w-[76%] snap-center overflow-hidden rounded-[28px] border border-white/[.07] bg-[#0d0d14]"><div className={`relative aspect-[16/10] ${i===0?'bg-[radial-gradient(circle_at_50%_40%,rgba(244,114,182,.18),transparent_35%),linear-gradient(145deg,#1b1020,#0b0b10)]':i===1?'bg-[radial-gradient(circle_at_50%_40%,rgba(167,139,250,.18),transparent_35%),linear-gradient(145deg,#151124,#0b0b10)]':'bg-[radial-gradient(circle_at_50%_40%,rgba(34,211,238,.16),transparent_35%),linear-gradient(145deg,#0b1a1d,#0b0b10)]'}`}><div className="absolute inset-0 grid place-items-center"><div className="grid h-20 w-20 place-items-center rounded-[28px] border border-dashed border-white/15 bg-white/[.03] text-3xl text-white/22">?</div></div><span className="absolute left-4 top-4 rounded-full border border-white/10 bg-black/35 px-3 py-1.5 text-[8px] font-black tracking-[.12em] text-white/55">{p.nivel}</span></div><div className="p-4"><p className="text-lg font-black">{p.nombre}</p><p className="mt-2 text-[10px] leading-4 text-white/35">{p.texto}</p><div className="mt-4 flex items-center justify-between"><span className="text-[9px] font-black text-fuchsia-200/60">{p.sellos} SELLOS</span><span className="text-[8px] font-black text-white/25">FOTO + STOCK PENDIENTE</span></div></div></article>)}</div></section>

  <section className="mt-4 overflow-hidden rounded-[30px] border border-cyan-200/15 bg-[linear-gradient(135deg,rgba(34,211,238,.08),rgba(244,114,182,.06))] p-5"><div className="flex items-start gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-[20px] border border-cyan-200/15 bg-cyan-300/[.06] text-2xl">📷</div><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-cyan-100/60">COMPROBACIÓN DE SELLOS</p><h2 className="mt-1 text-xl font-black">Tu pasaporte es la prueba.</h2><p className="mt-2 text-[10px] leading-5 text-white/38">Cuando hagas un canje vas a poder sacar una foto con la cámara del celular o elegirla desde la galería. La página completa y los sellos deben verse claramente.</p></div></div><button disabled className="mt-4 w-full rounded-[20px] border border-white/10 bg-white/[.04] py-4 text-[9px] font-black tracking-[.08em] text-white/30">📷 FOTOGRAFIAR PASAPORTE · AL CANJEAR</button></section>

  <section className="mt-4 rounded-[30px] border border-fuchsia-200/15 bg-fuchsia-300/[.045] p-5"><p className="text-[9px] font-black uppercase tracking-[.18em] text-fuchsia-200/60">TEMPORADA 2027</p><h2 className="mt-2 text-[22px] font-black">Tu próxima aventura ya viene en camino.</h2><p className="mt-2 text-[11px] leading-5 text-white/40">Cuando completes tu pasaporte actual, guardalo. Punta Rollers te entregará la nueva edición del Pasaporte PR Kids para continuar sumando historias, desafíos y sellos en 2027.</p></section>

  <section className="mt-4 rounded-[30px] border border-white/[.07] bg-black/20 p-5 text-center"><p className="text-[8px] font-black uppercase tracking-[.22em] text-white/25">SISTEMA OFICIAL DE RECOMPENSAS</p><p className="mt-2 font-display text-[26px] text-white">PR Kids · Punta Rollers</p><p className="mt-2 text-[9px] text-white/25">Los premios, requisitos y disponibilidad se confirmarán antes de cada canje.</p></section>
  <style>{`.prk-stamp{animation:stampFloat 3s ease-in-out infinite}.prk-orbit{animation:orbitFloat 7s ease-in-out infinite}.prk-orbit-b{animation-delay:-2s;animation-duration:5s}@keyframes stampFloat{0%,100%{transform:translateY(0) rotate(-4deg)}50%{transform:translateY(-5px) rotate(4deg)}}@keyframes orbitFloat{50%{transform:translate(-8px,9px) scale(1.08)}}@media(prefers-reduced-motion:reduce){.prk-stamp,.prk-orbit{animation:none!important}}`}</style>
 </main></PublicLayout>
}