import { useEffect, useMemo, useRef, useState } from 'react'
import PublicLayout from '../layouts/PublicLayout'
import { supabase } from '../lib/supabase'

const pasos=[['01','JUNTÁ','Cada clase, esfuerzo y desafío puede sumar nuevos sellos a tu Pasaporte PR Kids.'],['02','ELEGÍ','Explorá los premios disponibles y elegí el que querés desbloquear.'],['03','COMPROBÁ','Sacá una foto clara de la página del pasaporte donde están tus sellos.'],['04','CANJEÁ','Enviá la solicitud. Punta Rollers valida los sellos y prepara el premio para una próxima clase.']]
const oficiales=[{src:'/pasaporte-kids/01-presentacion-pasaporte-pr-kids.jpg',alt:'Presentación del Pasaporte PR Kids'},{src:'/pasaporte-kids/02-como-funciona-pasaporte-pr-kids.jpg',alt:'Cómo funciona el Pasaporte PR Kids'},{src:'/pasaporte-kids/03-experiencia-pasaporte-pr-kids.jpg',alt:'Experiencia Pasaporte PR Kids'}]
function Stamp({delay=0}){return <span style={{animationDelay:`${delay}ms`}} className="prk-stamp grid h-12 w-12 place-items-center rounded-full border-2 border-dashed border-fuchsia-200/35 bg-fuchsia-300/[.08] text-[18px]">✦</span>}
function Field({label,value,onChange,type='text',placeholder=''}){return <label className="block"><span className="mb-1.5 block text-[8px] font-black uppercase tracking-[.15em] text-white/30">{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-[17px] border border-white/[.08] bg-black/25 px-3 py-3 text-[12px] text-white outline-none placeholder:text-white/20 focus:border-fuchsia-200/30"/></label>}
function available(r){return Math.max(0,(r.stock_total||0)-(r.stock_reservado||0)-(r.stock_entregado||0))}

export default function PRKidsSellos(){
 const[rewards,setRewards]=useState([]),[loading,setLoading]=useState(true),[selected,setSelected]=useState(null),[step,setStep]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState(null),[photos,setPhotos]=useState([]),fileRef=useRef(null)
 const[form,setForm]=useState({child_name:'',child_document:'',parent_name:'',parent_phone:'',parent_document:'',declared_stamps:''})
 useEffect(()=>{supabase.rpc('pr_kids_rewards_public').then(({data})=>{setRewards(data||[]);setLoading(false)})},[])
 const canContinue=useMemo(()=>form.child_name.trim()&&form.parent_name.trim()&&form.parent_phone.trim()&&Number(form.declared_stamps||0)>=(selected?.sellos||0),[form,selected])
 function choose(r){setSelected(r);setStep(1);setError('');setReceipt(null);setPhotos([]);setTimeout(()=>document.getElementById('canje-pr-kids')?.scrollIntoView({behavior:'smooth'}),50)}
 function pickFiles(e){const next=[...e.target.files].filter(f=>f.type.startsWith('image/')).slice(0,5);setPhotos(next);setError(next.length?'':'Elegí al menos una foto clara del pasaporte.')}
 async function submit(){if(!selected||!canContinue||!photos.length)return setError('Completá los datos y adjuntá al menos una foto clara del pasaporte.');setBusy(true);setError('');let created=null;try{const{data,error:e}=await supabase.rpc('pr_kids_create_redemption_v2',{p_reward_id:selected.id,p_child_name:form.child_name,p_child_document:form.child_document,p_parent_name:form.parent_name,p_parent_phone:form.parent_phone,p_parent_document:form.parent_document,p_declared_stamps:Number(form.declared_stamps)});if(e)throw e;created=data;for(let i=0;i<photos.length;i++){const f=photos[i],ext=(f.name.split('.').pop()||'jpg').toLowerCase(),path=`redemptions/${created.id}/${Date.now()}-${i}.${ext}`;const up=await supabase.storage.from('pr-kids-sellos').upload(path,f,{upsert:false,contentType:f.type});if(up.error)throw up.error;const at=await supabase.rpc('pr_kids_attach_redemption_photo_v2',{p_redemption_id:created.id,p_upload_token:created.upload_token,p_photo_path:path});if(at.error)throw at.error}setReceipt({id:created.id,token:created.upload_token});setStep(4)}catch(e){setError(e.message||'No pudimos enviar el canje. Probá nuevamente.')}finally{setBusy(false)}}
 const shortId=receipt?.id?`PRK-${receipt.id.slice(0,6).toUpperCase()}`:''
 return <PublicLayout><main className="mx-auto max-w-[620px] px-4 py-5 pb-16 text-white">
  <section className="relative overflow-hidden rounded-[38px] border border-fuchsia-200/20 bg-[radial-gradient(circle_at_85%_12%,rgba(244,114,182,.23),transparent_30%),radial-gradient(circle_at_10%_90%,rgba(34,211,238,.13),transparent_32%),linear-gradient(145deg,#160b1a,#0b0b12_55%,#071315)] p-5 shadow-[0_28px_90px_rgba(0,0,0,.42)]"><div className="prk-orbit absolute -right-10 -top-12 h-44 w-44 rounded-full border border-fuchsia-200/10"/><div className="relative"><p className="text-[9px] font-black uppercase tracking-[.23em] text-fuchsia-100/65">PASAPORTE PR KIDS · TEMPORADA 2026</p><p className="mt-4 text-[11px] font-black uppercase tracking-[.18em] text-cyan-200/55">PUNTA ROLLERS PRESENTA</p><h1 className="mt-2 font-display text-[44px] leading-[.86]">Club de<br/><span className="bg-gradient-to-r from-fuchsia-300 via-violet-200 to-cyan-200 bg-clip-text text-transparent">Sellos.</span></h1><p className="mt-5 max-w-[350px] text-[13px] leading-6 text-white/48">Tu pasaporte cuenta tu historia. Ahora tus sellos también desbloquean recompensas.</p><div className="mt-6 flex gap-2"><Stamp/><Stamp delay={180}/><Stamp delay={360}/></div></div></section>

  <section className="mt-4 overflow-hidden rounded-[30px] border border-white/[.07] bg-black/20"><img src={oficiales[0].src} alt={oficiales[0].alt} className="block w-full"/><div className="p-5"><p className="text-[9px] font-black uppercase tracking-[.2em] text-fuchsia-200/60">DEL PASAPORTE AL PREMIO</p><h2 className="mt-2 text-[24px] font-black">Todo empieza con tus sellos.</h2><p className="mt-2 text-[10px] leading-5 text-white/38">El pasaporte físico sigue siendo el registro oficial. Para canjear, un adulto envía una foto clara y Punta Rollers valida los sellos antes de entregar el premio.</p></div></section>

  <section className="mt-4 rounded-[30px] border border-white/[.07] bg-white/[.025] p-5"><p className="text-[9px] font-black uppercase tracking-[.2em] text-fuchsia-200/60">¿CÓMO FUNCIONA?</p><div className="mt-4 grid grid-cols-2 gap-2">{pasos.map(([n,t,x])=><div key={n} className="rounded-[22px] border border-white/[.06] bg-black/20 p-4"><span className="text-[9px] font-black text-fuchsia-200/60">{n}</span><p className="mt-2 text-[11px] font-black">{t}</p><p className="mt-1 text-[9px] leading-4 text-white/34">{x}</p></div>)}</div></section>

  <section className="mt-5"><div className="mb-3"><p className="text-[9px] font-black uppercase tracking-[.2em] text-cyan-200/55">PRIZE DROP</p><h2 className="mt-1 text-[25px] font-black">Elegí tu próximo desbloqueo</h2></div>{loading?<div className="rounded-[28px] border border-white/[.07] p-8 text-center text-[10px] text-white/30">CARGANDO PREMIOS…</div>:rewards.length?<div className="flex snap-x gap-3 overflow-x-auto pb-2">{rewards.map(r=>{const stock=available(r);return <article key={r.id} className="min-w-[78%] snap-center overflow-hidden rounded-[28px] border border-white/[.07] bg-[#0d0d14]"><div className="relative aspect-[16/10] bg-[radial-gradient(circle_at_50%_40%,rgba(244,114,182,.15),transparent_38%),#111018]">{r.foto_url?<img src={r.foto_url} alt={r.nombre} className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-4xl text-white/15">✦</div>}<span className="absolute left-4 top-4 rounded-full bg-black/50 px-3 py-1.5 text-[8px] font-black">{r.nivel}</span></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-black">{r.nombre}</h3><p className="mt-1 text-[9px] leading-4 text-white/35">{r.descripcion}</p></div><span className="shrink-0 rounded-full bg-fuchsia-300/10 px-3 py-2 text-[10px] font-black text-fuchsia-200">{r.sellos} SELLOS</span></div><div className="mt-4 flex items-center justify-between"><span className={`text-[8px] font-black ${stock>2?'text-emerald-300':stock>0?'text-amber-300':'text-white/25'}`}>{stock>2?`DISPONIBLE · ${stock}`:stock>0?`ÚLTIMAS ${stock}`:'SIN STOCK'}</span><button disabled={!stock} onClick={()=>choose(r)} className="rounded-2xl bg-white px-4 py-2.5 text-[9px] font-black text-black disabled:opacity-20">CANJEAR →</button></div></div></article>})}</div>:<div className="rounded-[30px] border border-fuchsia-200/10 bg-fuchsia-300/[.035] p-6 text-center"><p className="text-3xl">🎁</p><h3 className="mt-3 text-lg font-black">Los premios están llegando.</h3><p className="mt-2 text-[10px] leading-5 text-white/35">Estamos preparando el primer Prize Drop. Cuando carguemos los premios reales, aparecerán acá con sus sellos y stock disponible.</p></div>}</section>

  {selected&&<section id="canje-pr-kids" className="mt-5 overflow-hidden rounded-[32px] border border-fuchsia-200/15 bg-[linear-gradient(145deg,rgba(244,114,182,.07),rgba(34,211,238,.035),rgba(255,255,255,.02))] p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[8px] font-black uppercase tracking-[.18em] text-fuchsia-200/60">CANJE SEGURO · PASO {Math.min(step,3)} DE 3</p><h2 className="mt-1 text-xl font-black">{selected.nombre}</h2><p className="mt-1 text-[9px] text-white/35">Requiere {selected.sellos} sellos · stock reservado al enviar</p></div><button onClick={()=>setSelected(null)} className="rounded-full border border-white/10 px-3 py-2 text-[8px] font-black text-white/35">CERRAR</button></div>
   {step===1&&<div className="mt-5"><p className="mb-3 text-[10px] font-black">1 · ¿Para quién es el canje?</p><div className="grid grid-cols-2 gap-2"><div className="col-span-2"><Field label="Nombre del niño/a *" value={form.child_name} onChange={v=>setForm({...form,child_name:v})} placeholder="Nombre y apellido"/></div><Field label="Documento del niño/a" value={form.child_document} onChange={v=>setForm({...form,child_document:v})} placeholder="Opcional"/><Field label="Sellos que tiene *" type="number" value={form.declared_stamps} onChange={v=>setForm({...form,declared_stamps:v})}/><div className="col-span-2"><Field label="Nombre del adulto responsable *" value={form.parent_name} onChange={v=>setForm({...form,parent_name:v})}/></div><Field label="Teléfono *" value={form.parent_phone} onChange={v=>setForm({...form,parent_phone:v})} placeholder="09…"/><Field label="Documento adulto" value={form.parent_document} onChange={v=>setForm({...form,parent_document:v})} placeholder="Opcional"/></div><button disabled={!canContinue} onClick={()=>setStep(2)} className="mt-4 w-full rounded-[20px] bg-white py-4 text-[10px] font-black text-black disabled:opacity-25">CONTINUAR · COMPROBAR SELLOS →</button></div>}
   {step===2&&<div className="mt-5"><p className="text-[10px] font-black">2 · Fotografíá el pasaporte</p><p className="mt-2 text-[10px] leading-5 text-white/38">Mostrá la página completa. Todos los sellos que quieras validar tienen que verse claramente. Podés subir hasta 5 fotos.</p><input ref={fileRef} className="hidden" type="file" accept="image/*" capture="environment" multiple onChange={pickFiles}/><button onClick={()=>fileRef.current?.click()} className="mt-4 w-full rounded-[22px] border border-cyan-200/15 bg-cyan-300/[.07] py-5 text-[10px] font-black text-cyan-100">📷 ABRIR CÁMARA / ELEGIR FOTOS</button>{photos.length>0&&<div className="mt-3 grid grid-cols-5 gap-2">{photos.map((f,i)=><div key={`${f.name}-${i}`} className="aspect-square overflow-hidden rounded-xl border border-white/10 bg-black"><img src={URL.createObjectURL(f)} alt="Pasaporte" className="h-full w-full object-cover"/></div>)}</div>}<div className="mt-4 rounded-[18px] border border-amber-200/10 bg-amber-300/[.04] p-3 text-[9px] leading-4 text-white/38">Conservá el pasaporte físico. Al retirar el premio, Punta Rollers verificará y marcará los sellos utilizados.</div><div className="mt-4 flex gap-2"><button onClick={()=>setStep(1)} className="w-1/3 rounded-[18px] border border-white/10 py-4 text-[9px] font-black text-white/45">VOLVER</button><button disabled={!photos.length} onClick={()=>setStep(3)} className="flex-1 rounded-[18px] bg-white py-4 text-[9px] font-black text-black disabled:opacity-25">REVISAR CANJE →</button></div></div>}
   {step===3&&<div className="mt-5"><p className="text-[10px] font-black">3 · Revisá antes de enviar</p><div className="mt-3 space-y-2 rounded-[22px] border border-white/[.07] bg-black/20 p-4 text-[10px]"><div className="flex justify-between"><span className="text-white/35">Niño/a</span><b>{form.child_name}</b></div><div className="flex justify-between"><span className="text-white/35">Premio</span><b>{selected.nombre}</b></div><div className="flex justify-between"><span className="text-white/35">Sellos requeridos</span><b>{selected.sellos}</b></div><div className="flex justify-between"><span className="text-white/35">Sellos declarados</span><b>{form.declared_stamps}</b></div><div className="flex justify-between"><span className="text-white/35">Fotos</span><b>{photos.length}</b></div></div><p className="mt-3 text-[9px] leading-4 text-white/30">Enviar la solicitud no aprueba automáticamente el canje. Punta Rollers revisará las fotos y confirmará la entrega.</p>{error&&<p className="mt-3 rounded-xl bg-red-400/10 p-3 text-[9px] text-red-200">{error}</p>}<div className="mt-4 flex gap-2"><button disabled={busy} onClick={()=>setStep(2)} className="w-1/3 rounded-[18px] border border-white/10 py-4 text-[9px] font-black text-white/45">VOLVER</button><button disabled={busy} onClick={submit} className="flex-1 rounded-[18px] bg-gradient-to-r from-fuchsia-300 to-cyan-200 py-4 text-[9px] font-black text-black disabled:opacity-40">{busy?'ENVIANDO…':'ENVIAR SOLICITUD ✓'}</button></div></div>}
   {step===4&&receipt&&<div className="mt-5 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full border border-emerald-200/20 bg-emerald-300/10 text-2xl text-emerald-200">✓</div><p className="mt-4 text-[9px] font-black uppercase tracking-[.18em] text-emerald-200/60">SOLICITUD RECIBIDA</p><h3 className="mt-2 text-2xl font-black">¡Canje en revisión!</h3><p className="mx-auto mt-2 max-w-[360px] text-[10px] leading-5 text-white/38">Vamos a comprobar los sellos enviados. Si todo está correcto, el premio se prepara para una próxima clase. Traé el pasaporte físico para completar la entrega.</p><div className="mx-auto mt-4 inline-block rounded-[18px] border border-white/10 bg-black/25 px-5 py-3"><p className="text-[7px] font-black text-white/25">NÚMERO DE SOLICITUD</p><p className="mt-1 text-sm font-black tracking-[.12em]">{shortId}</p></div></div>}
  </section>}

  <section className="mt-5 grid grid-cols-2 gap-2">{oficiales.slice(1).map(x=><img key={x.src} src={x.src} alt={x.alt} className="h-full w-full rounded-[22px] border border-white/[.07] object-cover"/>)}</section>
  <section className="mt-4 rounded-[30px] border border-fuchsia-200/15 bg-fuchsia-300/[.045] p-5"><p className="text-[9px] font-black uppercase tracking-[.18em] text-fuchsia-200/60">PASAPORTE 2027 · LA HISTORIA CONTINÚA</p><h2 className="mt-2 text-[22px] font-black">Cuando completes este, empieza el siguiente.</h2><p className="mt-2 text-[10px] leading-5 text-white/40">Guardá tu Pasaporte PR Kids 2026. Cuando esté completo, Punta Rollers te entregará la nueva edición para seguir construyendo tu colección en 2027.</p></section>
  <style>{`.prk-stamp{animation:stampFloat 3s ease-in-out infinite}.prk-orbit{animation:orbitFloat 7s ease-in-out infinite}@keyframes stampFloat{0%,100%{transform:translateY(0) rotate(-4deg)}50%{transform:translateY(-5px) rotate(4deg)}}@keyframes orbitFloat{50%{transform:translate(-8px,9px) scale(1.08)}}@media(prefers-reduced-motion:reduce){.prk-stamp,.prk-orbit{animation:none!important}}`}</style>
 </main></PublicLayout>
}