import {Link} from 'react-router-dom'
import AppLayout from '../layouts/AppLayout'
import {useAuth} from '../lib/auth'
const historic=[['Road to Shifter 2026','/app/historia/shifter-2026','Preparación, deberes y registros anteriores'],['Tomas de tiempo','/app/historia','Resultados históricos y evolución'],['Mi historia sobre ruedas','/app/historia','Tus capítulos, hitos y actividades'],['Wrapped 2026','/app/historia/wrapped-2026','Tu cierre anual con datos verificados']]
const personal=[['Mi Setup','Equipamiento y preferencias'],['Actividades recientes','Entrenamientos y momentos registrados'],['Conexión con Strava','Sincronización y permisos'],['Tus grupos','Tu comunidad de entrenamiento']]
export default function ProfileNext(){const{user,logout}=useAuth();const name=[user?.nombre,user?.apellido].filter(Boolean).join(' ')||'Supervisión';return <AppLayout title="Perfil"><main className="mx-auto max-w-[780px] space-y-5 px-4 pb-36 pt-4 text-white">
<div className="rounded-full border border-amber-200/15 bg-[#17141a] px-4 py-2 text-center"><span className="text-[10px] font-black tracking-[.13em] text-amber-100/60">MENSUALIDAD PR · SIN VERIFICAR EN ESTA DEMO</span></div>
<section className="relative overflow-hidden rounded-[32px] border border-violet-300/20 bg-[#11101b] pb-6 shadow-2xl"><div className="relative h-40 overflow-hidden bg-gradient-to-br from-[#44315e] via-[#1c1730] to-[#101018]"><div className="absolute -right-10 -top-16 h-56 w-56 rounded-full bg-violet-400/20 blur-3xl"/><div className="absolute bottom-3 left-5 text-[10px] font-black tracking-[.24em] text-white/55">PUNTA ROLLERS · TU PERFIL</div></div><div className="relative -mt-14 flex flex-col items-center px-5 text-center"><div className="grid h-28 w-28 place-items-center overflow-hidden rounded-full border-4 border-[#11101b] bg-gradient-to-br from-violet-300/25 to-violet-800/25 text-4xl font-black shadow-xl">{user?.foto?<img src={user.foto} alt="" className="h-full w-full object-cover"/>:name.slice(0,1)}</div><div className="mt-2 rounded-full border border-violet-300/20 bg-violet-300/10 px-4 py-1.5 text-[10px] font-black tracking-widest text-violet-100/80">PR ROLLER · VISTA BETA</div><h1 className="mt-4 text-3xl font-black tracking-tight">{name}</h1><p className="mt-3 max-w-sm text-[12px] leading-5 text-white/50">Vista de supervisión sin conexión a datos privados. El perfil original conserva biografía, fotografías, amigos y Pulso Roller; aquí todavía no se recuperan.</p><div className="mt-5 grid w-full grid-cols-3 gap-2">{['BIOGRAFÍA','AMIGOS PR','PULSO ROLLER'].map(x=><div key={x} className="rounded-xl border border-white/10 bg-white/[.035] px-2 py-3 text-[9px] font-black text-white/45">{x}</div>)}</div></div></section>
<section className="rounded-[26px] border border-violet-200/20 bg-gradient-to-r from-[#24172d] to-[#13111c] p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-black tracking-[.19em] text-violet-200/60">AMIGOS PR</p><h2 className="mt-2 text-xl font-black">Tu comunidad más cerca.</h2></div><span className="text-2xl text-violet-200/70">◎</span></div><details className="mt-4 rounded-xl border border-white/10 bg-black/20 p-4"><summary className="cursor-pointer text-xs font-bold">¿Cómo funciona Amigos PR?</summary><p className="mt-3 text-xs leading-5 text-white/55">Conectá con otros integrantes, visitá perfiles según sus permisos y descubrí sus publicaciones. Las solicitudes y los datos reales no se consultan desde esta beta.</p></details></section>
<section><div className="mb-3"><p className="text-[10px] font-black tracking-[.2em] text-amber-200/55">TU LEGADO · HISTORIAL INTACTO</p><h2 className="mt-2 text-2xl font-black">Tu historia no se borra.</h2></div><div className="grid gap-3 sm:grid-cols-2">{historic.map(([title,to,desc],i)=><Link key={title} to={to} className={`rounded-[23px] border p-5 ${i<2?'border-amber-200/20 bg-gradient-to-br from-[#2a2119] to-[#151219]':'border-white/10 bg-[#14131a]'}`}><p className="text-[10px] font-black tracking-[.16em] text-amber-100/50">{i<2?'ARCHIVO DESTACADO':'RECORRIDO PERSONAL'}</p><h3 className="mt-3 text-lg font-black">{title} ↗</h3><p className="mt-2 text-xs leading-5 text-white/50">{desc}</p></Link>)}</div></section>
<section><p className="mb-3 text-[10px] font-black tracking-[.2em] text-white/45">TUS HERRAMIENTAS PERSONALES</p><div className="grid grid-cols-2 gap-3">{personal.map(([title,desc])=><article key={title} className="min-h-[120px] rounded-[22px] border border-white/10 bg-[#14141b] p-4"><h3 className="text-sm font-black">{title}</h3><p className="mt-3 text-[11px] leading-5 text-white/45">{desc}</p><p className="mt-3 text-[9px] font-bold text-violet-200/45">Integración pendiente</p></article>)}</div></section>
<section className="rounded-[20px] border border-amber-200/15 bg-amber-200/[.035] p-4"><p className="text-xs font-black text-amber-100/65">VISTA DE SUPERVISIÓN</p><p className="mt-2 text-xs leading-5 text-white/50">La fotografía de banner, biografía, mensualidad, grupos, Strava y tiempos reales siguen en la plataforma original. Aquí no se muestran ni se modifican hasta tener una conexión de pruebas con permisos verificados.</p></section>
<button type="button" onClick={()=>logout()} className="w-full rounded-2xl border border-white/10 p-4 text-xs font-bold text-white/50">Salir de supervisión</button></main></AppLayout>}