import { useEffect, useMemo, useState } from 'react'
import AppLayout from '../layouts/AppLayout'
import { supabase } from '../lib/supabase'
import { useAuth } from '../lib/auth'

const DAY=86400000
const fmtKm=v=>Number(v||0).toLocaleString('es-UY',{minimumFractionDigits:1,maximumFractionDigits:1})
const fmtDur=s=>{s=Math.max(0,Number(s)||0);const h=Math.floor(s/3600),m=Math.floor((s%3600)/60);return h?`${h}h ${String(m).padStart(2,'0')}m`:`${m} min`}
const fmtDate=v=>v?new Intl.DateTimeFormat('es-UY',{day:'2-digit',month:'short',year:'numeric',timeZone:'America/Montevideo'}).format(new Date(v)):'—'
const speed=ms=>(Number(ms)||0)*3.6
const name=p=>[p?.nombre,p?.apellido].filter(Boolean).join(' ')||'Alumno PR'
const groups=p=>(Array.isArray(p?.grupos_info)?p.grupos_info:[]).map(x=>String(x?.titulo||x?.nombre||'').trim()).filter(Boolean)
function startFor(p){const n=Date.now();if(p==='7d')return new Date(n-7*DAY);if(p==='30d')return new Date(n-30*DAY);if(p==='90d')return new Date(n-90*DAY);if(p==='180d')return new Date(n-180*DAY);if(p==='365d')return new Date(n-365*DAY);return new Date('2020-01-01T00:00:00Z')}
function csvEscape(v){const s=String(v??'');return (s.includes(',')||s.includes('\
')||s.includes('\\r')||s.includes('\\"'))?'\\"'+s.replaceAll('\\"','\\"\\"')+'\\"':s}
function Metric({label,value,sub}){return <div className="rounded-[22px] border border-white/10 bg-white/[.035] p-4"><p className="text-[9px] font-black uppercase tracking-[.18em] text-white/30">{label}</p><p className="mt-2 text-2xl font-black tracking-[-.03em]">{value}</p>{sub?<p className="mt-1 text-[10px] text-white/35">{sub}</p>:null}</div>}

export default function PRPerformance(){
 const {user}=useAuth()
 const [profiles,setProfiles]=useState([]),[activities,setActivities]=useState([]),[tasks,setTasks]=useState([]),[results,setResults]=useState([]),[notes,setNotes]=useState([])
 const [selectedId,setSelectedId]=useState(''),[group,setGroup]=useState('ALL'),[period,setPeriod]=useState('30d'),[query,setQuery]=useState(''),[note,setNote]=useState(''),[visibility,setVisibility]=useState('staff'),[loading,setLoading]=useState(true),[message,setMessage]=useState('')
 async function load(){
   setLoading(true);setMessage('')
   const [p,a,t,r,n]=await Promise.all([
     supabase.from('profiles').select('id,nombre,apellido,foto,role,participa_como_alumno,grupos_info,estado').order('nombre'),
     supabase.from('pr_inline_skate_activities').select('id,alumno_id,nombre,fecha_inicio,distancia_metros,tiempo_movimiento_segundos,tiempo_total_segundos,desnivel_metros,velocidad_media_ms,velocidad_maxima_ms,frecuencia_cardiaca_media,frecuencia_cardiaca_maxima,es_privada').order('fecha_inicio',{ascending:false}).limit(5000),
     supabase.from('pr_training_tasks').select('*').eq('active',true).order('sort_order'),
     supabase.from('pr_training_task_results').select('*').order('updated_at',{ascending:false}).limit(5000),
     supabase.from('pr_performance_notes').select('*').order('created_at',{ascending:false}).limit(1000)
   ])
   const err=p.error||a.error||t.error||r.error||n.error;if(err){setMessage(err.message);setLoading(false);return}
   const students=(p.data||[]).filter(x=>x.role==='alumno'||x.participa_como_alumno===true)
   setProfiles(students);setActivities(a.data||[]);setTasks(t.data||[]);setResults(r.data||[]);setNotes(n.data||[]);if(!selectedId&&students[0]?.id)setSelectedId(students[0].id);setLoading(false)
 }
 useEffect(()=>{load()},[])
 const allGroups=useMemo(()=>[...new Set(profiles.flatMap(groups))].sort((a,b)=>a.localeCompare(b,'es')),[profiles])
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return profiles.filter(p=>(group==='ALL'||groups(p).includes(group))&&(!q||name(p).toLowerCase().includes(q)))},[profiles,group,query])
 const selected=profiles.find(p=>p.id===selectedId)||visible[0]||profiles[0]
 const start=useMemo(()=>startFor(period),[period])
 const acts=useMemo(()=>activities.filter(a=>a.alumno_id===selected?.id&&new Date(a.fecha_inicio)>=start),[activities,selected?.id,start])
 const studentResults=results.filter(r=>r.profile_id===selected?.id)
 const studentNotes=notes.filter(n=>n.profile_id===selected?.id)
 const visibleIds=useMemo(()=>new Set(visible.map(p=>p.id)),[visible])
 const groupActs=useMemo(()=>activities.filter(a=>visibleIds.has(a.alumno_id)&&new Date(a.fecha_inicio)>=start),[activities,visibleIds,start])
 const metrics=useMemo(()=>{const km=acts.reduce((s,a)=>s+(Number(a.distancia_metros)||0)/1000,0),seconds=acts.reduce((s,a)=>s+(Number(a.tiempo_movimiento_segundos)||0),0),elevation=acts.reduce((s,a)=>s+(Number(a.desnivel_metros)||0),0),av=acts.filter(a=>Number(a.velocidad_media_ms)>0),hr=acts.filter(a=>Number(a.frecuencia_cardiaca_media)>0);return{km,seconds,elevation,sessions:acts.length,avgSpeed:av.length?av.reduce((s,a)=>s+speed(a.velocidad_media_ms),0)/av.length:0,maxSpeed:Math.max(0,...acts.map(a=>speed(a.velocidad_maxima_ms))),avgHr:hr.length?hr.reduce((s,a)=>s+Number(a.frecuencia_cardiaca_media),0)/hr.length:0,longest:Math.max(0,...acts.map(a=>(Number(a.distancia_metros)||0)/1000))}},[acts])
 const completed=studentResults.filter(r=>r.status==='completed').length
 async function saveNote(){if(!note.trim()||!selected?.id)return;const {error}=await supabase.from('pr_performance_notes').insert({profile_id:selected.id,body:note.trim(),visibility,created_by:user?.id||null});if(error){setMessage(error.message);return}setNote('');await load()}
 function exportCSV(){const rows=[['Alumno','Fecha','Actividad','KM','Movimiento seg','Total seg','Vel media km/h','Vel max km/h','Desnivel +m','FC media','FC max','Privada']];for(const a of acts)rows.push([name(selected),fmtDate(a.fecha_inicio),a.es_privada?'Actividad privada':a.nombre||'',((Number(a.distancia_metros)||0)/1000).toFixed(2),a.tiempo_movimiento_segundos||0,a.tiempo_total_segundos||0,speed(a.velocidad_media_ms).toFixed(2),speed(a.velocidad_maxima_ms).toFixed(2),a.desnivel_metros||0,a.frecuencia_cardiaca_media||'',a.frecuencia_cardiaca_maxima||'',a.es_privada?'Sí':'No']);const blob=new Blob([rows.map(r=>r.map(csvEscape).join(',')).join('\\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),el=document.createElement('a');el.href=url;el.download=`PR-Performance-${name(selected).replaceAll(' ','-')}.csv`;el.click();URL.revokeObjectURL(url)}
 function exportGroupCSV(){const rows=[['Alumno','KM','Sesiones','Tiempo seg','Deberes completados','Deberes total']];for(const p of visible){const pa=groupActs.filter(a=>a.alumno_id===p.id),km=pa.reduce((s,a)=>s+(Number(a.distancia_metros)||0)/1000,0),secs=pa.reduce((s,a)=>s+(Number(a.tiempo_movimiento_segundos)||0),0),pr=results.filter(r=>r.profile_id===p.id&&r.status==='completed').length;rows.push([name(p),km.toFixed(2),pa.length,secs,pr,tasks.length])}const blob=new Blob([rows.map(r=>r.map(csvEscape).join(',')).join('\\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),el=document.createElement('a');el.href=url;el.download='PR-Performance-Equipo.csv';el.click();URL.revokeObjectURL(url)}
 function printGroupReport(){const w=window.open('','_blank','width=1100,height=800');if(!w)return;const rows=visible.map(p=>{const pa=groupActs.filter(a=>a.alumno_id===p.id),km=pa.reduce((s,a)=>s+(Number(a.distancia_metros)||0)/1000,0),secs=pa.reduce((s,a)=>s+(Number(a.tiempo_movimiento_segundos)||0),0),done=results.filter(r=>r.profile_id===p.id&&r.status==='completed').length;return `<tr><td>${name(p)}</td><td>${km.toFixed(1)} km</td><td>${pa.length}</td><td>${fmtDur(secs)}</td><td>${done}/${tasks.length}</td></tr>`}).join('');const totalKm=groupActs.reduce((s,a)=>s+(Number(a.distancia_metros)||0)/1000,0),totalSecs=groupActs.reduce((s,a)=>s+(Number(a.tiempo_movimiento_segundos)||0),0);w.document.write(`<!doctype html><html><head><title>PR Performance · Equipo</title><style>body{font-family:Arial;margin:36px;color:#111}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.card{border:1px solid #ddd;border-radius:14px;padding:14px}.big{font-size:24px;font-weight:800}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid #ddd;text-align:left;font-size:12px}@media print{button{display:none}}</style></head><body><p>PUNTA ROLLERS · PR PERFORMANCE</p><h1>Informe de equipo</h1><p>${group==='ALL'?'Todos los grupos':group} · ${period}</p><div class="grid"><div class="card"><div>ALUMNOS</div><div class="big">${visible.length}</div></div><div class="card"><div>KM</div><div class="big">${fmtKm(totalKm)}</div></div><div class="card"><div>SESIONES</div><div class="big">${groupActs.length}</div></div><div class="card"><div>TIEMPO</div><div class="big">${fmtDur(totalSecs)}</div></div></div><h2>Resumen por alumno</h2><table><thead><tr><th>Alumno</th><th>KM</th><th>Sesiones</th><th>Tiempo</th><th>Deberes</th></tr></thead><tbody>${rows}</tbody></table><p>Datos: Strava + Punta Rollers. Las actividades privadas solo aportan valores agregados.</p><button onclick="window.print()">Imprimir / Guardar PDF</button></body></html>`);w.document.close()}
 function printReport(){if(!selected)return;const w=window.open('','_blank','width=1000,height=800');if(!w)return;const activityRows=acts.slice(0,60).map(a=>`<tr><td>${fmtDate(a.fecha_inicio)}</td><td>${a.es_privada?'Actividad privada':(a.nombre||'Inline Skate')}</td><td>${fmtKm((Number(a.distancia_metros)||0)/1000)} km</td><td>${fmtDur(a.tiempo_movimiento_segundos)}</td><td>${speed(a.velocidad_media_ms).toFixed(1)} km/h</td><td>+${Math.round(Number(a.desnivel_metros)||0)} m</td></tr>`).join('');const duty=tasks.map(t=>{const rr=studentResults.find(r=>r.task_id===t.id);return `<li><b>${t.title}</b> — ${rr?.status==='completed'?'Completado':(rr?.status||'Pendiente')}</li>`}).join('');const coach=studentNotes.filter(n=>n.visibility!=='staff').map(n=>`<li>${n.body}</li>`).join('');w.document.write(`<!doctype html><html><head><title>PR Performance</title><style>body{font-family:Arial;margin:36px;color:#111}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.card{border:1px solid #ddd;border-radius:14px;padding:14px}.big{font-size:24px;font-weight:800}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left;font-size:12px}h2{margin-top:28px}@media print{button{display:none}}</style></head><body><p>PUNTA ROLLERS · PR PERFORMANCE</p><h1>${name(selected)}</h1><p>Informe generado ${new Date().toLocaleDateString('es-UY')} · ${period}</p><div class="grid"><div class="card"><div>KM</div><div class="big">${fmtKm(metrics.km)}</div></div><div class="card"><div>SESIONES</div><div class="big">${metrics.sessions}</div></div><div class="card"><div>TIEMPO</div><div class="big">${fmtDur(metrics.seconds)}</div></div><div class="card"><div>DESNIVEL</div><div class="big">+${Math.round(metrics.elevation)} m</div></div></div><h2>Actividades Inline Skate</h2><table><thead><tr><th>Fecha</th><th>Actividad</th><th>KM</th><th>Tiempo</th><th>Vel. media</th><th>Desnivel</th></tr></thead><tbody>${activityRows}</tbody></table><h2>Deberes PR</h2><ul>${duty||'<li>Sin deberes</li>'}</ul><h2>Observaciones compartibles</h2><ul>${coach||'<li>Sin observaciones compartibles</li>'}</ul><p>Datos: Strava + Punta Rollers. Las actividades privadas aportan métricas, sin exponer recorrido ni ubicación.</p><button onclick="window.print()">Imprimir / Guardar PDF</button></body></html>`);w.document.close()}
 return <AppLayout><main className="min-h-screen bg-[#050508] px-4 pb-24 pt-5 text-white"><div className="mx-auto max-w-6xl space-y-5">
 <section className="rounded-[34px] border border-orange-300/20 bg-[radial-gradient(circle_at_90%_0%,rgba(124,58,237,.24),transparent_38%),linear-gradient(135deg,#2c1702,#0b0c10_50%,#0c0715)] p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.24em] text-orange-300">PR PERFORMANCE · CENTRO DE RENDIMIENTO</p><h1 className="mt-2 text-4xl font-black tracking-[-.045em]">Expediente deportivo PR.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/45">Inline Skate + deberes + lectura técnica. Un único lugar para seguir evolución individual y del equipo.</p></div><a href="/admin" className="rounded-2xl border border-white/10 bg-black/25 px-4 py-3 text-xs font-black text-white/55">← PR Control</a></div><div className="mt-6 grid gap-2 sm:grid-cols-4"><select value={group} onChange={e=>setGroup(e.target.value)} className="rounded-2xl border border-white/10 bg-black/35 px-4 py-3 text-sm"><option value="ALL">Todos los grupos</option>{allGroups.map(g=><option key={g}>{g}</option>)}</select><select value={period} onChange={e=>setPeriod(e.target.value)} className="rounded-2xl border border-white/10 bg-black/35 px-4 py-3 text-sm"><option value="7d">7 días</option><option value="30d">30 días</option><option value="90d">90 días</option><option value="180d">6 meses</option><option value="365d">1 año</option><option value="all">Todo</option></select><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar alumno…" className="rounded-2xl border border-white/10 bg-black/35 px-4 py-3 text-sm outline-none"/><div className="grid grid-cols-2 gap-2"><button onClick={exportCSV} className="rounded-2xl border border-white/10 bg-white/[.05] px-2 py-3 text-[10px] font-black">CSV ALUMNO</button><button onClick={printReport} className="rounded-2xl bg-orange-300 px-2 py-3 text-[10px] font-black text-black">PDF ALUMNO</button></div></div><div className="mt-2 flex justify-end gap-2"><button onClick={exportGroupCSV} className="rounded-2xl border border-violet-300/20 bg-violet-400/[.08] px-4 py-2.5 text-[10px] font-black text-violet-200">CSV EQUIPO</button><button onClick={printGroupReport} className="rounded-2xl border border-violet-300/20 bg-violet-300 px-4 py-2.5 text-[10px] font-black text-black">PDF EQUIPO</button></div></section>
 {message?<div className="rounded-2xl border border-red-300/20 bg-red-400/[.07] p-4 text-sm">{message}</div>:null}
 <div className="grid gap-5 lg:grid-cols-[280px_1fr]"><aside className="rounded-[28px] border border-white/10 bg-white/[.025] p-3 lg:sticky lg:top-4 lg:self-start"><p className="px-2 pb-3 text-[9px] font-black uppercase tracking-[.18em] text-white/30">ALUMNOS · {visible.length}</p><div className="max-h-[70vh] space-y-1 overflow-auto">{visible.map(p=>{const pa=activities.filter(a=>a.alumno_id===p.id&&new Date(a.fecha_inicio)>=start),km=pa.reduce((s,a)=>s+(Number(a.distancia_metros)||0)/1000,0);return <button key={p.id} onClick={()=>setSelectedId(p.id)} className={`flex w-full items-center gap-3 rounded-2xl px-3 py-3 text-left ${selected?.id===p.id?'bg-orange-300 text-black':'hover:bg-white/[.04]'}`}>{p.foto?<img src={p.foto} className="h-10 w-10 rounded-full object-cover"/>:<div className="grid h-10 w-10 place-items-center rounded-full bg-white/10 text-xs font-black">{name(p).slice(0,2).toUpperCase()}</div>}<div className="min-w-0"><p className="truncate text-xs font-black">{name(p)}</p><p className="mt-1 text-[10px] opacity-50">{fmtKm(km)} km · {pa.length} sesiones</p></div></button>})}</div></aside>
 <section className="space-y-5">{loading?<div className="rounded-[28px] border border-white/10 bg-white/[.03] p-8 text-sm text-white/40">Cargando PR Performance…</div>:selected?<>
 <article className="rounded-[30px] border border-white/10 bg-white/[.03] p-5"><div className="flex items-center gap-4">{selected.foto?<img src={selected.foto} className="h-20 w-20 rounded-full object-cover"/>:<div className="grid h-20 w-20 place-items-center rounded-full bg-orange-300 text-xl font-black text-black">{name(selected).slice(0,2).toUpperCase()}</div>}<div><p className="text-[9px] font-black uppercase tracking-[.18em] text-orange-300">EXPEDIENTE DEPORTIVO</p><h2 className="mt-1 text-3xl font-black">{name(selected)}</h2><p className="mt-1 text-xs text-white/35">{groups(selected).join(' · ')||'Punta Rollers'}</p></div></div><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4"><Metric label="Kilómetros" value={fmtKm(metrics.km)} sub={`${metrics.sessions} sesiones`}/><Metric label="Tiempo" value={fmtDur(metrics.seconds)}/><Metric label="Vel. media" value={`${metrics.avgSpeed.toFixed(1)} km/h`} sub={`Máx. ${metrics.maxSpeed.toFixed(1)} km/h`}/><Metric label="Desnivel +" value={`${Math.round(metrics.elevation)} m`} sub={metrics.avgHr?`FC media ${Math.round(metrics.avgHr)} ppm`:'Sin FC suficiente'}/></div></article>
 <div className="grid gap-5 xl:grid-cols-2"><article className="rounded-[28px] border border-white/10 bg-white/[.025] p-5"><p className="text-[9px] font-black uppercase tracking-[.18em] text-emerald-300">DEBERES PR</p><h3 className="mt-1 text-xl font-black">{completed}/{tasks.length} completados</h3><div className="mt-4 space-y-2">{tasks.map(t=>{const rr=studentResults.find(r=>r.task_id===t.id),done=rr?.status==='completed';return <div key={t.id} className="rounded-2xl border border-white/8 bg-black/20 p-3"><div className="flex items-center justify-between gap-3"><p className="text-sm font-black">{t.title}</p><span className={`rounded-full px-2 py-1 text-[9px] font-black ${done?'bg-emerald-400/15 text-emerald-300':'bg-white/[.06] text-white/35'}`}>{done?'COMPLETADO':(rr?.status||'PENDIENTE').toUpperCase()}</span></div></div>})}</div></article>
 <article className="rounded-[28px] border border-white/10 bg-white/[.025] p-5"><p className="text-[9px] font-black uppercase tracking-[.18em] text-sky-300">LECTURA DEL ENTRENADOR</p><h3 className="mt-1 text-xl font-black">Notas técnicas</h3><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Técnica, resistencia, postura, objetivo…" className="mt-4 min-h-28 w-full rounded-2xl border border-white/10 bg-black/25 p-4 text-sm outline-none"/><div className="mt-2 flex gap-2"><select value={visibility} onChange={e=>setVisibility(e.target.value)} className="flex-1 rounded-2xl border border-white/10 bg-black/35 px-3 py-3 text-xs"><option value="staff">Solo staff</option><option value="coach_share">Compartible con entrenador</option><option value="student">Visible para alumno</option></select><button onClick={saveNote} className="rounded-2xl bg-sky-300 px-4 py-3 text-xs font-black text-black">Guardar</button></div><div className="mt-4 space-y-2">{studentNotes.map(n=><div key={n.id} className="rounded-2xl border border-white/8 bg-black/20 p-3"><p className="text-sm leading-5 text-white/70">{n.body}</p><p className="mt-2 text-[9px] uppercase tracking-[.12em] text-white/25">{fmtDate(n.created_at)} · {n.visibility==='staff'?'Solo staff':n.visibility==='coach_share'?'Compartible':'Alumno'}</p></div>)}</div></article></div>
 <article className="rounded-[28px] border border-white/10 bg-white/[.025] p-5"><div className="flex items-end justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-orange-300">SESIONES INLINE SKATE</p><h3 className="mt-1 text-xl font-black">Historial técnico</h3></div><p className="text-xs text-white/30">{acts.length} sesiones</p></div><div className="mt-4 space-y-2">{acts.slice(0,80).map(a=><details key={a.id} className="rounded-2xl border border-white/8 bg-black/20 p-4"><summary className="cursor-pointer list-none"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-black">{a.es_privada?'Actividad privada':(a.nombre||'Inline Skate')}</p><p className="mt-1 text-[10px] text-white/30">{fmtDate(a.fecha_inicio)} · {fmtDur(a.tiempo_movimiento_segundos)}</p></div><p className="text-lg font-black text-orange-300">{fmtKm((Number(a.distancia_metros)||0)/1000)} km</p></div></summary><div className="mt-4 grid grid-cols-2 gap-2 border-t border-white/8 pt-4 sm:grid-cols-4"><Metric label="Vel. media" value={`${speed(a.velocidad_media_ms).toFixed(1)} km/h`}/><Metric label="Vel. máxima" value={`${speed(a.velocidad_maxima_ms).toFixed(1)} km/h`}/><Metric label="Desnivel +" value={`${Math.round(Number(a.desnivel_metros)||0)} m`}/><Metric label="FC" value={a.frecuencia_cardiaca_media?`${Math.round(a.frecuencia_cardiaca_media)} ppm`:'—'} sub={a.frecuencia_cardiaca_maxima?`Máx. ${Math.round(a.frecuencia_cardiaca_maxima)}`:null}/></div>{a.es_privada?<p className="mt-3 rounded-xl border border-amber-300/15 bg-amber-300/[.06] p-3 text-[10px] text-amber-100/60">Privada en Strava: suma a las métricas, pero no se exportan recorrido ni ubicación.</p>:null}</details>)}</div></article>
 </>:null}</section></div></div></main></AppLayout>
}