import { useEffect, useMemo, useState } from 'react'
import AppLayout from '../layouts/AppLayout'
import { useAuth } from '../lib/auth'
import { supabase } from '../lib/supabase'

const EVENT='shifter-marathon-2026'
const CATEGORY_LABEL={ '6K':'6K', '12K':'12K' }
const pad=(n)=>String(n).padStart(2,'0')
function seriesNames(task){const n=Number(task.series_count||1);return Array.from({length:n},(_,i)=>n===1?`${task.strava_code} · ${task.title.toUpperCase()}`:`${task.strava_code}-S${i+1} · ${task.rule_type==='series_distance'?(Number(task.target_value)>=1000?`${Number(task.target_value)/1000}K`:`${Number(task.target_value)}M`):`${Number(task.target_value)} MIN`}`)}
function pctOf(done,total){return total?Math.round(done/total*100):0}
function ProfileDot({p}){return <div className="flex min-w-[74px] flex-col items-center"><div className="h-12 w-12 overflow-hidden rounded-full border-2 border-orange-300/35 bg-white/5">{p.foto?<img src={p.foto} className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-xs font-black">{(p.nombre||'PR')[0]}</div>}</div><span className="mt-1 max-w-[72px] truncate text-[9px] font-bold text-white/60">{p.nombre}</span><span className="text-[8px] font-black text-orange-300">{p.completed_tasks}/{p.total_tasks}</span></div>}

export default function PRTraining(){
 const {user}=useAuth(); const staff=['admin','profesor'].includes(user?.role)
 const [enrollment,setEnrollment]=useState(null),[tasks,setTasks]=useState([]),[results,setResults]=useState([]),[community,setCommunity]=useState([]),[profiles,setProfiles]=useState([]),[allResults,setAllResults]=useState([]),[saving,setSaving]=useState(false),[copied,setCopied]=useState(''),[open,setOpen]=useState({})
 async function load(){if(!user?.id)return;const {data:e}=await supabase.from('pr_training_enrollments').select('*').eq('profile_id',user.id).eq('event_slug',EVENT).maybeSingle();setEnrollment(e||null);if(e?.category&&e.category!=='NO'){const [{data:t},{data:r},{data:c},{data:p}]=await Promise.all([supabase.from('pr_training_tasks').select('*').eq('event_slug',EVENT).eq('active',true).in('category',[e.category,'ALL']).order('sort_order'),supabase.from('pr_training_task_results').select('*').eq('profile_id',user.id),supabase.from('pr_training_progress_public').select('*').order('progress_pct',{ascending:false}),supabase.from('profiles_public').select('id,nombre,apellido,foto')]);setTasks(t||[]);setResults(r||[]);setCommunity(c||[]);setProfiles(p||[]);if(staff){const {data:ar}=await supabase.from('pr_training_task_results').select('profile_id,task_id,status,progress_value,completed_at,updated_at');setAllResults(ar||[])}}}
 useEffect(()=>{load()},[user?.id])
 async function choose(category){setSaving(true);const {data}=await supabase.from('pr_training_enrollments').upsert({profile_id:user.id,event_slug:EVENT,category,active:category!=='NO',updated_at:new Date().toISOString()},{onConflict:'profile_id,event_slug'}).select().single();setEnrollment(data||{category});if(category!=='NO')window.localStorage.setItem('pr_training_visible','1');else window.localStorage.removeItem('pr_training_visible');setSaving(false);if(category!=='NO')load()}
 async function copy(code){try{await navigator.clipboard.writeText(code);setCopied(code);setTimeout(()=>setCopied(''),1600)}catch{}}
 const resultMap=useMemo(()=>new Map(results.map(r=>[r.task_id,r])),[results]);const completed=tasks.filter(t=>resultMap.get(t.id)?.status==='completed').length,pct=pctOf(completed,tasks.length);const profileMap=useMemo(()=>new Map(profiles.map(p=>[p.id,p])),[profiles]);const communityRows=community.map(c=>({...c,...profileMap.get(c.profile_id)}));
 if(!enrollment)return <AppLayout title="Deberes" showBack><div className="mx-auto max-w-lg px-4 pb-32 pt-5"><section className="overflow-hidden rounded-[36px] border border-orange-300/20 bg-[radial-gradient(circle_at_75%_0%,rgba(255,114,31,.3),transparent_38%),linear-gradient(145deg,#1b1015,#08080c_65%)] p-6 shadow-2xl"><p className="text-[10px] font-black uppercase tracking-[.25em] text-orange-300">Punta Rollers · Preparación</p><h1 className="mt-3 text-4xl font-black leading-[.9]">ROAD TO<br/><span className="text-orange-400">SHIFTER.</span></h1><p className="mt-5 text-sm leading-6 text-white/50">Un plan para complementar las clases y el trabajo de clínica hasta el día de la Shifter.</p></section><section className="mt-4 rounded-[28px] border border-white/8 bg-white/[.035] p-5"><p className="text-[10px] font-black uppercase tracking-[.18em] text-white/35">¿Participás de Shifter Marathon?</p><h2 className="mt-2 text-2xl font-black">Elegí tu distancia</h2><div className="mt-5 grid grid-cols-2 gap-3">{['6K','12K'].map(c=><button disabled={saving} key={c} onClick={()=>choose(c)} className="rounded-[24px] border border-orange-300/20 bg-orange-400/[.09] py-7 text-3xl font-black text-orange-300">{c}</button>)}</div><button disabled={saving} onClick={()=>choose('NO')} className="mt-3 w-full rounded-2xl border border-white/8 bg-white/[.025] py-4 text-xs font-bold text-white/40">No voy a participar</button></section></div></AppLayout>
 if(enrollment.category==='NO')return <AppLayout title="Deberes" showBack><div className="mx-auto max-w-lg px-4 py-10"><div className="rounded-[30px] border border-white/8 bg-white/[.03] p-6 text-center"><p className="text-xs font-black uppercase tracking-[.18em] text-white/30">Shifter Marathon</p><h1 className="mt-3 text-2xl font-black">Marcaste que no participás.</h1><button onClick={()=>setEnrollment(null)} className="mt-6 text-xs font-black text-orange-300">Cambiar respuesta</button></div></div></AppLayout>
 return <AppLayout title="Deberes" showBack><div className="mx-auto max-w-lg px-4 pb-36 pt-4">
  <section className="rounded-[36px] border border-orange-300/15 bg-[radial-gradient(circle_at_90%_0%,rgba(255,120,32,.25),transparent_38%),linear-gradient(150deg,#1c1015,#08080c_68%)] p-5 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.22em] text-orange-300">Road to Shifter</p><h1 className="mt-2 text-3xl font-black">{CATEGORY_LABEL[enrollment.category]} · TU CAMINO</h1></div><span className="rounded-full border border-orange-300/20 bg-orange-300/10 px-3 py-1.5 text-[9px] font-black text-orange-200">EN MARCHA</span></div><div className="mt-6 flex items-end justify-between"><div><p className="text-5xl font-black">{pct}<span className="text-xl text-white/35">%</span></p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.12em] text-white/35">{completed} de {tasks.length} deberes</p></div><p className="text-right text-[10px] leading-4 text-white/30">Preparación personal<br/>sin competir con nadie.</p></div><div className="mt-4 h-2.5 overflow-hidden rounded-full bg-white/7"><div className="h-full rounded-full bg-gradient-to-r from-orange-500 via-amber-400 to-yellow-200 transition-all" style={{width:`${pct}%`}}/></div></section>
  <section className="mt-4 rounded-[28px] border border-white/8 bg-white/[.03] p-5"><p className="text-[9px] font-black uppercase tracking-[.18em] text-orange-300">Antes de empezar</p><p className="mt-2 text-sm leading-6 text-white/60">Estos deberes complementan las clases y el trabajo de clínica. Tenés hasta la Shifter para completarlos. <b className="text-white">No se recomienda hacerlos todos en una semana:</b> organizalos a tu ritmo y priorizá calidad. Si los concentrás demasiado, repetí trabajos progresivos o técnicos durante el proceso.</p></section>
  <section className="mt-3 rounded-[28px] border border-orange-300/12 bg-[#111116] p-5"><p className="text-[9px] font-black uppercase tracking-[.18em] text-orange-300">Strava · en 4 pasos</p><div className="mt-3 space-y-2 text-xs leading-5 text-white/55"><p><b className="text-white">1.</b> Grabá normalmente tu entrenamiento con Strava.</p><p><b className="text-white">2.</b> Si hay series, guardá <b className="text-white">cada serie como una actividad separada</b>. La recuperación no cuenta como serie.</p><p><b className="text-white">3.</b> Al finalizar, Strava te deja cambiar el nombre. Pegá exactamente el nombre PR que aparece abajo.</p><p><b className="text-white">4.</b> Guardá. PR la detectará y actualizará tu progreso automáticamente.</p></div><p className="mt-4 rounded-2xl bg-orange-400/8 p-3 text-[10px] leading-5 text-orange-100/65">Puede existir una demora de sincronización entre Strava y Punta Rollers. Si no se marca enseguida, no dupliques la actividad ni cambies el nombre mientras se procesa.</p></section>
  <div className="mt-6"><p className="text-[9px] font-black uppercase tracking-[.2em] text-orange-300">Plan {enrollment.category}</p><h2 className="mt-1 text-2xl font-black">Tus 12 deberes</h2></div>
  <div className="mt-3 space-y-3">{tasks.map((t,i)=>{const r=resultMap.get(t.id),status=r?.status||'pending',series=seriesNames(t),done=Math.min(Number(r?.progress_value||0),Number(t.series_count||1)),spct=pctOf(done,Number(t.series_count||1));return <article key={t.id} className={`rounded-[30px] border p-5 ${status==='completed'?'border-emerald-300/20 bg-emerald-300/[.035]':'border-white/8 bg-white/[.028]'}`}><div className="flex gap-4"><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl text-xs font-black ${status==='completed'?'bg-emerald-400 text-black':'bg-white/6 text-white/45'}`}>{status==='completed'?'✓':pad(i+1)}</div><div className="min-w-0 flex-1"><p className="text-[9px] font-black uppercase tracking-[.16em] text-white/28">Deber {pad(i+1)}</p><h3 className="mt-1 text-lg font-black">{t.title}</h3><p className="mt-2 text-xs leading-5 text-white/48">{t.description}</p>{t.reference_text&&<p className="mt-2 text-[10px] font-bold text-amber-200/65">REFERENCIA · {t.reference_text}</p>}{t.recovery_minutes&&<p className="mt-1 text-[10px] font-bold text-sky-200/55">RECUPERACIÓN · {Number(t.recovery_minutes)} min entre series</p>}</div></div>{Number(t.series_count)>1&&<div className="mt-4"><div className="flex justify-between text-[9px] font-black uppercase tracking-[.12em] text-white/30"><span>Series</span><span>{done}/{t.series_count}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/7"><div className="h-full bg-orange-400" style={{width:`${spct}%`}}/></div></div>}<button onClick={()=>setOpen(o=>({...o,[t.id]:!o[t.id]}))} className="mt-4 text-[9px] font-black uppercase tracking-[.14em] text-orange-300">{open[t.id]?'Ocultar nombres':'Ver nombres para Strava'}</button>{open[t.id]&&<div className="mt-3 space-y-2">{series.map((name,si)=><div key={name} className="rounded-2xl border border-orange-300/12 bg-orange-300/[.05] p-3"><p className="text-[8px] font-black uppercase tracking-[.16em] text-orange-200/60">{series.length>1?`Serie ${si+1} · copiá este nombre`:'Copiá este nombre'}</p><div className="mt-2 flex items-center gap-2"><code className="min-w-0 flex-1 break-all text-[10px] font-black text-white">{name}</code><button onClick={()=>copy(name)} className="rounded-xl bg-orange-400 px-3 py-2 text-[8px] font-black text-black">{copied===name?'COPIADO ✓':'COPIAR'}</button></div></div>)}</div>}<p className={`mt-4 text-[9px] font-black uppercase tracking-[.14em] ${status==='completed'?'text-emerald-300':status==='incomplete'?'text-amber-300':status==='detected'?'text-sky-300':'text-white/28'}`}>{status==='completed'?'Deber completado ✓':status==='incomplete'?'Actividad detectada · revisá el objetivo':status==='detected'?`${done}/${t.series_count} series detectadas`:'Esperando Strava'}</p></article>})}</div>
  {communityRows.some(x=>x.completed_tasks>0)&&<section className="mt-7 overflow-hidden rounded-[30px] border border-orange-300/12 bg-[linear-gradient(145deg,#171014,#0c0c11)] p-5"><p className="text-[9px] font-black uppercase tracking-[.2em] text-orange-300">PR en movimiento</p><h2 className="mt-1 text-xl font-black">El equipo ya está entrenando.</h2><p className="mt-1 text-[10px] text-white/35">Progreso compartido para motivarnos, no para competir.</p><div className="mt-4 flex gap-3 overflow-x-auto pb-2">{communityRows.filter(x=>x.completed_tasks>0).map(p=><ProfileDot key={p.profile_id} p={p}/>)}</div></section>}
  {staff&&<section className="mt-7 rounded-[30px] border border-violet-300/15 bg-violet-300/[.04] p-5"><p className="text-[9px] font-black uppercase tracking-[.18em] text-violet-200">Seguimiento · Staff</p><h2 className="mt-1 text-xl font-black">Panel del equipo</h2><div className="mt-4 space-y-2">{communityRows.map(p=>{const rs=allResults.filter(r=>r.profile_id===p.profile_id),series=rs.reduce((s,r)=>s+Number(r.progress_value||0),0);return <div key={p.profile_id} className="rounded-2xl bg-black/20 p-3"><div className="flex items-center justify-between"><span className="text-xs font-black">{p.nombre} {p.apellido||''}</span><span className="text-[10px] font-black text-orange-300">{p.completed_tasks}/{p.total_tasks}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/7"><div className="h-full bg-violet-300" style={{width:`${p.progress_pct}%`}}/></div><p className="mt-2 text-[9px] text-white/30">{series} registros/series validados · {p.progress_pct}% del plan</p></div>})}</div></section>}
 </div></AppLayout>
}
