import { useEffect, useMemo, useState } from 'react'
import AppLayout from '../layouts/AppLayout'
import { useAuth } from '../lib/auth'
import { supabase } from '../lib/supabase'
const EVENT='shifter-marathon-2026'
export default function ShifterHistoryNext(){
 const{user}=useAuth();const[enrollment,setEnrollment]=useState(null),[tasks,setTasks]=useState([]),[results,setResults]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{let alive=true;(async()=>{if(!user?.id)return;const{data:e,error:ee}=await supabase.from('pr_training_enrollments').select('*').eq('profile_id',user.id).eq('event_slug',EVENT).maybeSingle();if(ee)throw ee;if(!alive)return;setEnrollment(e||null);if(e?.category&&e.category!=='NO'){const[{data:t,error:te},{data:r,error:re}]=await Promise.all([supabase.from('pr_training_tasks').select('*').eq('event_slug',EVENT).eq('active',true).order('sort_order'),supabase.from('pr_training_task_results').select('*').eq('profile_id',user.id)]);if(te||re)throw(te||re);if(!alive)return;setTasks((t||[]).filter(x=>x.category==='ALL'||x.category===e.category));setResults(r||[])}setLoading(false)})().catch(()=>{if(alive){setError('No pudimos leer tu historial de Shifter.');setLoading(false)}});return()=>{alive=false}},[user?.id])
 const map=useMemo(()=>new Map(results.map(r=>[r.task_id,r])),[results]);const completed=tasks.filter(t=>map.get(t.id)?.status==='completed').length;let distance=0,duration=0;results.forEach(r=>Object.values(r.evidence?.series||{}).forEach(x=>{if(x.valid){distance+=Number(x.distance_m||0);duration+=Number(x.moving_seconds||0)}}))
 if(loading)return <AppLayout title="Mi Historia"><main className="p-8 text-center text-white/40">Cargando tu historia…</main></AppLayout>
 return <AppLayout title="Mi Historia"><main className="mx-auto w-full max-w-[760px] space-y-4 px-4 pb-32 pt-4 text-white">
  <section className="relative overflow-hidden rounded-[36px] border border-amber-300/15 bg-[#0f0c08] p-6"><div className="absolute -right-20 -top-24 h-72 w-72 rounded-full bg-amber-400/10 blur-3xl"/><div className="relative"><p className="text-[8px] font-black tracking-[.24em] text-amber-200/70">MI HISTORIA · SHIFTER 2026</p><h1 className="mt-3 text-[34px] font-black tracking-[-.045em]">Lo que hiciste queda con vos.</h1><p className="mt-4 max-w-[500px] text-[11px] leading-5 text-white/38">Este capítulo conserva tus registros reales de preparación. No agregamos estadísticas estimadas ni datos inventados.</p></div></section>
  {error&&<section className="rounded-[24px] border border-red-300/15 bg-red-300/[.05] p-4 text-[10px] text-red-100/70">{error}</section>}
  {!enrollment||enrollment.category==='NO'?<section className="rounded-[30px] border border-white/[.07] bg-white/[.02] p-6"><p className="text-[8px] font-black tracking-[.18em] text-white/25">SHIFTER 2026</p><h2 className="mt-2 text-xl font-black">Sin capítulo de participación.</h2><p className="mt-2 text-[10px] leading-5 text-white/35">Tu cuenta no figura como participante activo en Road to Shifter. Por eso no mostramos un resumen que no te corresponde.</p></section>:<>
   <section className="grid grid-cols-3 gap-2"><Mini v={enrollment.category} l="DISTANCIA"/><Mini v={tasks.length?completed:'—'} l="DEBERES HECHOS"/><Mini v={distance?(distance/1000).toFixed(1)+' km':'—'} l="REGISTRADOS"/></section>
   <section className="rounded-[30px] border border-white/[.07] bg-[#101015] p-5"><div className="flex items-end justify-between"><div><p className="text-[8px] font-black tracking-[.18em] text-white/25">PREPARACIÓN</p><h2 className="mt-1 text-xl font-black">Tus deberes</h2></div><span className="text-[9px] font-black text-amber-200/60">{completed}/{tasks.length}</span></div><div className="mt-4 space-y-2">{tasks.map((t,i)=>{const r=map.get(t.id),done=r?.status==='completed';return <article key={t.id} className="flex items-center gap-3 rounded-[18px] border border-white/[.06] bg-black/20 p-3"><span className={'grid h-9 w-9 place-items-center rounded-full text-[9px] font-black '+(done?'bg-emerald-300 text-black':'bg-white/[.05] text-white/30')}>{done?'✓':String(i+1).padStart(2,'0')}</span><div className="min-w-0 flex-1"><p className="truncate text-[10px] font-black">{t.title}</p><p className="mt-1 text-[8px] text-white/25">{done&&r?.completed_at?'Registrado '+new Date(r.completed_at).toLocaleDateString('es-UY'):'Sin completar'}</p></div></article>})}</div></section>
   <section className="rounded-[28px] border border-violet-300/15 bg-violet-300/[.04] p-5"><p className="text-[8px] font-black tracking-[.18em] text-violet-200/55">DATOS CONSERVADOS</p><div className="mt-3 grid grid-cols-2 gap-2"><Mini v={duration?Math.round(duration/60)+' min':'—'} l="TIEMPO VÁLIDO"/><Mini v={results.length||'—'} l="REGISTROS"/></div></section>
  </>}
 </main></AppLayout>
}
function Mini({v,l}){return <div className="rounded-[20px] border border-white/[.07] bg-black/20 p-4 text-center"><p className="text-lg font-black">{v}</p><p className="mt-1 text-[7px] font-black tracking-[.12em] text-white/22">{l}</p></div>}
