import { useEffect, useMemo, useState } from 'react'
import AppLayout from '../layouts/AppLayout'
import { supabase } from '../lib/supabase'
const EVENT='shifter-marathon-2026'
export default function TeacherDashboardNext(){
 const[profiles,setProfiles]=useState([]),[acts,setActs]=useState([]),[enrollments,setEnrollments]=useState([]),[results,setResults]=useState([]),[tasks,setTasks]=useState([]),[loading,setLoading]=useState(true)
 useEffect(()=>{let alive=true;(async()=>{const[p,a,e,r,t]=await Promise.all([
  supabase.from('profiles').select('id,nombre,apellido,role,participa_como_alumno,foto').order('nombre'),
  supabase.from('pr_inline_skate_activities').select('alumno_id,distancia_metros,fecha_inicio,eliminada,fuente').eq('fuente','strava').eq('eliminada',false).limit(3000),
  supabase.from('pr_training_enrollments').select('profile_id,category,active').eq('event_slug',EVENT),
  supabase.from('pr_training_task_results').select('profile_id,task_id,status,updated_at'),
  supabase.from('pr_training_tasks').select('id,category').eq('event_slug',EVENT).eq('active',true)
 ]);if(!alive)return;setProfiles((p.data||[]).filter(x=>x.role==='alumno'||x.participa_como_alumno===true));setActs(a.data||[]);setEnrollments(e.data||[]);setResults(r.data||[]);setTasks(t.data||[]);setLoading(false)})().catch(()=>alive&&setLoading(false));return()=>{alive=false}},[])
 const rows=useMemo(()=>profiles.map(p=>{const pa=acts.filter(a=>String(a.alumno_id)===String(p.id));const km=pa.reduce((n,a)=>n+(Number(a.distancia_metros)||0)/1000,0);const e=enrollments.find(x=>String(x.profile_id)===String(p.id)&&x.category!=='NO');const plan=e?tasks.filter(t=>t.category==='ALL'||t.category===e.category):[];const done=new Set(results.filter(r=>String(r.profile_id)===String(p.id)&&r.status==='completed').map(r=>r.task_id));const completed=plan.filter(t=>done.has(t.id)).length;return{...p,km,sessions:pa.length,plan:e?.category||null,completed,total:plan.length}}),[profiles,acts,enrollments,results,tasks])
 const withActivity=rows.filter(x=>x.sessions>0).length,shifter=rows.filter(x=>x.plan).length
 return <AppLayout title="Profesores"><main className="mx-auto w-full max-w-[900px] space-y-4 px-4 pb-32 pt-4 text-white"><section className="relative overflow-hidden rounded-[34px] border border-violet-300/15 bg-[#0b0910] p-6"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-violet-500/15 blur-3xl"/><div className="relative"><p className="text-[8px] font-black tracking-[.22em] text-violet-200/65">DASHBOARD · PROFESORES</p><h1 className="mt-2 text-[31px] font-black tracking-[-.04em]">Una vista para acompañar, no para perseguir.</h1><p className="mt-3 max-w-[560px] text-[10px] leading-5 text-white/35">Lectura rápida de actividad y preparación con datos existentes. Sin modificar registros desde esta pantalla.</p></div></section>
 <section className="grid grid-cols-3 gap-2"><Stat v={loading?'—':rows.length} l="ALUMNOS"/><Stat v={loading?'—':withActivity} l="CON ACTIVIDAD"/><Stat v={loading?'—':shifter} l="SHIFTER"/></section>
 <section className="rounded-[30px] border border-white/[.07] bg-[#101015] p-5"><div className="flex items-end justify-between"><div><p className="text-[8px] font-black tracking-[.18em] text-white/25">SEGUIMIENTO</p><h2 className="mt-1 text-xl font-black">Alumnos</h2></div><span className="text-[8px] text-white/20">DATOS REALES · SOLO LECTURA</span></div><div className="mt-4 space-y-2">{loading?<p className="text-[10px] text-white/25">Cargando…</p>:rows.map(p=><article key={p.id} className="grid grid-cols-[1fr_auto] gap-3 rounded-[18px] border border-white/[.06] bg-black/20 p-3"><div className="min-w-0"><p className="truncate text-[10px] font-black">{p.nombre} {p.apellido||''}</p><p className="mt-1 text-[8px] text-white/25">{p.sessions} entrenos · {p.km.toLocaleString('es-UY',{maximumFractionDigits:1})} km</p></div><div className="text-right"><p className="text-[9px] font-black text-violet-200/65">{p.plan?p.plan:'—'}</p><p className="mt-1 text-[8px] text-white/25">{p.plan?p.completed+'/'+p.total+' deberes':'Sin Shifter'}</p></div></article>)}</div></section></main></AppLayout>
}
function Stat({v,l}){return <div className="rounded-[20px] border border-white/[.07] bg-black/20 p-4 text-center"><p className="text-xl font-black">{v}</p><p className="mt-1 text-[7px] font-black tracking-[.12em] text-white/22">{l}</p></div>}
