import { useEffect, useMemo, useState } from 'react'
import { useParams } from 'react-router-dom'
import PublicLayout from '../layouts/PublicLayout'
import { supabase } from '../lib/supabase'

function NfcIcon({size=32}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"><path d="M8 7c3 2.6 3 7.4 0 10M11 4c5 4.3 5 11.7 0 16M5 10c1.2 1.1 1.2 2.9 0 4"/><circle cx="4" cy="12" r="1" fill="currentColor" stroke="none"/></svg>}
function whatsappNumber(phone){let clean=String(phone||'').replace(/\D/g,'');if(clean.startsWith('00'))clean=clean.slice(2);if(clean.startsWith('598'))return clean;if(clean.startsWith('0'))clean=clean.slice(1);if(clean.length===8)return `598${clean}`;return clean}
function whatsappLink(phone,item,lost){const clean=whatsappNumber(phone);if(!clean)return'';const msg=lost?`Hola. Encontré tu ${item?.nombre||item?.tipo||'artículo'} reportado como extraviado. Escaneé su PR Tracking de Punta Rollers.`:`Hola. Tengo información sobre tu ${item?.nombre||item?.tipo||'artículo'} identificado con PR Tracking de Punta Rollers.`;return `https://wa.me/${clean}?text=${encodeURIComponent(msg)}`}
function callLink(phone){const clean=String(phone||'').replace(/[^\d+]/g,'');return clean?`tel:${clean}`:''}
function scanKey(publicId){try{const key=`pr_track_scan_${publicId}`,now=Date.now(),raw=localStorage.getItem(key),last=Number(raw||0);if(last&&now-last<30*60*1000)return null;localStorage.setItem(key,String(now));const bucket=Math.floor(now/(30*60*1000));return `${publicId}:${bucket}:${Math.random().toString(36).slice(2,10)}`}catch{return `${publicId}:${Math.floor(Date.now()/(30*60*1000))}`}}
const labels={patines:'Patines',casco:'Casco',mochila:'Mochila',protecciones:'Protecciones',termo:'Termo',otro:'Artículo'}
function ownerInitials(owner){return `${owner?.nombre?.[0]||''}${owner?.apellido?.[0]||''}`.toUpperCase()||'PR'}

export default function TrackPublicView(){
 const{publicId}=useParams(),[state,setState]=useState({loading:true,data:null,error:''}),[reported,setReported]=useState(false)
 useEffect(()=>{let alive=true;(async()=>{const{data,error}=await supabase.rpc('pr_track_public',{p_public_id:publicId});if(!alive)return;if(error){setState({loading:false,data:null,error:'Este Track ID todavía no está disponible.'});return}setState({loading:false,data:data||null,error:''});if(data?.status&&data.status!=='not_found'){const key=scanKey(publicId);if(key)supabase.rpc('pr_track_scan',{p_public_id:publicId,p_scan_key:key}).then(()=>{})}})();return()=>{alive=false}},[publicId])
 const data=state.data,item=data?.item||{},owner=data?.owner||{},paused=data?.status==='paused',missing=data?.status==='not_found',lost=data?.status==='lost',details=item?.detalles||{}
 const facts=useMemo(()=>{const base=[['Marca',item.marca],['Modelo',item.modelo],['Color',item.color]];const extra=Object.entries(details).filter(([k,v])=>v&&k!=='observaciones').map(([k,v])=>[k.charAt(0).toUpperCase()+k.slice(1),v]);return [...base,...extra].filter(([,v])=>v)},[item,details])
 const whatsapp=whatsappLink(owner.telefono,item,lost),call=callLink(owner.telefono)
 async function reportFound(){setReported(true);await supabase.rpc('pr_track_public_report',{p_public_id:publicId,p_kind:'found',p_note:'Reporte iniciado desde la ficha pública'});if(whatsapp)window.location.href=whatsapp}
 return <PublicLayout><div className="mx-auto max-w-[540px] px-4 py-5 pb-14">
  <section className="track-public-hero relative overflow-hidden rounded-[38px] border border-emerald-300/20 bg-[radial-gradient(circle_at_88%_12%,rgba(52,211,153,.20),transparent_26%),linear-gradient(145deg,#071310,#09090d_55%,#07100d)] p-5 shadow-[0_26px_90px_rgba(0,0,0,.42)]"><div className="track-ring absolute -right-10 -top-12 h-44 w-44 rounded-full border border-emerald-300/10"/><div className="track-ring track-ring-b absolute right-7 top-9 h-20 w-20 rounded-full border border-emerald-300/10"/><div className="relative flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-300"/><p className="text-[9px] font-black uppercase tracking-[.23em] text-emerald-200/70">PUNTA ROLLERS · NFC IDENTIFICADO</p></div><h1 className="mt-3 font-display text-[42px] leading-[.88] text-white">PR <span className="text-emerald-300">Tracking</span></h1><p className="mt-4 max-w-[280px] text-xs leading-5 text-white/42">Escaneaste un artículo protegido dentro del ecosistema Punta Rollers.</p></div><div className="relative grid h-16 w-16 shrink-0 place-items-center rounded-[22px] border border-emerald-200/20 bg-emerald-300/[.08] text-emerald-200"><span className="absolute inset-2 rounded-2xl border border-emerald-200/10 track-pulse"/><NfcIcon/></div></div></section>

  {state.loading&&<section className="mt-4 rounded-[30px] border border-white/[.07] bg-white/[.03] p-8 text-center"><div className="mx-auto h-10 w-10 animate-pulse rounded-full bg-emerald-300/20"/><p className="mt-4 text-sm font-black text-white/55">Leyendo identidad NFC…</p></section>}
  {!state.loading&&(state.error||missing)&&<section className="mt-4 rounded-[30px] border border-white/[.07] bg-white/[.03] p-7 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-[20px] border border-white/[.08] bg-white/[.035] text-white/30"><NfcIcon/></div><p className="mt-4 text-xl font-black text-white">Track ID no disponible</p><p className="mt-2 text-xs leading-5 text-white/38">{state.error||'No encontramos una ficha asociada a este identificador.'}</p></section>}
  {!state.loading&&paused&&<section className="mt-4 rounded-[30px] border border-amber-300/15 bg-amber-300/[.06] p-7 text-center"><h2 className="text-xl font-black text-white">Track ID temporalmente pausado</h2><p className="mt-2 text-xs leading-5 text-white/40">El NFC existe, pero la ficha pública se encuentra momentáneamente inactiva.</p></section>}

  {!state.loading&&!paused&&!missing&&!state.error&&data&&<div className="mt-4 space-y-4">
    {lost&&<section className="relative overflow-hidden rounded-[28px] border border-amber-300/25 bg-[linear-gradient(120deg,rgba(251,191,36,.14),rgba(249,115,22,.07))] p-4"><span className="absolute right-4 top-4 h-2.5 w-2.5 animate-pulse rounded-full bg-amber-300"/><p className="text-[9px] font-black uppercase tracking-[.18em] text-amber-200">ARTÍCULO REPORTADO COMO EXTRAVIADO</p><p className="mt-2 pr-8 text-lg font-black text-white">Si lo encontraste, podés avisarle al dueño ahora.</p></section>}

    <section className="overflow-hidden rounded-[34px] border border-white/[.08] bg-[#0a0a0f] shadow-[0_24px_70px_rgba(0,0,0,.30)]">
      <div className="relative aspect-[16/10] bg-gradient-to-br from-emerald-300/[.08] to-black">{item.foto_url?<img src={item.foto_url} alt={item.nombre||'Artículo PR'} className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-emerald-200/35"><NfcIcon size={52}/></div>}<div className="absolute inset-x-0 bottom-0 h-32 bg-gradient-to-t from-black via-black/40 to-transparent"/><div className="absolute bottom-4 left-4"><p className="text-[8px] font-black uppercase tracking-[.18em] text-emerald-200/70">{labels[item.tipo]||'Artículo'}</p><h2 className="mt-1 text-[28px] font-black leading-none text-white">{item.nombre||'Artículo PR'}</h2></div><span className={`absolute right-3 top-3 rounded-full border px-3 py-1.5 text-[8px] font-black backdrop-blur-xl ${lost?'border-amber-300/25 bg-amber-300/15 text-amber-100':'border-emerald-300/20 bg-black/45 text-emerald-200'}`}>{lost?'EXTRAVIADO':'NFC VERIFICADO'}</span></div>
      <div className="p-5"><p className="text-[8px] font-black uppercase tracking-[.18em] text-white/25">IDENTIFICACIÓN DEL ARTÍCULO</p>{facts.length>0&&<div className="mt-3 grid grid-cols-2 gap-2">{facts.map(([k,v])=><div key={k} className="rounded-[18px] border border-white/[.06] bg-white/[.025] p-3"><p className="text-[7px] font-black uppercase tracking-[.12em] text-white/22">{k}</p><p className="mt-1 text-[11px] font-bold text-white/68">{v}</p></div>)}</div>}{item.descripcion&&<div className="mt-4 rounded-[20px] border border-white/[.06] bg-black/20 p-4"><p className="text-[7px] font-black uppercase tracking-[.14em] text-white/22">DESCRIPCIÓN</p><p className="mt-2 text-xs leading-5 text-white/45">{item.descripcion}</p></div>}{details.observaciones&&<div className="mt-2 rounded-[20px] border border-violet-300/10 bg-violet-400/[.04] p-4"><p className="text-[7px] font-black uppercase tracking-[.14em] text-violet-200/50">OBSERVACIONES</p><p className="mt-2 text-xs leading-5 text-white/45">{details.observaciones}</p></div>}</div>
    </section>

    <section className="rounded-[32px] border border-white/[.08] bg-[linear-gradient(145deg,rgba(255,255,255,.045),rgba(255,255,255,.015))] p-5"><div className="flex items-center gap-3">{owner.foto?<img src={owner.foto} alt="" className="h-16 w-16 rounded-[22px] object-cover"/>:<div className="grid h-16 w-16 place-items-center rounded-[22px] bg-emerald-300/10 text-sm font-black text-emerald-200">{ownerInitials(owner)}</div>}<div><p className="text-[8px] font-black uppercase tracking-[.18em] text-emerald-200/55">DUEÑO REGISTRADO</p><h3 className="mt-1 text-xl font-black text-white">{owner.nombre||'—'} {owner.apellido||''}</h3><p className="mt-1 text-[10px] text-white/35">📍 {owner.ciudad||'Localidad no cargada'}</p></div></div><div className="mt-4 rounded-[20px] border border-white/[.06] bg-black/20 p-4"><p className="text-[7px] font-black uppercase tracking-[.14em] text-white/22">CONTACTO</p><p className="mt-2 text-sm font-black text-white">{owner.telefono||'Teléfono no disponible'}</p></div>
      <div className="mt-3 grid grid-cols-2 gap-2">{whatsapp?<button onClick={reportFound} className="min-h-13 rounded-2xl bg-emerald-300 px-3 text-[10px] font-black text-black">{reported?'ABRIENDO WHATSAPP…':'✓ ENCONTRÉ ESTE ARTÍCULO'}</button>:<div className="grid min-h-13 place-items-center rounded-2xl border border-white/10 text-[9px] font-black text-white/30">SIN WHATSAPP</div>}{call?<a href={call} className="grid min-h-13 place-items-center rounded-2xl border border-white/10 bg-white/[.04] text-[10px] font-black text-white/65">LLAMAR AL DUEÑO</a>:null}</div><p className="mt-3 text-[9px] leading-4 text-white/27">El botón registra el aviso en PR Tracking y abre WhatsApp con un mensaje preparado para contactar directamente al dueño.</p>
    </section>

    <section className="relative overflow-hidden rounded-[32px] border border-emerald-300/15 bg-[radial-gradient(circle_at_90%_20%,rgba(52,211,153,.14),transparent_28%),linear-gradient(135deg,rgba(52,211,153,.08),rgba(168,85,247,.06),rgba(255,255,255,.02))] p-5"><div className="absolute -right-10 -bottom-12 h-32 w-32 rounded-full border border-emerald-300/10"/><p className="text-[8px] font-black uppercase tracking-[.22em] text-emerald-300">SERVICIO EXCLUSIVO PARA ALUMNOS PR</p><h3 className="mt-2 font-display text-[28px] leading-none text-white">Trackeo NFC · Temporada 2026/27.</h3><p className="mt-3 text-xs leading-5 text-white/38">Tecnología de identificación Punta Rollers. Un toque acerca el artículo correcto a la persona correcta.</p><div className="mt-4 flex items-center gap-2 text-[8px] font-black uppercase tracking-[.14em] text-emerald-200/55"><NfcIcon size={20}/> ESCANEADO · IDENTIFICADO · CONECTADO</div></section>
  </div>}
  <style>{`.track-pulse{animation:trackPulse 2.2s ease-out infinite}.track-ring{animation:trackOrbit 7s ease-in-out infinite}.track-ring-b{animation-delay:-2s;animation-duration:5s}@keyframes trackPulse{0%{transform:scale(.7);opacity:.85}80%,100%{transform:scale(1.4);opacity:0}}@keyframes trackOrbit{50%{transform:translate(-9px,9px) scale(1.08)}}@media(prefers-reduced-motion:reduce){.track-pulse,.track-ring{animation:none!important}}`}</style>
 </div></PublicLayout>
}
