import { useEffect, useMemo, useState } from 'react'
import AppLayout from '../layouts/AppLayout'
import { useAuth } from '../lib/auth'
import { supabase } from '../lib/supabase'

function NfcMark({size=34}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.45" strokeLinecap="round"><path d="M8 7c3 2.6 3 7.4 0 10M11 4c5 4.3 5 11.7 0 16M5 10c1.2 1.1 1.2 2.9 0 4"/><circle cx="4" cy="12" r="1" fill="currentColor" stroke="none"/></svg>}
function buildUrl(publicId){if(!publicId)return'';return `${window.location.origin}/t/${publicId}`}
const TYPE_LABELS={patines:'Patines',casco:'Casco',mochila:'Mochila',protecciones:'Protecciones',termo:'Termo',otro:'Otro'}
function fieldsFor(type){if(type==='patines')return[['talle','Talle'],['ruedas','Ruedas'],['frame','Frame'],['bota','Bota']];if(type==='casco')return[['talle','Talle'],['material','Material']];if(type==='mochila')return[['diseno','Diseño'],['capacidad','Capacidad']];if(type==='protecciones')return[['talle','Talle'],['piezas','Qué incluye']];return[['talle','Talle'],['detalle','Detalle extra']]}
function initials(owner){return `${owner?.nombre?.[0]||''}${owner?.apellido?.[0]||''}`.toUpperCase()||'PR'}

export default function Tracking(){
 const{user}=useAuth(),profileId=user?.id,[items,setItems]=useState([]),[owner,setOwner]=useState(null),[ownerEdit,setOwnerEdit]=useState(false),[ownerForm,setOwnerForm]=useState({}),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[editing,setEditing]=useState(null),[form,setForm]=useState({}),[uploading,setUploading]=useState(false)
 useEffect(()=>{let alive=true;(async()=>{if(!profileId){setLoading(false);return}const[i,p]=await Promise.all([supabase.from('pr_track_items').select('*,pr_track_tags(*)').eq('alumno_id',profileId).order('created_at',{ascending:false}),supabase.from('profiles').select('id,nombre,apellido,telefono,ciudad,email,foto').eq('id',profileId).maybeSingle()]);if(!alive)return;if(i.error){setItems([]);setMessage('PR Tracking todavía está terminando de activarse.')}else setItems(i.data||[]);setOwner(p.data||null);setOwnerForm(p.data||{});setLoading(false)})();return()=>{alive=false}},[profileId])
 const totalTags=useMemo(()=>items.reduce((n,i)=>n+(Array.isArray(i.pr_track_tags)?i.pr_track_tags.filter(t=>t.estado!=='retired').length:0),0),[items])
 const ownerComplete=Boolean(owner?.nombre&&owner?.apellido&&owner?.telefono&&owner?.ciudad)
 function beginEdit(item){setEditing(item.id);setForm({tipo:item.tipo||'patines',marca:item.marca||'',modelo:item.modelo||'',color:item.color||'',descripcion:item.descripcion||'',foto_url:item.foto_url||'',detalles:item.detalles||{}})}
 async function uploadPhoto(item,file){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setMessage('Usá una imagen JPG, PNG o WEBP.');return}if(file.size>25*1024*1024){setMessage('La foto puede pesar hasta 25 MB.');return}setUploading(true);setMessage('');const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${profileId}/${item.id}/${Date.now()}.${ext}`;const{error}=await supabase.storage.from('pr-tracking-media').upload(path,file,{cacheControl:'3600',upsert:false});if(error){setUploading(false);setMessage('No se pudo subir la foto.');return}const{data}=supabase.storage.from('pr-tracking-media').getPublicUrl(path);setForm(v=>({...v,foto_url:data.publicUrl}));setUploading(false);setMessage('Foto cargada. Guardá los cambios para publicarla en tu Track ID.')}
 async function save(item){const payload={p_item_id:item.id,p_nombre:form.modelo||TYPE_LABELS[form.tipo]||'Artículo',p_tipo:form.tipo||'otro',p_marca:form.marca||'',p_modelo:form.modelo||'',p_color:form.color||'',p_descripcion:form.descripcion||'',p_foto_url:form.foto_url||'',p_mostrar_nombre:true,p_mostrar_telefono:true,p_mostrar_email:true,p_mostrar_ciudad:true};const[a,b]=await Promise.all([supabase.rpc('pr_track_update_item',payload),supabase.rpc('pr_track_update_details',{p_item_id:item.id,p_detalles:form.detalles||{}})]);if(a.error||b.error){setMessage('No se pudieron guardar los cambios.');return}setItems(v=>v.map(x=>x.id===item.id?{...x,...form,...(a.data||{}),detalles:form.detalles||{}}:x));setEditing(null);setMessage('Track ID actualizado. El NFC no necesita regrabarse.')}
 async function saveOwner(){const{data,error}=await supabase.rpc('pr_track_update_owner_contact',{p_nombre:ownerForm.nombre||'',p_apellido:ownerForm.apellido||'',p_telefono:ownerForm.telefono||'',p_ciudad:ownerForm.ciudad||'',p_email:ownerForm.email||''});if(error){setMessage(error.message);return}setOwner(data);setOwnerForm(data);setOwnerEdit(false);setMessage('Datos del dueño actualizados para PR Tracking.')} async function setLost(item,lost){const next=lost?'lost':'active';const{data,error}=await supabase.rpc('pr_track_set_state',{p_item_id:item.id,p_state:next});if(error){setMessage('No se pudo cambiar el estado del artículo.');return}setItems(v=>v.map(x=>x.id===item.id?{...x,...(data||{}),estado:next}:x));setMessage(lost?'Artículo marcado como extraviado. Quien escanee el NFC verá cómo contactarte.':'Artículo marcado como encontrado y activo.')}
 return <AppLayout title="PR Tracking" showBack><div className="pr-page space-y-4 pb-12 animate-page-enter">
  <section className="tracking-hero relative overflow-hidden rounded-[36px] border border-emerald-300/20 bg-[radial-gradient(circle_at_85%_15%,rgba(52,211,153,.20),transparent_30%),linear-gradient(145deg,#071310,#09090d_55%,#07100d)] p-5 shadow-[0_24px_80px_rgba(0,0,0,.35)]"><div className="tracking-orbit absolute -right-10 -top-12 h-44 w-44 rounded-full border border-emerald-300/10"/><div className="tracking-orbit tracking-orbit-2 absolute -right-3 top-4 h-24 w-24 rounded-full border border-emerald-300/10"/><div className="relative flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-300"/><p className="text-[9px] font-black uppercase tracking-[.24em] text-emerald-200/70">MI PR · TRACK ID</p></div><h1 className="mt-3 font-display text-[42px] leading-[.88] text-white">PR <span className="text-emerald-300">Tracking</span></h1><p className="mt-4 max-w-[280px] text-xs leading-5 text-white/42">Tu equipamiento, identificado. Tu contacto, a un toque. Tecnología NFC exclusiva de Punta Rollers.</p></div><div className="relative grid h-16 w-16 shrink-0 place-items-center rounded-[22px] border border-emerald-200/20 bg-emerald-300/[.08] text-emerald-200"><span className="absolute inset-2 rounded-2xl border border-emerald-200/10 tracking-pulse"/><NfcMark/></div></div><div className="relative mt-5 grid grid-cols-2 gap-2"><Stat n={items.length} l="ARTÍCULOS"/><Stat n={totalTags} l="NFC ACTIVOS"/></div></section>

  <section className={`rounded-[30px] border p-4 ${ownerComplete?'border-emerald-300/10 bg-[linear-gradient(145deg,rgba(52,211,153,.06),rgba(255,255,255,.02))]':'border-amber-300/20 bg-amber-300/[.055]'}`}><div className="flex items-center gap-3">{owner?.foto?<img src={owner.foto} alt="" className="h-16 w-16 rounded-[22px] object-cover"/>:<div className="grid h-16 w-16 place-items-center rounded-[22px] bg-emerald-300/10 text-sm font-black text-emerald-200">{initials(owner)}</div>}<div className="min-w-0 flex-1"><p className="text-[8px] font-black uppercase tracking-[.18em] text-emerald-200/55">DUEÑO DEL TRACK ID</p><p className="mt-1 truncate text-lg font-black text-white">{owner?.nombre||'—'} {owner?.apellido||''}</p><p className="mt-1 text-[10px] text-white/40">{owner?.ciudad||'Falta localidad'}</p></div><button onClick={()=>setOwnerEdit(v=>!v)} className="rounded-full border border-white/10 bg-white/[.04] px-3 py-2 text-[8px] font-black text-white/55">{ownerEdit?'CERRAR':'EDITAR'}</button></div><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-[18px] border border-white/[.06] bg-black/20 p-3"><p className="text-[7px] font-black uppercase text-white/20">TELÉFONO</p><p className="mt-1 text-[10px] font-bold text-white/65">{owner?.telefono||'Sin cargar'}</p></div><div className="rounded-[18px] border border-white/[.06] bg-black/20 p-3"><p className="text-[7px] font-black uppercase text-white/20">EMAIL</p><p className="mt-1 truncate text-[10px] font-bold text-white/65">{owner?.email||'Sin cargar'}</p></div></div>{ownerEdit&&<div className="mt-4 grid grid-cols-2 gap-2"><Field label="Nombre" value={ownerForm.nombre} onChange={v=>setOwnerForm({...ownerForm,nombre:v})}/><Field label="Apellido" value={ownerForm.apellido} onChange={v=>setOwnerForm({...ownerForm,apellido:v})}/><Field label="Teléfono" value={ownerForm.telefono} onChange={v=>setOwnerForm({...ownerForm,telefono:v})}/><Field label="Localidad" value={ownerForm.ciudad} onChange={v=>setOwnerForm({...ownerForm,ciudad:v})}/><div className="col-span-2"><Field label="Email" value={ownerForm.email} onChange={v=>setOwnerForm({...ownerForm,email:v})}/></div><button onClick={saveOwner} className="col-span-2 rounded-2xl bg-emerald-300 py-3 text-[9px] font-black text-black">GUARDAR DATOS DEL DUEÑO</button></div>}<p className="mt-3 text-[9px] leading-4 text-white/28">Nombre, apellido, teléfono y localidad son obligatorios para que la ficha NFC pueda devolver el artículo a su dueño.</p></section>

  {message&&<div className="rounded-[22px] border border-emerald-300/15 bg-emerald-300/[.05] p-4 text-xs leading-5 text-emerald-100/75">{message}</div>}
  {loading?<div className="h-72 animate-pulse rounded-[30px] bg-white/[.04]"/>:items.length?<section className="space-y-4">{items.map(item=>{const tags=Array.isArray(item.pr_track_tags)?item.pr_track_tags:[],open=editing===item.id,lost=item.estado==='lost',url=buildUrl(item.public_id),photo=open&&form.foto_url?form.foto_url:item.foto_url,details=open?(form.detalles||{}):(item.detalles||{});return <article key={item.id} className={`overflow-hidden rounded-[32px] border shadow-[0_18px_60px_rgba(0,0,0,.28)] ${lost?'border-amber-300/20 bg-[#151008]':'border-white/[.08] bg-[#0b0b10]'}`}>
    <div className="relative aspect-[16/9] w-full overflow-hidden bg-gradient-to-br from-emerald-300/[.08] to-black">{photo?<img src={photo} alt={item.nombre||'Artículo PR'} className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-emerald-200/35"><NfcMark size={46}/></div>}<div className="absolute inset-x-0 bottom-0 h-24 bg-gradient-to-t from-black/80 to-transparent"/><div className="absolute bottom-4 left-4"><p className="text-[8px] font-black uppercase tracking-[.18em] text-emerald-200/70">{TYPE_LABELS[item.tipo]||'Artículo'}</p><h2 className="mt-1 text-2xl font-black text-white">{item.modelo||item.marca||TYPE_LABELS[item.tipo]||'Artículo'}</h2></div><span className={`absolute right-3 top-3 rounded-full border px-3 py-1.5 text-[8px] font-black backdrop-blur ${lost?'border-amber-300/25 bg-amber-300/15 text-amber-100':'border-emerald-300/20 bg-black/45 text-emerald-200'}`}>{lost?'EXTRAVIADO':'PROTEGIDO'}</span></div>
    <div className="p-4"><div className="flex items-center justify-between gap-3"><p className="text-[9px] text-white/30">{tags.filter(t=>t.estado!=='retired').length} NFC activo{tags.filter(t=>t.estado!=='retired').length===1?'':'s'} · URL estable</p><button onClick={()=>open?setEditing(null):beginEdit(item)} className="rounded-full border border-white/10 bg-white/[.04] px-3 py-2 text-[8px] font-black text-white/55">{open?'CERRAR':'EDITAR FICHA'}</button></div>
    <div className="mt-3 grid grid-cols-2 gap-2"><a href={url} target="_blank" rel="noreferrer" className="grid min-h-12 place-items-center rounded-2xl border border-emerald-300/15 bg-emerald-300/[.07] text-[9px] font-black text-emerald-100">VER FICHA NFC ↗</a>{!lost?<button onClick={()=>setLost(item,true)} className="min-h-12 rounded-2xl border border-amber-300/15 bg-amber-300/[.07] text-[9px] font-black text-amber-100">REPORTAR EXTRAVIADO</button>:<button onClick={()=>setLost(item,false)} className="min-h-12 rounded-2xl bg-emerald-300 text-[9px] font-black text-black">✓ YA APARECIÓ</button>}</div>
    {open&&<div className="mt-5 space-y-4 border-t border-white/[.06] pt-4"><div className="rounded-[22px] border border-dashed border-emerald-300/20 bg-emerald-300/[.035] p-4"><p className="text-[8px] font-black uppercase tracking-[.15em] text-emerald-200/60">FOTO PRINCIPAL</p><p className="mt-1 text-[9px] text-white/30">Esta imagen será la cabecera de la ficha pública · hasta 25 MB.</p><label className="mt-3 grid min-h-12 cursor-pointer place-items-center rounded-2xl bg-emerald-300 text-[9px] font-black text-black"><input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" disabled={uploading} onChange={e=>uploadPhoto(item,e.target.files?.[0])}/>{uploading?'SUBIENDO…':form.foto_url?'CAMBIAR FOTO':'SUBIR FOTO'}</label></div>
      <div><p className="mb-3 text-[8px] font-black uppercase tracking-[.18em] text-white/25">DATOS DEL ARTÍCULO</p><p className="mb-3 text-[9px] leading-4 text-white/28">No hace falta ponerle un nombre. La ficha se identifica por tipo, marca y modelo.</p><div className="grid grid-cols-2 gap-2"><Select label="Tipo" value={form.tipo} onChange={v=>setForm({...form,tipo:v,detalles:{}})}/><Field label="Marca" value={form.marca} onChange={v=>setForm({...form,marca:v})}/><Field label="Modelo" value={form.modelo} onChange={v=>setForm({...form,modelo:v})}/><Field label="Color" value={form.color} onChange={v=>setForm({...form,color:v})}/>{fieldsFor(form.tipo).map(([key,label])=><Field key={key} label={label} value={details[key]} onChange={v=>setForm({...form,detalles:{...(form.detalles||{}),[key]:v}})}/>)}</div></div>
      <label className="block"><span className="text-[8px] font-black uppercase tracking-[.14em] text-white/25">Descripción</span><textarea value={form.descripcion||''} onChange={e=>setForm({...form,descripcion:e.target.value})} placeholder="Características para reconocerlo fácilmente…" className="mt-2 min-h-24 w-full rounded-2xl border border-white/[.08] bg-[#111118] p-3 text-xs text-white outline-none"/></label>
      <label className="block"><span className="text-[8px] font-black uppercase tracking-[.14em] text-white/25">Observaciones</span><textarea value={details.observaciones||''} onChange={e=>setForm({...form,detalles:{...(form.detalles||{}),observaciones:e.target.value}})} placeholder="Marcas particulares, accesorios, detalles únicos…" className="mt-2 min-h-20 w-full rounded-2xl border border-white/[.08] bg-[#111118] p-3 text-xs text-white outline-none"/></label>
      <button disabled={uploading} onClick={()=>save(item)} className="w-full rounded-2xl bg-emerald-300 py-4 text-[10px] font-black text-black disabled:opacity-40">GUARDAR FICHA TRACKING</button>
    </div>}</div>
  </article>})}</section>:<section className="rounded-[30px] border border-dashed border-emerald-300/20 bg-emerald-300/[.035] p-6 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-[20px] border border-emerald-300/15 bg-emerald-300/[.06] text-emerald-200"><NfcMark/></div><h2 className="mt-4 text-lg font-black text-white">Todavía no tenés Track ID</h2><p className="mx-auto mt-2 max-w-[300px] text-xs leading-5 text-white/38">Cuando Punta Rollers te entregue un NFC, tu artículo aparecerá acá.</p></section>}

  <section className="relative overflow-hidden rounded-[30px] border border-emerald-300/15 bg-[linear-gradient(135deg,rgba(52,211,153,.10),rgba(255,255,255,.02),rgba(168,85,247,.06))] p-5"><div className="absolute -right-10 -bottom-12 h-32 w-32 rounded-full border border-emerald-300/10"/><p className="text-[8px] font-black uppercase tracking-[.22em] text-emerald-300">EXCLUSIVO PUNTA ROLLERS</p><h2 className="mt-2 font-display text-[28px] leading-none text-white">Trackeo NFC · Temporada 2026/27.</h2><p className="mt-3 text-xs leading-5 text-white/38">Identidad digital para el equipamiento de alumnos PR. Escaneás. Identificás. Contactás. Sin apps extra.</p></section>
  <style>{`.tracking-pulse{animation:trackingPulse 2.4s ease-out infinite}.tracking-orbit{animation:trackingOrbit 8s linear infinite}.tracking-orbit-2{animation-direction:reverse;animation-duration:5s}@keyframes trackingPulse{0%{transform:scale(.72);opacity:.8}75%,100%{transform:scale(1.35);opacity:0}}@keyframes trackingOrbit{50%{transform:translate(-8px,10px) scale(1.08)}100%{transform:translate(0,0) scale(1)}}@media(prefers-reduced-motion:reduce){.tracking-pulse,.tracking-orbit{animation:none!important}}`}</style>
 </div></AppLayout>
}
function Stat({n,l}){return <div className="rounded-[18px] border border-white/[.07] bg-black/25 p-3"><p className="text-xl font-black text-white">{n}</p><p className="mt-1 text-[8px] uppercase tracking-wider text-white/25">{l}</p></div>}
function Field({label,value,onChange}){return <label className="block"><span className="text-[8px] font-black uppercase tracking-[.14em] text-white/25">{label}</span><input value={value||''} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-2xl border border-white/[.08] bg-[#111118] px-3 py-3 text-xs text-white outline-none"/></label>}
function Select({label,value,onChange}){return <label className="block"><span className="text-[8px] font-black uppercase tracking-[.14em] text-white/25">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-2xl border border-white/[.08] bg-[#111118] px-3 py-3 text-xs text-white"><option value="patines">Patines</option><option value="casco">Casco</option><option value="mochila">Mochila</option><option value="protecciones">Protecciones</option><option value="termo">Termo</option><option value="otro">Otro</option></select></label>}
