import { useEffect, useMemo, useState } from 'react'
import AppLayout from '../layouts/AppLayout'
import { useAuth } from '../lib/auth'
import { supabase } from '../lib/supabase'

function NfcMark(){return <svg width="34" height="34" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.45" strokeLinecap="round"><path d="M8 7c3 2.6 3 7.4 0 10M11 4c5 4.3 5 11.7 0 16M5 10c1.2 1.1 1.2 2.9 0 4"/><circle cx="4" cy="12" r="1" fill="currentColor" stroke="none"/></svg>}
function buildUrl(publicId){if(!publicId)return'';return `${window.location.origin}/t/${publicId}`}

export default function Tracking(){
 const{user}=useAuth(),profileId=user?.id,[items,setItems]=useState([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[editing,setEditing]=useState(null),[form,setForm]=useState({})
 useEffect(()=>{let alive=true;(async()=>{if(!profileId){setLoading(false);return}const{data,error}=await supabase.from('pr_track_items').select('*,pr_track_tags(*)').eq('alumno_id',profileId).order('created_at',{ascending:false});if(!alive)return;if(error){setItems([]);setMessage('PR Tracking todavía está terminando de activarse.')}else setItems(data||[]);setLoading(false)})();return()=>{alive=false}},[profileId])
 const totalTags=useMemo(()=>items.reduce((n,i)=>n+(Array.isArray(i.pr_track_tags)?i.pr_track_tags.filter(t=>t.estado!=='retired').length:0),0),[items])
 function beginEdit(item){setEditing(item.id);setForm({nombre:item.nombre||'',tipo:item.tipo||'patines',marca:item.marca||'',modelo:item.modelo||'',color:item.color||'',descripcion:item.descripcion||'',foto_url:item.foto_url||'',mostrar_nombre:item.mostrar_nombre!==false,mostrar_telefono:item.mostrar_telefono!==false,mostrar_email:Boolean(item.mostrar_email),mostrar_ciudad:item.mostrar_ciudad!==false})}
 async function save(item){const{error}=await supabase.from('pr_track_items').update(form).eq('id',item.id);if(error){setMessage('No se pudieron guardar los cambios.');return}setItems(v=>v.map(x=>x.id===item.id?{...x,...form}:x));setEditing(null);setMessage('Track ID actualizado. El NFC no necesita regrabarse.')}
 async function setLost(item,lost){const next=lost?'lost':'active';const{error}=await supabase.from('pr_track_items').update({estado:next}).eq('id',item.id);if(error){setMessage('No se pudo cambiar el estado del equipo.');return}setItems(v=>v.map(x=>x.id===item.id?{...x,estado:next}:x));setMessage(lost?'Equipo marcado como perdido. La ficha pública lo indicará al escanear el NFC.':'Equipo marcado nuevamente como encontrado y activo.')}
 return <AppLayout title="PR Tracking" showBack><div className="pr-page space-y-4 pb-12 animate-page-enter">
  <section className="relative overflow-hidden rounded-[34px] border border-emerald-300/15 bg-gradient-to-br from-emerald-300/[.13] via-white/[.025] to-transparent p-5"><div className="absolute -right-16 -top-20 h-52 w-52 rounded-full bg-emerald-300/10 blur-3xl"/><div className="relative flex items-start justify-between gap-4"><div><p className="text-[9px] font-black uppercase tracking-[.24em] text-emerald-200/70">MI PR · TRACK ID</p><h1 className="mt-2 font-display text-[38px] leading-none text-white">PR Tracking</h1><p className="mt-3 max-w-[280px] text-sm leading-6 text-white/45">Administrá los equipos que Punta Rollers vinculó a tus NFC.</p></div><div className="relative grid h-16 w-16 shrink-0 place-items-center rounded-[22px] border border-emerald-200/20 bg-emerald-300/[.08] text-emerald-200"><span className="absolute inset-2 rounded-2xl border border-emerald-200/10 tracking-pulse"/><NfcMark/></div></div><div className="mt-5 grid grid-cols-2 gap-2"><Stat n={items.length} l="Track ID"/><Stat n={totalTags} l="NFC activos"/></div></section>
  {message&&<div className="rounded-[22px] border border-emerald-300/15 bg-emerald-300/[.05] p-4 text-xs leading-5 text-emerald-100/75">{message}</div>}
  {loading?<div className="space-y-3">{[0,1].map(i=><div key={i} className="h-36 animate-pulse rounded-[28px] bg-white/[.04]"/>)}</div>:items.length?<section className="space-y-3">{items.map(item=>{const tags=Array.isArray(item.pr_track_tags)?item.pr_track_tags:[],open=editing===item.id,lost=item.estado==='lost',url=buildUrl(item.public_id);return <article key={item.id} className={`rounded-[28px] border p-4 ${lost?'border-amber-300/18 bg-amber-300/[.035]':'border-white/[.07] bg-white/[.025]'}`}>
    <div className="flex items-start justify-between gap-3"><div><p className={`text-[8px] font-black uppercase tracking-[.16em] ${lost?'text-amber-200':'text-emerald-200/60'}`}>{item.tipo||'EQUIPO'}</p><h2 className="mt-1 text-lg font-black text-white">{item.nombre||'Track ID'}</h2><p className="mt-1 text-[9px] text-white/28">{tags.filter(t=>t.estado!=='retired').length} NFC activo{tags.filter(t=>t.estado!=='retired').length===1?'':'s'} · {lost?'PERDIDO':String(item.estado||'draft').toUpperCase()}</p></div><button onClick={()=>open?setEditing(null):beginEdit(item)} className="rounded-2xl border border-white/[.08] bg-white/[.035] px-3 py-2 text-[9px] font-black text-white/55">{open?'Cerrar':'Editar'}</button></div>
    <div className="mt-3 rounded-[18px] border border-white/[.06] bg-black/20 p-3"><p className="text-[7px] font-black uppercase tracking-[.15em] text-white/20">TU URL ESTABLE</p><p className="mt-2 break-all text-[10px] font-bold text-emerald-200/75">{url}</p></div>
    <div className="mt-3 grid grid-cols-2 gap-2"><a href={url} target="_blank" rel="noreferrer" className="grid min-h-11 place-items-center rounded-2xl border border-emerald-300/15 bg-emerald-300/[.06] px-3 text-[9px] font-black text-emerald-100">VER COMO LO VEN</a>{item.estado==='active'&&<button onClick={()=>setLost(item,true)} className="min-h-11 rounded-2xl border border-amber-300/15 bg-amber-300/[.06] px-3 text-[9px] font-black text-amber-100">REPORTAR PERDIDO</button>}{lost&&<button onClick={()=>setLost(item,false)} className="min-h-11 rounded-2xl bg-emerald-300 px-3 text-[9px] font-black text-black">YA LO ENCONTRÉ</button>}</div>
    {open&&<div className="mt-4 space-y-3 border-t border-white/[.06] pt-4"><div className="grid grid-cols-2 gap-2"><Field label="Nombre" value={form.nombre} onChange={v=>setForm({...form,nombre:v})}/><Select label="Tipo" value={form.tipo} onChange={v=>setForm({...form,tipo:v})}/><Field label="Marca" value={form.marca} onChange={v=>setForm({...form,marca:v})}/><Field label="Modelo" value={form.modelo} onChange={v=>setForm({...form,modelo:v})}/><Field label="Color" value={form.color} onChange={v=>setForm({...form,color:v})}/><Field label="Foto URL" value={form.foto_url} onChange={v=>setForm({...form,foto_url:v})}/></div><label className="block"><span className="text-[8px] font-black uppercase tracking-[.14em] text-white/25">Descripción</span><textarea value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})} className="mt-2 min-h-24 w-full rounded-2xl border border-white/[.08] bg-[#111118] p-3 text-xs text-white outline-none"/></label><div className="rounded-[20px] border border-white/[.06] bg-black/20 p-3"><p className="text-[8px] font-black uppercase tracking-[.14em] text-white/25">DATOS QUE PUEDE VER QUIEN ESCANEA</p><div className="mt-3 grid grid-cols-2 gap-2"><Toggle label="Nombre" checked={form.mostrar_nombre} onChange={v=>setForm({...form,mostrar_nombre:v})}/><Toggle label="WhatsApp" checked={form.mostrar_telefono} onChange={v=>setForm({...form,mostrar_telefono:v})}/><Toggle label="Email" checked={form.mostrar_email} onChange={v=>setForm({...form,mostrar_email:v})}/><Toggle label="Ciudad" checked={form.mostrar_ciudad} onChange={v=>setForm({...form,mostrar_ciudad:v})}/></div></div><button onClick={()=>save(item)} className="w-full rounded-2xl bg-emerald-300 py-4 text-[10px] font-black text-black">GUARDAR CAMBIOS</button></div>}
  </article>})}</section>:<section className="rounded-[30px] border border-dashed border-emerald-300/20 bg-emerald-300/[.035] p-6 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-[20px] border border-emerald-300/15 bg-emerald-300/[.06] text-emerald-200"><NfcMark/></div><h2 className="mt-4 text-lg font-black text-white">Todavía no tenés Track ID</h2><p className="mx-auto mt-2 max-w-[300px] text-xs leading-5 text-white/38">Cuando Punta Rollers te entregue un NFC, el equipo aparecerá acá y vas a poder editar su información sin regrabar el chip.</p></section>}
  <section className="rounded-[26px] border border-white/[.06] bg-white/[.025] p-4"><p className="text-[9px] font-black uppercase tracking-[.16em] text-white/25">UNA URL POR EQUIPO</p><p className="mt-2 text-xs leading-5 text-white/38">Podés tener varios Track ID. Cada par de patines, casco u objeto puede tener su propia URL. Si un mismo equipo lleva dos NFC físicos, ambos pueden apuntar a la misma ficha.</p></section>
  <style>{`.tracking-pulse{animation:trackingPulse 2.4s ease-out infinite}@keyframes trackingPulse{0%{transform:scale(.72);opacity:.8}75%,100%{transform:scale(1.35);opacity:0}}@media(prefers-reduced-motion:reduce){.tracking-pulse{animation:none!important}}`}</style>
 </div></AppLayout>
}
function Stat({n,l}){return <div className="rounded-[18px] border border-white/[.07] bg-black/20 p-3"><p className="text-xl font-black text-white">{n}</p><p className="mt-1 text-[8px] uppercase tracking-wider text-white/25">{l}</p></div>}
function Field({label,value,onChange}){return <label className="block"><span className="text-[8px] font-black uppercase tracking-[.14em] text-white/25">{label}</span><input value={value||''} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-2xl border border-white/[.08] bg-[#111118] px-3 py-3 text-xs text-white outline-none"/></label>}
function Select({label,value,onChange}){return <label className="block"><span className="text-[8px] font-black uppercase tracking-[.14em] text-white/25">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-2xl border border-white/[.08] bg-[#111118] px-3 py-3 text-xs text-white"><option value="patines">Patines</option><option value="casco">Casco</option><option value="protecciones">Protecciones</option><option value="termo">Termo</option><option value="otro">Otro</option></select></label>}
function Toggle({label,checked,onChange}){return <button type="button" onClick={()=>onChange(!checked)} className={`flex min-h-11 items-center justify-between rounded-2xl border px-3 text-[9px] font-black ${checked?'border-emerald-300/18 bg-emerald-300/[.06] text-emerald-100':'border-white/[.07] bg-white/[.025] text-white/35'}`}><span>{label}</span><span className={`h-2.5 w-2.5 rounded-full ${checked?'bg-emerald-300':'bg-white/15'}`}/></button>}
