import { useEffect,useMemo,useState } from 'react'
import { Link } from 'react-router-dom'
import AppLayout from '../layouts/AppLayout'
import { useAuth } from '../lib/auth'
import { supabase } from '../lib/supabase'
import { isChristmasSeasonActive } from '../lib/prSeason'
export default function WrappedNext(){const{user}=useAuth();const[loading,setLoading]=useState(true),[acts,setActs]=useState([]),[events,setEvents]=useState([]),[badges,setBadges]=useState([]);const open=isChristmasSeasonActive()
 useEffect(()=>{let alive=true;(async()=>{if(!user?.id)return setLoading(false);const[a,e,b]=await Promise.all([supabase.from('pr_inline_skate_activities').select('id,distancia_metros,fecha_inicio,tiempo_movimiento_segundos').eq('alumno_id',user.id).eq('fuente','strava').eq('eliminada',false).gte('fecha_inicio','2026-01-01').lt('fecha_inicio','2027-01-01').order('fecha_inicio',{ascending:false}).limit(3000),supabase.from('actividad_pr').select('id,tipo,titulo,fecha').eq('alumno_id',user.id).eq('tipo','Evento').gte('fecha','2026-01-01').lt('fecha','2027-01-01').or('eliminado.is.null,eliminado.eq.false').limit(200),supabase.from('actividad_pr').select('id,tipo,titulo,fecha').eq('alumno_id',user.id).eq('tipo','Insignia').gte('fecha','2026-01-01').lt('fecha','2027-01-01').or('eliminado.is.null,eliminado.eq.false').limit(200)]);if(!alive)return;setActs(a.data||[]);setEvents(e.data||[]);setBadges(b.data||[]);setLoading(false)})().catch(()=>alive&&setLoading(false));return()=>{alive=false}},[user?.id])
 const stats=useMemo(()=>{const km=acts.reduce((n,x)=>n+(Number(x.distancia_metros)||0)/1000,0),seconds=acts.reduce((n,x)=>n+(Number(x.tiempo_movimiento_segundos)||0),0),months=new Set(acts.map(x=>String(x.fecha_inicio||'').slice(0,7)).filter(Boolean)).size;return{km,sessions:acts.length,hours:seconds/3600,events:events.length,badges:badges.length,months}},[acts,events,badges]);const enough=stats.sessions>=3||stats.events>=1||stats.badges>=1
 return <AppLayout title="Wrapped 2026"><main className="mx-auto w-full max-w-[760px] space-y-5 px-4 pb-32 pt-4 text-white">{!open?<Locked/>:loading?<Loading/>:!enough?<Fresh/>:<><section className="relative min-h-[520px] overflow-hidden rounded-[44px] border border-white/[.09] bg-[#070709] p-6 shadow-[0_34px_120px_rgba(0,0,0,.62)]"><div className="absolute -right-24 -top-24 h-80 w-80 rounded-full bg-fuchsia-500/[.13] blur-3xl"/><div className="absolute -bottom-28 -left-20 h-72 w-72 rounded-full bg-cyan-400/[.10] blur-3xl"/><div className="relative flex min-h-[465px] flex-col justify-between"><div><p className="text-[7px] font-black tracking-[.28em] text-white/35">PUNTA ROLLERS · WRAPPED 2026</p><h1 className="mt-8 text-[49px] font-black leading-[.86] tracking-[-.07em]">Tu año<br/><span className="bg-gradient-to-r from-fuchsia-200 via-violet-200 to-cyan-200 bg-clip-text text-transparent">sobre ruedas.</span></h1><p className="mt-5 max-w-[500px] text-[10px] leading-5 text-white/30">No es una estimación ni un resumen genérico. Esto sale de los registros reales que Punta Rollers tiene de tu 2026.</p></div><div className="grid grid-cols-2 gap-2"><Big v={stats.sessions} l="ENTRENAMIENTOS"/><Big v={stats.km.toLocaleString('es-UY',{maximumFractionDigits:1})+' km'} l="DISTANCIA"/><Big v={stats.hours.toLocaleString('es-UY',{maximumFractionDigits:1})+' h'} l="TIEMPO EN MOVIMIENTO"/><Big v={stats.months} l="MESES CON ACTIVIDAD"/></div></div></section><section className="grid grid-cols-2 gap-2"><Card v={stats.events} t="Eventos" d="Experiencias registradas durante 2026."/><Card v={stats.badges} t="Hitos" d="Insignias que quedaron guardadas en tu historia."/></section><section className="rounded-[32px] border border-amber-200/12 bg-amber-200/[.035] p-5"><p className="text-[7px] font-black tracking-[.2em] text-amber-100/42">FINAL DE TEMPORADA</p><h2 className="mt-2 text-[28px] font-black tracking-[-.04em]">2026 fue esto.<br/><span className="text-amber-100/48">2027 recién empieza.</span></h2><p className="mt-3 text-[9px] leading-5 text-white/28">Tu historia queda guardada en Seasons para que el año que viene no vuelvas a empezar desde cero.</p><div className="mt-5 flex gap-2"><Link to="/app/historia" className="rounded-full border border-white/[.08] px-4 py-2 text-[7px] font-black text-white/45">MI HISTORIA →</Link><Link to="/app/awards" className="rounded-full border border-amber-100/15 bg-amber-100/[.04] px-4 py-2 text-[7px] font-black text-amber-100/55">PR AWARDS →</Link></div></section></>}</main></AppLayout>}
function Locked(){return <section className="relative min-h-[540px] overflow-hidden rounded-[44px] border border-white/[.08] bg-[#08080b] p-6"><div className="absolute -right-24 -top-24 h-80 w-80 rounded-full bg-violet-500/[.12] blur-3xl"/><div className="relative flex min-h-[485px] flex-col justify-between"><div><p className="text-[7px] font-black tracking-[.28em] text-white/28">WRAPPED 2026 · LOCKED</p><h1 className="mt-10 text-[47px] font-black leading-[.88] tracking-[-.065em]">Tu año todavía<br/><span className="text-white/35">se está escribiendo.</span></h1><p className="mt-5 max-w-[470px] text-[10px] leading-5 text-white/28">Wrapped se desbloquea en diciembre. Hasta entonces seguimos sumando únicamente lo que realmente hacés dentro de Punta Rollers.</p></div><span className="text-[7px] font-black tracking-[.18em] text-violet-200/36">SEASON FINALE · DICIEMBRE</span></div></section>}
function Fresh(){return <section className="rounded-[40px] border border-white/[.08] bg-[#09090d] p-7 text-center"><p className="text-[7px] font-black tracking-[.22em] text-cyan-200/40">WRAPPED 2026</p><h1 className="mt-5 text-[36px] font-black tracking-[-.05em]">Tu historia recién empieza.</h1><p className="mx-auto mt-4 max-w-[430px] text-[10px] leading-5 text-white/28">Todavía no hay suficientes registros reales para construir un Wrapped que te represente. Preferimos decirte eso antes que rellenarlo con números inventados.</p><Link to="/app/historia" className="mt-6 inline-flex rounded-full border border-white/[.08] px-4 py-2 text-[7px] font-black text-white/45">VER MI HISTORIA →</Link></section>}
function Loading(){return <section className="grid min-h-[420px] place-items-center rounded-[40px] border border-white/[.07] bg-[#09090d] text-center"><div><div className="mx-auto h-10 w-10 animate-spin rounded-full border border-white/10 border-t-cyan-200"/><p className="mt-4 text-[8px] font-black tracking-[.18em] text-white/30">LEYENDO TU 2026…</p></div></section>}
function Big({v,l}){return <div className="rounded-[22px] border border-white/[.07] bg-white/[.02] p-4"><p className="text-[24px] font-black tracking-[-.04em]">{v}</p><p className="mt-2 text-[6px] font-black tracking-[.14em] text-white/20">{l}</p></div>}
function Card({v,t,d}){return <div className="rounded-[24px] border border-white/[.07] bg-[#0e0e12] p-5"><p className="text-[32px] font-black text-cyan-100/65">{v}</p><h3 className="mt-3 text-sm font-black">{t}</h3><p className="mt-2 text-[8px] leading-4 text-white/24">{d}</p></div>}
