import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'

const REFRESH_ID='pr-refresh-2026-09-v3'
const ONBOARDING_STEPS=[
 {icon:'⚡',eyebrow:'PUNTA ROLLERS SE RENOVÓ',title:'Tu PR ahora se siente más vivo.',text:'Reordenamos la plataforma para que encuentres más rápido lo que hacés, lo que entrenás y con quién rodás.',detail:'Abajo vas a ver siempre Inicio, Perfil, Rendimiento, Deberes, Comunidad y Mi PR.',accent:'from-orange-500/28 to-amber-300/5'},
 {icon:'👤',eyebrow:'TU NUEVO PERFIL',title:'Ahora tu perfil cuenta más de vos.',text:'Banner, bio, redes, amigos, logros, fotos, actividad reciente y tu identidad roller viven juntos.',detail:'Tu Círculo Roller, Mi Setup y Mi Momento hacen que tu perfil deje de sentirse como una ficha.',accent:'from-violet-500/24 to-fuchsia-400/7'},
 {icon:'🤝',eyebrow:'COMUNIDAD',title:'Ahora también es una red social.',text:'Podés publicar para tus amigos, subir fotos, etiquetar personas, reaccionar, comentar y crear álbumes colaborativos.',detail:'El badge de Comunidad te avisa solicitudes, mensajes, etiquetas, comentarios, reacciones e invitaciones.',accent:'from-cyan-500/18 to-violet-500/10'},
 {icon:'📈',eyebrow:'RENDIMIENTO + DEBERES',title:'Tu progreso quedó más claro.',text:'En Rendimiento están tus km, salidas, evolución y ranking. Deberes queda destacado para que no se pierda.',detail:'Strava sigue alimentando automáticamente estadísticas, RollerFeed y evolución.',accent:'from-violet-500/22 to-cyan-400/7'},
 {icon:'◆',eyebrow:'MI PR',title:'Tus herramientas tienen su propia casa.',text:'PR Card, PR Tracking, PR Music e Insignias están juntos dentro de Mi PR.',detail:'Próximamente empezaremos a entregar los nuevos chips PR Tracking.',accent:'from-emerald-500/18 to-amber-400/8'},
 {icon:'🛼',eyebrow:'LISTO',title:'Explorá. Personalizá. Hacelo tuyo.',text:'Esta actualización suma nuevas formas de mostrar tu mundo roller y compartirlo con tu círculo.',detail:'Este recorrido aparece como máximo dos veces y después deja de molestarte.',accent:'from-orange-500/24 to-violet-500/10'},
]
function storageKey(userId){return `${REFRESH_ID}:onboarding:${userId}`}
function readState(userId){try{return JSON.parse(localStorage.getItem(storageKey(userId))||'{"shows":0,"done":false}')}catch{return{shows:0,done:false}}}
function writeState(userId,state){try{localStorage.setItem(storageKey(userId),JSON.stringify(state))}catch{}}
function shouldShow(user){if(!user?.id)return false;const state=readState(user.id);return !state.done&&Number(state.shows||0)<2}
export default function LaunchExperience({user}){
 const navigate=useNavigate(),[open,setOpen]=useState(()=>shouldShow(user)),[step,setStep]=useState(0)
 const current=ONBOARDING_STEPS[step],isLast=step===ONBOARDING_STEPS.length-1,firstName=String(user?.nombre||'').trim().split(' ')[0]
 const progress=useMemo(()=>((step+1)/ONBOARDING_STEPS.length)*100,[step])
 useEffect(()=>{if(!open)return undefined;const prev=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=prev}},[open])
 useEffect(()=>{if(!user?.id)return;const show=shouldShow(user);if(show){const state=readState(user.id);writeState(user.id,{...state,shows:Number(state.shows||0)+1});setOpen(true);setStep(0)}else setOpen(false)},[user?.id])
 function complete(){if(user?.id)writeState(user.id,{shows:2,done:true});setOpen(false);navigate('/app/dashboard')}
 function later(){if(user?.id){const state=readState(user.id);writeState(user.id,{...state,done:Number(state.shows||0)>=2})}setOpen(false)}
 if(!open)return null
 return <div className="fixed inset-0 z-[180] overflow-y-auto bg-[#050508]/96 px-4 py-[max(18px,env(safe-area-inset-top))] backdrop-blur-2xl"><div className="mx-auto flex min-h-full w-full max-w-[470px] items-center"><section className="relative w-full overflow-hidden rounded-[38px] border border-orange-300/15 bg-gradient-to-br from-[#20140e] via-[#101016] to-[#08080c] p-6 shadow-[0_35px_110px_rgba(0,0,0,.72)]"><div className={`pointer-events-none absolute inset-0 bg-gradient-to-br ${current.accent} transition-all duration-500`}/><div className="relative"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><img src="/logo.png" alt="Punta Rollers" className="h-12 w-12 object-contain"/><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-white/30">NUEVA EXPERIENCIA PR</p><p className="mt-1 text-xs font-black text-white/75">{firstName?`Hola, ${firstName}`:'Punta Rollers'}</p></div></div><button type="button" onClick={later} className="rounded-full border border-white/10 bg-black/20 px-3 py-2 text-[8px] font-black text-white/35">AHORA NO</button></div><div><div className="mt-7 grid h-20 w-20 place-items-center rounded-[28px] border border-orange-200/20 bg-orange-400/10 text-4xl">{current.icon}</div><p className="mt-6 text-[9px] font-black uppercase tracking-[.22em] text-orange-300/75">{current.eyebrow}</p><h1 className="mt-2 font-display text-[36px] leading-[.98] text-white">{current.title}</h1><p className="mt-4 min-h-[92px] text-sm leading-6 text-white/52">{current.text}</p><div className="mt-4 rounded-[20px] border border-white/[.07] bg-black/20 px-4 py-3"><p className="text-[11px] leading-5 text-white/38">⚡ {current.detail}</p></div></div><div className="mt-6 h-1.5 overflow-hidden rounded-full bg-white/[.07]"><div className="h-full rounded-full bg-gradient-to-r from-orange-500 to-amber-200 transition-all duration-500" style={{width:`${progress}%`}}/></div><div className="mt-6 grid grid-cols-[auto_1fr] gap-2.5"><button type="button" disabled={step===0} onClick={()=>setStep(v=>Math.max(0,v-1))} className="grid min-h-14 w-14 place-items-center rounded-[20px] border border-white/10 bg-white/[.035] text-lg text-white/55 disabled:opacity-25">←</button><button type="button" onClick={()=>isLast?complete():setStep(v=>v+1)} className="flex min-h-14 items-center justify-between rounded-[20px] bg-gradient-to-r from-orange-500 to-amber-300 px-5 text-sm font-black text-black"><span>{isLast?'Entrar a mi PR':'Continuar'}</span><span>→</span></button></div><p className="mt-3 text-center text-[9px] text-white/24">Se muestra como máximo dos veces.</p></div></section></div></div>
}
