import {useState} from 'react'
const activities=['Equilibrio','Frenadas','Giros','Circuito con conos','Coordinación','Juego en equipo','Desplazamiento','Seguridad']
const initial={title:'',date:new Date().toISOString().slice(0,10),summary:'',teacherNote:'',skills:[]}
export default function PRKidsPublicationStudio(){
 const [draft,setDraft]=useState(initial),[preview,setPreview]=useState(false),[copied,setCopied]=useState(false)
 const change=(key,value)=>{setDraft(p=>({...p,[key]:value}));setCopied(false)}
 const toggle=skill=>change('skills',draft.skills.includes(skill)?draft.skills.filter(s=>s!==skill):[...draft.skills,skill])
 const valid=draft.title.trim().length>=4&&draft.summary.trim().length>=12&&draft.date
 const summary=()=>['PR KIDS · BORRADOR INTERNO',draft.date,draft.title.trim(),'','ACTIVIDAD',draft.summary.trim(),'','HABILIDADES',draft.skills.join(', ')||'Sin seleccionar','','MENSAJE PARA FAMILIAS',draft.teacherNote.trim()||'Sin mensaje'].join('\n')
 return <section className="mt-8 rounded-3xl border border-sky-300/20 bg-gradient-to-br from-slate-900 to-[#17162c] p-5 text-white shadow-xl sm:p-7" aria-label="Estudio de publicaciones PR Kids">
 <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black tracking-[.18em] text-sky-300">PR KIDS · ESTUDIO DE CLASES</p><h2 className="mt-2 text-2xl font-black">Preparar una publicación</h2></div><span className="rounded-full border border-amber-300/30 bg-amber-300/10 px-3 py-2 text-xs font-bold text-amber-200">SOLO BORRADOR · NO PUBLICA</span></div>
 <p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Armá un resumen de clase para revisarlo antes de compartirlo. Esta herramienta no guarda datos en el servidor ni envía información a las familias.</p>
 <div className="mt-6 grid gap-5 md:grid-cols-2"><div><label htmlFor="prk-studio-title" className="mb-2 block text-sm font-bold">Título de la clase</label><input id="prk-studio-title" maxLength={80} value={draft.title} onChange={e=>change('title',e.target.value)} placeholder="Ej.: Aprendimos a frenar" className="w-full rounded-xl border border-white/20 bg-black/30 p-3 text-white"/></div><div><label htmlFor="prk-studio-date" className="mb-2 block text-sm font-bold">Fecha de la clase</label><input id="prk-studio-date" type="date" value={draft.date} onChange={e=>change('date',e.target.value)} className="w-full rounded-xl border border-white/20 bg-black/30 p-3 text-white"/></div></div>
 <label htmlFor="prk-studio-summary" className="mt-5 block text-sm font-bold">¿Qué practicamos?</label><textarea id="prk-studio-summary" rows={4} maxLength={1000} value={draft.summary} onChange={e=>change('summary',e.target.value)} placeholder="Describí los ejercicios, el objetivo y cómo trabajó el grupo." className="mt-2 w-full rounded-xl border border-white/20 bg-black/30 p-3 text-white"/>
 <p className="mt-5 text-sm font-bold">Habilidades trabajadas</p><div className="mt-3 flex flex-wrap gap-2">{activities.map(skill=><button key={skill} type="button" aria-pressed={draft.skills.includes(skill)} onClick={()=>toggle(skill)} className={'rounded-full border px-3 py-2 text-xs font-bold '+(draft.skills.includes(skill)?'border-sky-300 bg-sky-300/20 text-sky-100':'border-white/20 text-slate-300')}>{draft.skills.includes(skill)?'✓ ': '+ '}{skill}</button>)}</div>
 <label htmlFor="prk-studio-note" className="mt-5 block text-sm font-bold">Mensaje del profesor (opcional)</label><textarea id="prk-studio-note" rows={3} maxLength={500} value={draft.teacherNote} onChange={e=>change('teacherNote',e.target.value)} placeholder="Un mensaje cálido para las familias…" className="mt-2 w-full rounded-xl border border-white/20 bg-black/30 p-3 text-white"/>
 <div className="mt-6 flex flex-wrap gap-3"><button type="button" disabled={!valid} onClick={()=>setPreview(true)} className="rounded-xl bg-sky-400 px-5 py-3 text-sm font-black text-slate-950 disabled:opacity-40">Vista previa de la publicación →</button><button type="button" onClick={()=>{setDraft(initial);setPreview(false);setCopied(false)}} className="rounded-xl border border-white/20 px-5 py-3 text-sm font-bold">Limpiar borrador</button></div>
 {preview&&valid&&<div className="mt-6 rounded-2xl border border-violet-300/30 bg-black/25 p-5" role="region" aria-label="Vista previa del borrador"><p className="text-xs font-black tracking-widest text-violet-200">VISTA PREVIA · NO PUBLICADA</p><p className="mt-3 text-xs text-slate-400">{draft.date}</p><h3 className="mt-1 text-xl font-black">{draft.title}</h3><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-200">{draft.summary}</p>{draft.skills.length>0&&<div className="mt-4 flex flex-wrap gap-2">{draft.skills.map(s=><span key={s} className="rounded-full bg-violet-400/20 px-3 py-1 text-xs text-violet-100">{s}</span>)}</div>}{draft.teacherNote&&<p className="mt-4 border-l-2 border-amber-300 pl-3 text-sm italic text-amber-100">{draft.teacherNote}</p>}<button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(summary());setCopied(true)}catch{setCopied(false)}}} className="mt-5 rounded-xl border border-sky-300/40 px-4 py-2 text-xs font-black text-sky-200">{copied?'✓ Copiado':'Copiar borrador para revisión'}</button></div>}
 </section>
}
