import {useState} from 'react'
import {filterClassPosts,formatClassDate} from '../lib/prKidsClassPosts'
import './PRKidsFamilyDashboard.css'
const sampleSaturdays=[{date:'2026-10-03',title:'Equilibrio y frenadas',detail:'Circuito de conos, postura de seguridad y frenada controlada.',skills:['Equilibrio','Frenada en T'],teacher:'Claudio',note:'¡Muy buen trabajo en equipo!',avatar:null},{date:'2026-09-26',title:'Primeros giros',detail:'Giros amplios, coordinación y desplazamiento seguro.',skills:['Giros','Coordinación'],teacher:'David',note:'Seguimos practicando con confianza.',avatar:null}]


const sample={
 clases:[{date:'SÁBADO · CLASE DE EJEMPLO',title:'Equilibrio y frenadas',detail:'Circuito de conos, postura de seguridad y frenada controlada.',teacher:'Mensaje de ejemplo: ¡Muy buen trabajo en equipo!'},{date:'MIÉRCOLES · CLASE DE EJEMPLO',title:'Primeros giros',detail:'Giros amplios, coordinación y desplazamiento seguro.',teacher:'Mensaje de ejemplo: Seguimos practicando con confianza.'}],
 skills:[{name:'Equilibrio',detail:'Mantener postura y estabilidad',done:true},{name:'Primeros giros',detail:'Control de dirección',done:true},{name:'Frenada en T',detail:'Aprender a detenerse con seguridad',done:false},{name:'Trabajo en equipo',detail:'Compartir el circuito',done:true}],
 attendanceStamps:6
}
const tabs=[['clases','Qué hicimos hoy'],['pasaporte','Pasaporte'],['logros','Mis logros'],['recuerdos','Recuerdos']]
export default function PRKidsFamilyDashboard({child,demo=false,onBack}){
 const [tab,setTab]=useState('clases')
 const [showTeacher,setShowTeacher]=useState(true)
 const [historySearch,setHistorySearch]=useState(''),[historyDate,setHistoryDate]=useState('all')
 const visibleSaturdays=demo?filterClassPosts(sampleSaturdays,{date:historyDate,query:historySearch}):[]
 // Never interpret an unverified child-profile field as a scanner attendance record.
 const attendanceCount=demo?3:0
 const stampSlots=demo?6:0
 const childPhoto=child.foto_url||child.photo_url||child.avatar_url||null
 return <section className="prk-dashboard" aria-label={'Perfil infantil de '+child.nombre}>
  <div className="prk-dashboard-top"><button type="button" className="prk-dashboard-back" onClick={onBack}>← Mi familia</button><span className="prk-dashboard-chip">{demo?'VISTA DEMO · FICTICIA':'PERFIL PRIVADO'}</span></div>
  <div className="prk-dashboard-hero"><div className="prk-dashboard-avatar" aria-label="Foto de perfil infantil">{childPhoto?<img src={childPhoto} alt={'Foto de '+child.nombre}/>:<span>{String(child.nombre||'?').trim()[0]?.toUpperCase()}</span>}</div><div><p className="prk-dashboard-eyebrow">MI AVENTURA SOBRE RUEDAS</p><h2>{child.nombre}</h2><p>{demo?'Un ejemplo de cómo la familia acompañará cada avance.':'Mi espacio familiar de PR Kids.'}</p></div></div>
  {demo&&<div className="prk-dashboard-stats"><div><strong>2</strong><span>Clases de ejemplo</span></div><div><strong>3</strong><span>Logros de ejemplo</span></div><div><strong>3</strong><span>Sellos de asistencia · ejemplo</span></div></div>}
  <div className="prk-dashboard-tabs" role="tablist" aria-label="Secciones del perfil infantil">{tabs.map(([id,name])=><button key={id} type="button" role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}>{name}</button>)}</div>
  <div className="prk-dashboard-panel" role="tabpanel">
  {tab==='clases'&&<><h3>Qué hicimos hoy</h3><p className="prk-dashboard-muted">Un resumen para que las familias conozcan lo que se practica en clase.</p>{demo&&<div className="mb-4 grid gap-2 sm:grid-cols-2"><label className="text-xs font-bold text-slate-300">Buscar clases<input value={historySearch} onChange={e=>setHistorySearch(e.target.value)} placeholder="Actividad o habilidad…" className="mt-2 w-full rounded-xl border border-white/20 bg-black/30 p-3 text-white"/></label><label className="text-xs font-bold text-slate-300">Elegir sábado<select value={historyDate} onChange={e=>setHistoryDate(e.target.value)} className="mt-2 w-full rounded-xl border border-white/20 bg-slate-900 p-3 text-white"><option value="all">Todos los sábados</option>{sampleSaturdays.map(c=><option key={c.date} value={c.date}>{formatClassDate(c.date)}</option>)}</select></label></div>}{demo?(visibleSaturdays.length?visibleSaturdays.map(c=><article key={c.date} className="prk-dashboard-entry"><span>{formatClassDate(c.date).toUpperCase()} · EJEMPLO</span><h4>{c.title}</h4><p>{c.detail}</p><div className="mt-3 flex flex-wrap gap-2">{c.skills.map(skill=><span key={skill} className="rounded-full bg-violet-500/20 px-3 py-1 text-xs font-bold text-violet-100">{skill}</span>)}</div><div className="mt-4 flex items-center gap-3">{c.avatar?<img src={c.avatar} alt="" className="h-10 w-10 rounded-full object-cover"/>:<span className="grid h-10 w-10 place-items-center rounded-full bg-violet-700 font-black">{c.teacher[0]}</span>}<div><strong className="block text-xs">{c.teacher} · Ejemplo</strong><span className="rounded-full border border-sky-300/30 px-2 py-1 text-[10px] font-black text-sky-200">PROFESOR</span></div></div>{showTeacher&&<div className="prk-dashboard-teacher">Mensaje de ejemplo: {c.note}</div>}</article>):<p className="prk-dashboard-empty">No hay clases de ejemplo que coincidan con la búsqueda.</p>):<p className="prk-dashboard-empty">Todavía no hay clases publicadas para este perfil.</p>}{demo&&<button type="button" className="prk-dashboard-secondary" onClick={()=>setShowTeacher(v=>!v)}>{showTeacher?'Ocultar':'Mostrar'} mensajes de ejemplo</button>}</>}
  {tab==='pasaporte'&&<><h3>Mi pasaporte roller</h3><p className="prk-dashboard-muted">Cada asistencia confirmada por el equipo mediante el escáner suma un sello. Acumulá sellos para canjearlos por premios.</p><div className="prk-passport-summary"><div><span>SELLOS ACUMULADOS</span><strong>{attendanceCount}</strong><small>{demo?'Cantidad ficticia de ejemplo':'Según asistencias confirmadas'}</small></div><div><span>SELLOS DISPONIBLES</span><strong>{attendanceCount}</strong><small>{demo?'Sin canjes en esta demostración':'Pendiente de conectar con el registro de asistencias y canjes'}</small></div></div>{demo&&<div className="prk-dashboard-progress" aria-label={attendanceCount+' sellos ilustrativos de '+stampSlots+' espacios'}><div style={{width:(Math.min(1,attendanceCount/stampSlots)*100)+'%'}}/></div>}<div className="prk-dashboard-stamps">{Array.from({length:stampSlots},(_,i)=><div key={i} className={'prk-dashboard-stamp '+(i<attendanceCount?'is-earned':'is-pending')} aria-label={i<attendanceCount?'Sello de asistencia '+(i+1):'Espacio para próxima asistencia'}><div className="prk-stamp-mark"><img src="/pr-kids-attendance-seal.svg" alt="" loading="lazy" /></div></div>)}</div>{!demo&&<div className="prk-dashboard-empty" role="status">El pasaporte de asistencias todavía no está conectado al escáner. No se muestran sellos reales hasta validar esa integración.</div>}<p className="prk-passport-footnote">{demo?'DEMOSTRACIÓN: los 3 sellos no representan asistencias reales.':'Los sellos reales se mostrarán cuando esté conectada y verificada la sincronización con el escáner de asistencia.'} Los canjes de premios tendrán sus propias reglas y registro.</p></>}
  {tab==='logros'&&<><h3>Mis logros</h3><p className="prk-dashboard-muted">Insignias asociadas a habilidades verificadas por el equipo de PR Kids.</p><div className="prk-dashboard-skills">{sample.skills.map((skill,i)=><div key={skill.name} className={'prk-dashboard-skill '+(demo&&skill.done?'is-earned':'')}><span aria-hidden="true">{demo&&skill.done?'✦':'◇'}</span><div><strong>{skill.name}</strong><small>{skill.detail}</small></div><em>{demo&&skill.done?'Ejemplo conseguido':demo?'Por conseguir':'Sin registrar'}</em></div>)}</div></>}
  {tab==='recuerdos'&&<><h3>Mis recuerdos</h3><p className="prk-dashboard-muted">Un álbum privado. Solo aparecerán fotografías y videos autorizados y publicados para esta familia.</p><div className="prk-dashboard-gallery"><div><span aria-hidden="true">▧</span><strong>Momentos de clase</strong><small>{demo?'Espacio de foto ficticio':'Sin fotos publicadas'}</small></div><div><span aria-hidden="true">▷</span><strong>Videos de progreso</strong><small>{demo?'Espacio de video ficticio':'Sin videos publicados'}</small></div></div></>}
  </div>
  {demo&&<p className="prk-dashboard-disclaimer">DEMOSTRACIÓN · Todos los nombres, actividades, sellos y logros son ficticios. No se muestran datos de alumnos reales.</p>}
 </section>
}
