import {useEffect,useState} from 'react'
import {useAuth} from '../lib/auth'
const activities=['Equilibrio','Frenadas','Giros','Circuito con conos','Coordinación','Juego en equipo','Desplazamiento','Seguridad']
const initial={title:'',date:new Date().toISOString().slice(0,10),summary:'',teacherNote:'',skills:[]}
const formatDate=date=>new Date(date+'T12:00:00').toLocaleDateString('es-UY',{weekday:'long',day:'numeric',month:'long',year:'numeric'})
export default function PRKidsPublicationStudio(){
 const {user}=useAuth()
 const [draft,setDraft]=useState(initial),[preview,setPreview]=useState(false),[copied,setCopied]=useState(false)
 const [customSkill,setCustomSkill]=useState(''),[photos,setPhotos]=useState([]),[blocks,setBlocks]=useState([])
 const teacherName=[user?.nombre,user?.apellido].filter(Boolean).join(' ')||'Profesor/a'
 const teacherAvatar=user?.foto_url||user?.avatar_url||user?.foto||null
 useEffect(()=>()=>{photos.forEach(p=>URL.revokeObjectURL(p.url))},[photos])
 const addSkill=()=>{const value=customSkill.trim().slice(0,60);if(value&&!draft.skills.some(s=>s.toLowerCase()===value.toLowerCase()))change('skills',[...draft.skills,value]);setCustomSkill('')}
 const addPhotos=files=>{const allowed=Array.from(files||[]).filter(file=>file.type.startsWith('image/')&&file.size<=8*1024*1024);setPhotos(prev=>[...prev,...allowed.slice(0,Math.max(0,8-prev.length)).map(file=>({name:file.name,url:URL.createObjectURL(file)}))])}
 const removePhoto=index=>setPhotos(prev=>{URL.revokeObjectURL(prev[index].url);return prev.filter((_,i)=>i!==index)})
 const addPreviewBlock=()=>{if(!valid)return;setBlocks(prev=>[{...draft,id:Date.now(),teacherName,teacherAvatar,photos:[...photos]},...prev].sort((a,b)=>b.date.localeCompare(a.date)));setPreview(false);setDraft(initial);setPhotos([])}
 const change=(key,value)=>{setDraft(p=>({...p,[key]:value}));setCopied(false)}
 const toggle=skill=>change('skills',draft.skills.includes(skill)?draft.skills.filter(s=>s!==skill):[...draft.skills,skill])
 const valid=draft.title.trim().length>=4&&draft.summary.trim().length>=12&&draft.date
 const summary=()=>['PR KIDS · BORRADOR INTERNO',draft.date,draft.title.trim(),'','ACTIVIDAD',draft.summary.trim(),'','HABILIDADES',draft.skills.join(', ')||'Sin seleccionar','','MENSAJE PARA FAMILIAS',draft.teacherNote.trim()||'Sin mensaje','',`DOCENTE: ${teacherName}`,`FOTOS SELECCIONADAS: ${photos.length} (no incluidas en el texto)`].join('\n')
 return <section className="mt-8 rounded-3xl border border-sky-300/20 bg-gradient-to-br from-slate-900 to-[#17162c] p-5 text-white shadow-xl sm:p-7" aria-label="Estudio de publicaciones PR Kids">
 <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black tracking-[.18em] text-sky-300">PR KIDS · ESTUDIO DE CLASES</p><h2 className="mt-2 text-2xl font-black">Preparar una publicación</h2></div><span className="rounded-full border border-amber-300/30 bg-amber-300/10 px-3 py-2 text-xs font-bold text-amber-200">SOLO BORRADOR · NO PUBLICA</span></div>
 <p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Prepará publicaciones por fecha, con fotos, habilidades y firma del profesor. Por ahora todo es una demostración local: los bloques se pierden al recargar y nada llega a las familias.</p>
 <div className="mt-6 grid gap-5 md:grid-cols-2"><div><label htmlFor="prk-studio-title" className="mb-2 block text-sm font-bold">Título de la clase</label><input id="prk-studio-title" maxLength={80} value={draft.title} onChange={e=>change('title',e.target.value)} placeholder="Ej.: Aprendimos a frenar" className="w-full rounded-xl border border-white/20 bg-black/30 p-3 text-white"/></div><div><label htmlFor="prk-studio-date" className="mb-2 block text-sm font-bold">Fecha de la clase</label><input id="prk-studio-date" type="date" value={draft.date} onChange={e=>change('date',e.target.value)} className="w-full rounded-xl border border-white/20 bg-black/30 p-3 text-white"/></div></div>
 <label htmlFor="prk-studio-summary" className="mt-5 block text-sm font-bold">¿Qué practicamos?</label><textarea id="prk-studio-summary" rows={4} maxLength={1000} value={draft.summary} onChange={e=>change('summary',e.target.value)} placeholder="Describí los ejercicios, el objetivo y cómo trabajó el grupo." className="mt-2 w-full rounded-xl border border-white/20 bg-black/30 p-3 text-white"/>
 <p className="mt-5 text-sm font-bold">Habilidades trabajadas</p><div className="mt-3 flex flex-wrap gap-2">{activities.map(skill=><button key={skill} type="button" aria-pressed={draft.skills.includes(skill)} onClick={()=>toggle(skill)} className={'rounded-full border px-3 py-2 text-xs font-bold '+(draft.skills.includes(skill)?'border-sky-300 bg-sky-300/20 text-sky-100':'border-white/20 text-slate-300')}>{draft.skills.includes(skill)?'✓ ': '+ '}{skill}</button>)}</div>
 <div className="mt-5 flex flex-wrap items-end gap-3"><label className="flex-1 text-sm font-bold">Otra habilidad trabajada<input value={customSkill} onChange={e=>setCustomSkill(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addSkill()}}} maxLength={60} placeholder="Ej.: frenada en taco" className="mt-2 w-full rounded-xl border border-white/20 bg-black/30 p-3 text-white"/></label><button type="button" onClick={addSkill} disabled={!customSkill.trim()} className="rounded-xl border border-sky-300/40 px-4 py-3 text-sm font-bold disabled:opacity-40">+ Agregar habilidad</button></div>
 <div className="mt-5 rounded-2xl border border-white/15 p-4"><div className="flex items-center gap-3">{teacherAvatar?<img src={teacherAvatar} alt="" className="h-11 w-11 rounded-full object-cover"/>:<span className="grid h-11 w-11 place-items-center rounded-full bg-violet-600 text-lg font-black">{teacherName[0]}</span>}<div><p className="text-sm font-black">{teacherName}</p><span className="inline-block rounded-full border border-sky-300/30 px-2 py-1 text-[10px] font-black tracking-wider text-sky-200">PROFESOR</span></div></div><p className="mt-2 text-xs text-slate-400">La foto se muestra si está disponible en tu perfil; nunca se inventa una imagen de Claudio o David.</p></div>
 <div className="mt-5"><label htmlFor="prk-studio-photos" className="block text-sm font-bold">Fotos de la clase (hasta 8, máximo 8 MB cada una)</label><input id="prk-studio-photos" type="file" accept="image/*" multiple onChange={e=>{addPhotos(e.target.files);e.target.value=''}} className="mt-2 block w-full rounded-xl border border-white/20 bg-black/30 p-3 text-xs text-white"/><p className="mt-2 text-xs text-amber-200">Las imágenes son solo previsualizaciones locales: todavía no se suben ni quedan guardadas. Cargá únicamente fotos autorizadas.</p>{photos.length>0&&<div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4">{photos.map((photo,i)=><div key={photo.url} className="relative"><img src={photo.url} alt={'Foto seleccionada '+(i+1)} className="h-28 w-full rounded-xl object-cover"/><button type="button" onClick={()=>removePhoto(i)} aria-label={'Quitar foto '+(i+1)} className="absolute right-1 top-1 rounded-full bg-black/80 px-2 py-1 text-xs">✕</button></div>)}</div>}</div>
 <label htmlFor="prk-studio-note" className="mt-5 block text-sm font-bold">Mensaje del profesor (opcional)</label><textarea id="prk-studio-note" rows={3} maxLength={500} value={draft.teacherNote} onChange={e=>change('teacherNote',e.target.value)} placeholder="Un mensaje cálido para las familias…" className="mt-2 w-full rounded-xl border border-white/20 bg-black/30 p-3 text-white"/>
 <div className="mt-6 flex flex-wrap gap-3"><button type="button" disabled={!valid} onClick={()=>setPreview(true)} className="rounded-xl bg-sky-400 px-5 py-3 text-sm font-black text-slate-950 disabled:opacity-40">Vista previa de la publicación →</button><button type="button" onClick={()=>{setDraft(initial);setPreview(false);setCopied(false)}} className="rounded-xl border border-white/20 px-5 py-3 text-sm font-bold">Limpiar borrador</button></div>
 {preview&&valid&&<div className="mt-6 rounded-2xl border border-violet-300/30 bg-black/25 p-5" role="region" aria-label="Vista previa del borrador"><p className="text-xs font-black tracking-widest text-violet-200">VISTA PREVIA · NO PUBLICADA</p><p className="mt-3 text-xs text-slate-400">{draft.date}</p><h3 className="mt-1 text-xl font-black">{draft.title}</h3><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-200">{draft.summary}</p>{draft.skills.length>0&&<div className="mt-4 flex flex-wrap gap-2">{draft.skills.map(s=><span key={s} className="rounded-full bg-violet-400/20 px-3 py-1 text-xs text-violet-100">{s}</span>)}</div>}{draft.teacherNote&&<p className="mt-4 border-l-2 border-amber-300 pl-3 text-sm italic text-amber-100">{draft.teacherNote}</p>}<div className="mt-4 flex items-center gap-2">{teacherAvatar?<img src={teacherAvatar} alt="" className="h-9 w-9 rounded-full object-cover"/>:<span className="grid h-9 w-9 place-items-center rounded-full bg-violet-600 font-bold">{teacherName[0]}</span>}<strong className="text-xs">{teacherName} · PROFESOR</strong></div>{photos.length>0&&<div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{photos.map(photo=><img key={photo.url} src={photo.url} alt="Vista previa de clase" className="h-28 w-full rounded-xl object-cover"/>)}</div>}<button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(summary());setCopied(true)}catch{setCopied(false)}}} className="mt-5 rounded-xl border border-sky-300/40 px-4 py-2 text-xs font-black text-sky-200">{copied?'✓ Copiado':'Copiar borrador para revisión'}</button><button type="button" onClick={addPreviewBlock} className="ml-2 mt-3 rounded-xl bg-violet-500 px-4 py-3 text-xs font-black">Añadir al historial de esta demo</button></div>}
 <div className="mt-8 border-t border-white/15 pt-6"><h3 className="text-xl font-black">Historial por sábados</h3><p className="mt-2 text-xs text-amber-200">Historial temporal de demostración. No persiste al recargar ni es visible para familias.</p>{blocks.length===0?<p className="mt-4 rounded-xl border border-dashed border-white/20 p-5 text-sm text-slate-400">Creá una publicación de prueba para ver cómo se acumulan los bloques por fecha.</p>:blocks.map(block=><article key={block.id} className="mt-4 rounded-2xl border border-white/15 bg-white/5 p-4"><p className="text-xs font-black uppercase tracking-wider text-sky-200">{formatDate(block.date)}</p><h4 className="mt-2 text-lg font-black">{block.title}</h4><p className="mt-2 whitespace-pre-wrap text-sm text-slate-300">{block.summary}</p><div className="mt-3 flex flex-wrap gap-2">{block.skills.map(skill=><span key={skill} className="rounded-full bg-violet-400/20 px-3 py-1 text-xs">{skill}</span>)}</div>{block.photos.length>0&&<div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{block.photos.map(photo=><img key={photo.url} src={photo.url} alt="Foto del bloque de clase" className="h-28 w-full rounded-xl object-cover"/>)}</div>}<div className="mt-4 flex items-center gap-2">{block.teacherAvatar?<img src={block.teacherAvatar} alt="" className="h-9 w-9 rounded-full object-cover"/>:<span className="grid h-9 w-9 place-items-center rounded-full bg-violet-600 font-black">{block.teacherName[0]}</span>}<div><strong className="block text-xs">{block.teacherName}</strong><span className="text-[10px] font-black text-sky-200">PROFESOR</span></div></div>{block.teacherNote&&<p className="mt-3 text-sm italic text-slate-300">{block.teacherNote}</p>}</article>)}</div>
 </section>
}
