import { useState } from 'react'
const CATS=['Asistencia de Acero','Mejor Compañero/a','La Radio PR','Premio Piso Conocido','Superación 2026','Espíritu Punta Rollers']
export default function AwardsParticipationBeta(){
 const[selected,setSelected]=useState('');const[suggestion,setSuggestion]=useState('');const[voted,setVoted]=useState(false);const[sent,setSent]=useState(false)
 return <section className="rounded-[28px] border border-amber-200/15 bg-amber-200/[.035] p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[8px] font-black tracking-[.2em] text-amber-100/50">VOTACIÓN · PREVIEW</p><h2 className="mt-2 text-xl font-black">Probamos la experiencia antes de diciembre.</h2></div><span className="rounded-full border border-white/10 px-3 py-1 text-[7px] font-black text-white/25">NO GUARDA VOTOS</span></div><p className="mt-2 text-[9px] leading-4 text-white/30">La votación final será privada. Esta beta sirve para validar claridad, navegación y tono sin registrar decisiones reales.</p>
 <div className="mt-4 grid gap-2 sm:grid-cols-2">{CATS.map(c=><button key={c} onClick={()=>{setSelected(c);setVoted(false)}} className={'rounded-[17px] border p-3 text-left text-[9px] font-black '+(selected===c?'border-amber-200/25 bg-amber-200/[.08] text-amber-100':'border-white/[.07] bg-black/15 text-white/38')}>{selected===c?'● ':'○ '}{c}</button>)}</div>
 <button disabled={!selected} onClick={()=>setVoted(true)} className="mt-3 w-full rounded-[16px] bg-amber-200 px-4 py-3 text-[9px] font-black text-black disabled:opacity-25">{voted?'VOTO DE PRUEBA ✓':'PROBAR VOTO PRIVADO'}</button>
 <div className="mt-5 border-t border-white/[.06] pt-5"><p className="text-[8px] font-black tracking-[.15em] text-white/30">PROPONER UNA CATEGORÍA</p><div className="mt-2 flex gap-2"><input value={suggestion} onChange={e=>{setSuggestion(e.target.value.slice(0,80));setSent(false)}} placeholder="Ej. La mejor energía del grupo" className="min-w-0 flex-1 rounded-[15px] border border-white/[.08] bg-black/20 px-3 py-3 text-[10px] outline-none placeholder:text-white/18"/><button disabled={!suggestion.trim()} onClick={()=>setSent(true)} className="rounded-[15px] border border-white/10 px-4 text-[8px] font-black text-white/55 disabled:opacity-25">PROBAR</button></div>{sent&&<p className="mt-2 text-[8px] text-white/25">Sugerencia simulada en beta. No fue enviada ni guardada.</p>}</div>
 </section>
}