import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../../lib/supabase'
import NewStudentWelcome from '../onboarding/NewStudentWelcome'
const EVENT='shifter-marathon-2026'
const LEVELS=[{n:1,name:'Punto de partida',min:0},{n:2,name:'En movimiento',min:50},{n:3,name:'Constancia',min:150},{n:4,name:'Rodaje',min:300},{n:5,name:'Impulso',min:500},{n:6,name:'Dominio',min:800},{n:7,name:'Referente PR',min:1200}]
function monthStart(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-01T00:00:00'}
export default function DashboardLiveStats({user}){
 const[data,setData]=useState({loading:true,monthKm:null,sessions:null,allKm:0,allSessions:0,goals:0,takes:0,milestones:0,shifter:null,strava:false,newStudent:false})
 useEffect(()=>{let alive=true;(async()=>{if(!user?.id){setData(x=>({...x,loading:false}));return}
  const[p,a,all,s,e,g,t,h]=await Promise.all([
   supabase.from('profiles').select('miembro_desde,created_at').eq('id',user.id).maybeSingle(),
   supabase.from('pr_inline_skate_activities').select('id,distancia_metros,fecha_inicio').eq('alumno_id',user.id).eq('fuente','strava').eq('eliminada',false).gte('fecha_inicio',monthStart()).limit(1000),
   supabase.from('pr_inline_skate_activities').select('id,distancia_metros').eq('alumno_id',user.id).eq('fuente','strava').eq('eliminada',false).limit(3000),
   supabase.from('pr_strava_connections').select('conectado').eq('alumno_id',user.id).maybeSingle(),
   supabase.from('pr_training_enrollments').select('category,active').eq('profile_id',user.id).eq('event_slug',EVENT).maybeSingle(),
   supabase.from('pr_performance_objetivos').select('id,estado').eq('alumno_id',user.id).eq('eliminado',false),
   supabase.from('pr_performance_tomas_calculadas').select('id').eq('alumno_id',user.id).limit(500),
   supabase.from('actividad_pr').select('id,tipo').eq('alumno_id',user.id).eq('tipo','Insignia').or('eliminado.is.null,eliminado.eq.false').limit(500)
  ]);if(!alive)return
  const acts=a.data||[],allActs=all.data||[];let shifter=null
  if(e.data?.category&&e.data.category!=='NO'){const[tt,r]=await Promise.all([supabase.from('pr_training_tasks').select('id,category').eq('event_slug',EVENT).eq('active',true),supabase.from('pr_training_task_results').select('task_id,status').eq('profile_id',user.id)]);const tasks=(tt.data||[]).filter(x=>x.category==='ALL'||x.category===e.data.category),done=new Set((r.data||[]).filter(x=>x.status==='completed').map(x=>x.task_id));shifter={completed:tasks.filter(x=>done.has(x.id)).length,total:tasks.length}}
  const memberDate=p.data?.miembro_desde||p.data?.created_at,ageDays=memberDate?Math.floor((Date.now()-new Date(memberDate).getTime())/86400000):null
  setData({loading:false,monthKm:acts.reduce((n,x)=>n+(Number(x.distancia_metros)||0)/1000,0),sessions:acts.length,allKm:allActs.reduce((n,x)=>n+(Number(x.distancia_metros)||0)/1000,0),allSessions:allActs.length,goals:(g.data||[]).filter(x=>String(x.estado).toLowerCase()==='completado').length,takes:(t.data||[]).length,milestones:(h.data||[]).length,shifter,strava:Boolean(s.data?.conectado)||allActs.length>0,newStudent:(ageDays!==null&&ageDays<45)||(allActs.length===0&&!shifter)})
 })().catch(()=>alive&&setData(x=>({...x,loading:false})));return()=>{alive=false}},[user?.id])
 const evolution=useMemo(()=>{const score=Math.round(Math.min(1500,data.allKm*.7+data.allSessions*4+data.goals*25+data.milestones*20+data.takes*5)),level=[...LEVELS].reverse().find(x=>score>=x.min)||LEVELS[0],next=LEVELS.find(x=>x.n===level.n+1),progress=next?Math.max(0,Math.min(100,((score-level.min)/(next.min-level.min))*100)):100;return{score,level,next,progress}},[data])
 const cards=[['KM ESTE MES',data.loading?'—':data.monthKm===null?'—':data.monthKm.toLocaleString('es-UY',{maximumFractionDigits:1}),data.strava?'Desde Strava':'Conectá Strava','/app/perfil'],['ENTRENOS',data.loading?'—':data.sessions??'—','Actividades de este mes','/app/rollerfeed'],['SHIFTER',data.loading?'—':data.shifter?data.shifter.completed+'/'+data.shifter.total:'—',data.shifter?'Tu capítulo guardado':'Sin participación',data.shifter?'/app/historia/shifter-2026':'/app/mi-pr']]
 return <><NewStudentWelcome show={!data.loading&&data.newStudent}/><section className="grid grid-cols-3 gap-2">{cards.map(([k,v,s,to])=><Link key={k} to={to} className="rounded-[22px] border border-white/[.07] bg-white/[.025] p-4"><p className="text-[7px] font-black tracking-[.13em] text-white/30">{k}</p><p className="mt-3 text-xl font-black tracking-tight">{v}</p><p className="mt-1 text-[8px] leading-3 text-white/30">{s}</p></Link>)}</section>
 <Link to="/app/evolucion" className="block overflow-hidden rounded-[25px] border border-violet-300/15 bg-gradient-to-r from-violet-400/[.07] via-white/[.02] to-cyan-300/[.05] p-4"><div className="flex items-center justify-between gap-4"><div><p className="text-[7px] font-black tracking-[.18em] text-violet-200/60">EVOLUCIÓN 2.0 · NIVEL {data.loading?'—':evolution.level.n}</p><h3 className="mt-1 text-sm font-black">{data.loading?'Leyendo tu historia…':evolution.level.name}</h3></div><span className="text-violet-200/60">→</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-gradient-to-r from-violet-400 to-cyan-300" style={{width:(data.loading?0:evolution.progress)+'%'}}/></div><div className="mt-2 flex justify-between text-[7px] font-black text-white/20"><span>{data.loading?'—':evolution.score+' PR'}</span><span>{evolution.next?'SIGUIENTE · '+evolution.next.name.toUpperCase():'RECORRIDO ACTUAL COMPLETO'}</span></div></Link>
 <section className="grid grid-cols-3 gap-2"><Link to="/app/tareas" className="rounded-[20px] border border-violet-300/12 bg-violet-300/[.04] p-4"><p className="text-[8px] font-black text-violet-200/60">TAREAS</p><p className="mt-2 text-[9px] text-white/30">Entrenamiento y objetivos →</p></Link><Link to="/app/asistencia" className="rounded-[20px] border border-cyan-300/12 bg-cyan-300/[.04] p-4"><p className="text-[8px] font-black text-cyan-200/60">PR CHECK</p><p className="mt-2 text-[9px] text-white/30">Asistencia e ID →</p></Link><Link to="/app/mi-pr" className="rounded-[20px] border border-white/[.07] bg-white/[.025] p-4"><p className="text-[8px] font-black text-white/35">MI PR</p><p className="mt-2 text-[9px] text-white/30">Identidad e historia →</p></Link></section></>
}