import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../../lib/supabase'
import NewStudentWelcome from '../onboarding/NewStudentWelcome'
import { calculatePRProgression, PR_PROGRESSION_IS_BETA } from '../../lib/prProgression'
function monthStart(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-01T00:00:00'}
export default function DashboardLiveStats({user}){
 const[data,setData]=useState({loading:true,monthKm:null,sessions:null,allKm:0,allSessions:0,goals:0,takes:0,milestones:0,historyEvents:0,strava:false,newStudent:false})
 useEffect(()=>{let alive=true;(async()=>{if(!user?.id){setData(x=>({...x,loading:false}));return}
  const[p,a,all,s,g,t,h,v]=await Promise.all([
   supabase.from('profiles').select('miembro_desde,created_at').eq('id',user.id).maybeSingle(),supabase.from('pr_inline_skate_activities').select('id,distancia_metros,fecha_inicio').eq('alumno_id',user.id).eq('fuente','strava').eq('eliminada',false).gte('fecha_inicio',monthStart()).limit(1000),supabase.from('pr_inline_skate_activities').select('id,distancia_metros').eq('alumno_id',user.id).eq('fuente','strava').eq('eliminada',false).limit(3000),supabase.from('pr_strava_connections').select('conectado').eq('alumno_id',user.id).maybeSingle(),supabase.from('pr_performance_objetivos').select('id,estado').eq('alumno_id',user.id).eq('eliminado',false),supabase.from('pr_performance_tomas_calculadas').select('id').eq('alumno_id',user.id).limit(500),supabase.from('actividad_pr').select('id,tipo').eq('alumno_id',user.id).eq('tipo','Insignia').or('eliminado.is.null,eliminado.eq.false').limit(500),supabase.from('actividad_pr').select('id').eq('alumno_id',user.id).eq('tipo','Evento').or('eliminado.is.null,eliminado.eq.false').limit(500)
  ]);if(!alive)return;const acts=a.data||[],allActs=all.data||[];
  const memberDate=p.data?.miembro_desde||p.data?.created_at,ageDays=memberDate?Math.floor((Date.now()-new Date(memberDate).getTime())/86400000):null;setData({loading:false,monthKm:acts.reduce((n,x)=>n+(Number(x.distancia_metros)||0)/1000,0),sessions:acts.length,allKm:allActs.reduce((n,x)=>n+(Number(x.distancia_metros)||0)/1000,0),allSessions:allActs.length,goals:(g.data||[]).filter(x=>String(x.estado).toLowerCase()==='completado').length,takes:(t.data||[]).length,milestones:(h.data||[]).length,historyEvents:(v.data||[]).length,strava:Boolean(s.data?.conectado)||allActs.length>0,newStudent:(ageDays!==null&&ageDays<45)||allActs.length===0})
 })().catch(()=>alive&&setData(x=>({...x,loading:false})));return()=>{alive=false}},[user?.id])
 const evolution=useMemo(()=>calculatePRProgression({km:data.allKm,sessions:data.allSessions,completedGoals:data.goals,milestones:data.milestones,takes:data.takes}),[data.allKm,data.allSessions,data.goals,data.milestones,data.takes])
 const cards=[['KM ESTE MES',data.loading?'—':data.monthKm===null?'—':data.monthKm.toLocaleString('es-UY',{maximumFractionDigits:1}),data.strava?'Desde Strava':'Conectá Strava','/app/mi-pr'],['ENTRENOS',data.loading?'—':data.sessions??'—','Actividades de este mes','/app/rollerfeed'],['EVENTOS',data.loading?'—':data.historyEvents,'Tu historia en PR','/app/historia']]
 return <><NewStudentWelcome show={!data.loading&&data.newStudent}/><section className="grid grid-cols-1 gap-2 min-[360px]:grid-cols-3">{cards.map(([k,v,s,to])=><Link key={k} to={to} className="rounded-[22px] border border-white/[.07] bg-white/[.025] p-3.5 sm:p-4"><p className="text-[7px] font-black tracking-[.13em] text-white/30">{k}</p><p className="mt-3 text-xl font-black tracking-tight">{v}</p><p className="mt-1 text-[8px] leading-3 text-white/30">{s}</p></Link>)}</section>
 <Link to="/app/evolucion" className="block overflow-hidden rounded-[27px] border border-violet-300/15 bg-gradient-to-r from-violet-400/[.07] via-white/[.02] to-cyan-300/[.05] p-4"><div className="flex items-center justify-between gap-4"><div><p className="text-[7px] font-black tracking-[.18em] text-violet-200/60">EVOLUCIÓN 2.0 · {PR_PROGRESSION_IS_BETA?'BETA · ':''}NIVEL {data.loading?'—':evolution.level.n}</p><h3 className="mt-1 text-sm font-black">{data.loading?'Leyendo tu historia…':evolution.level.name}</h3><p className="mt-1 text-[8px] text-white/22">Tu referencia personal. Nunca un ranking.</p></div><span className="text-violet-200/60">→</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-gradient-to-r from-violet-400 to-cyan-300 transition-all duration-700" style={{width:(data.loading?0:evolution.progress)+'%'}}/></div><div className="mt-2 flex justify-between text-[7px] font-black text-white/20"><span>{data.loading?'—':evolution.score+' PR'}</span><span>{evolution.next?'SIGUIENTE · '+evolution.next.name.toUpperCase():'RECORRIDO ACTUAL COMPLETO'}</span></div></Link>
 <section className="grid grid-cols-1 gap-2 min-[360px]:grid-cols-3"><Link to="/app/tareas" className="relative overflow-hidden rounded-[22px] border border-lime-300/12 bg-lime-300/[.03] p-4"><span className="absolute -right-3 -top-4 text-4xl font-black text-lime-100/[.035]">01</span><p className="relative text-[7px] font-black tracking-[.14em] text-lime-200/55">TAREAS</p><p className="relative mt-2 text-[9px] leading-4 text-white/28">Misiones y objetivos →</p></Link><Link to="/app/asistencia" className="relative overflow-hidden rounded-[22px] border border-cyan-300/12 bg-cyan-300/[.035] p-4"><span className="absolute -right-3 -top-4 text-4xl font-black text-cyan-100/[.035]">ID</span><p className="relative text-[7px] font-black tracking-[.14em] text-cyan-200/55">PR CHECK</p><p className="relative mt-2 text-[9px] leading-4 text-white/28">Asistencia e ID →</p></Link><Link to="/app/mi-pr" className="relative overflow-hidden rounded-[22px] border border-violet-300/10 bg-violet-300/[.025] p-4"><span className="absolute -right-3 -top-4 text-4xl font-black text-violet-100/[.035]">PR</span><p className="relative text-[7px] font-black tracking-[.14em] text-violet-200/48">MI PR</p><p className="relative mt-2 text-[9px] leading-4 text-white/28">Identidad e historia →</p></Link></section></>
}