-- Original schema metadata; beta only. No production data copied.
DO $replica$ BEGIN IF (SELECT attidentity FROM pg_attribute WHERE attrelid='public.clases_particulares_historial'::regclass AND attname='id') = '' THEN ALTER TABLE public."clases_particulares_historial" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY; END IF; END $replica$;
ALTER TABLE public."clases_particulares_historial" ALTER COLUMN "id" SET NOT NULL;
DO $replica$ BEGIN IF (SELECT attidentity FROM pg_attribute WHERE attrelid='public.cuponeras_particulares'::regclass AND attname='id') = '' THEN ALTER TABLE public."cuponeras_particulares" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY; END IF; END $replica$;
ALTER TABLE public."cuponeras_particulares" ALTER COLUMN "id" SET NOT NULL;
DO $replica$ BEGIN IF (SELECT attidentity FROM pg_attribute WHERE attrelid='public.pagos_pr'::regclass AND attname='id') = '' THEN ALTER TABLE public."pagos_pr" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY; END IF; END $replica$;
ALTER TABLE public."pagos_pr" ALTER COLUMN "id" SET NOT NULL;
DO $replica$ BEGIN IF (SELECT attidentity FROM pg_attribute WHERE attrelid='public.pr_email_campaign_sends'::regclass AND attname='id') = '' THEN ALTER TABLE public."pr_email_campaign_sends" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY; END IF; END $replica$;
ALTER TABLE public."pr_email_campaign_sends" ALTER COLUMN "id" SET NOT NULL;
DO $replica$ BEGIN IF (SELECT attidentity FROM pg_attribute WHERE attrelid='public.pr_email_contacts'::regclass AND attname='id') = '' THEN ALTER TABLE public."pr_email_contacts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY; END IF; END $replica$;
ALTER TABLE public."pr_email_contacts" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE public."pr_kids_children" ALTER COLUMN "nombre_confirmado" SET NOT NULL;
ALTER TABLE public."pr_kids_children" ALTER COLUMN "created_at" SET NOT NULL;
ALTER TABLE public."pr_kids_children" ALTER COLUMN "updated_at" SET NOT NULL;
ALTER TABLE public."pr_kids_family_approval_audit" ALTER COLUMN "request_id" SET NOT NULL;
ALTER TABLE public."pr_kids_family_approval_audit" ALTER COLUMN "guardian_id" SET NOT NULL;
ALTER TABLE public."pr_kids_family_approval_audit" ALTER COLUMN "admin_auth_user_id" SET NOT NULL;
ALTER TABLE public."pr_kids_family_approval_audit" ALTER COLUMN "child_profile_ids" SET NOT NULL;
ALTER TABLE public."pr_kids_family_approval_audit" ALTER COLUMN "created_at" SET NOT NULL;
ALTER TABLE public."pr_kids_family_requests" ALTER COLUMN "created_at" SET NOT NULL;
ALTER TABLE public."pr_kids_family_requests" ALTER COLUMN "nombre_tutor" SET NOT NULL;
ALTER TABLE public."pr_kids_family_requests" ALTER COLUMN "documento_tutor" SET NOT NULL;
ALTER TABLE public."pr_kids_family_requests" ALTER COLUMN "email_tutor" SET NOT NULL;
ALTER TABLE public."pr_kids_family_requests" ALTER COLUMN "telefono_tutor" SET NOT NULL;
ALTER TABLE public."pr_kids_family_requests" ALTER COLUMN "nombre_nino" SET NOT NULL;
ALTER TABLE public."pr_kids_family_requests" ALTER COLUMN "vinculo" SET NOT NULL;
ALTER TABLE public."pr_kids_family_requests" ALTER COLUMN "es_alumno" SET NOT NULL;
ALTER TABLE public."pr_kids_family_requests" ALTER COLUMN "estado" SET NOT NULL;
ALTER TABLE public."pr_kids_family_requests" ALTER COLUMN "hijos" SET NOT NULL;
ALTER TABLE public."pr_kids_family_review_audit" ALTER COLUMN "request_id" SET NOT NULL;
ALTER TABLE public."pr_kids_family_review_audit" ALTER COLUMN "admin_auth_user_id" SET NOT NULL;
ALTER TABLE public."pr_kids_family_review_audit" ALTER COLUMN "checks" SET NOT NULL;
ALTER TABLE public."pr_kids_family_review_audit" ALTER COLUMN "note" SET NOT NULL;
ALTER TABLE public."pr_kids_family_review_audit" ALTER COLUMN "created_at" SET NOT NULL;
ALTER TABLE public."pr_kids_guardian_children" ALTER COLUMN "vinculo" SET NOT NULL;
ALTER TABLE public."pr_kids_guardians" ALTER COLUMN "documento" SET NOT NULL;
ALTER TABLE public."pr_kids_guardians" ALTER COLUMN "nombre" SET NOT NULL;
ALTER TABLE public."pr_kids_guardians" ALTER COLUMN "estado" SET NOT NULL;
ALTER TABLE public."pr_kids_guardians" ALTER COLUMN "created_at" SET NOT NULL;
DO $replica$ BEGIN IF (SELECT attidentity FROM pg_attribute WHERE attrelid='public.pr_performance_objetivos'::regclass AND attname='id') = '' THEN ALTER TABLE public."pr_performance_objetivos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY; END IF; END $replica$;
ALTER TABLE public."pr_performance_objetivos" ALTER COLUMN "id" SET NOT NULL;
DO $replica$ BEGIN IF (SELECT attidentity FROM pg_attribute WHERE attrelid='public.pr_personal_disponibilidad'::regclass AND attname='id') = '' THEN ALTER TABLE public."pr_personal_disponibilidad" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY; END IF; END $replica$;
ALTER TABLE public."pr_personal_disponibilidad" ALTER COLUMN "id" SET NOT NULL;
DO $replica$ BEGIN IF (SELECT attidentity FROM pg_attribute WHERE attrelid='public.pr_personal_reservas'::regclass AND attname='id') = '' THEN ALTER TABLE public."pr_personal_reservas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY; END IF; END $replica$;
ALTER TABLE public."pr_personal_reservas" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE public."pr_rollermap_route_photos" ALTER COLUMN "sort_order" SET NOT NULL;
ALTER TABLE public."pr_rollermap_route_photos" ALTER COLUMN "status" SET NOT NULL;
DO $replica$ BEGIN IF (SELECT attidentity FROM pg_attribute WHERE attrelid='public.pr_track_reports'::regclass AND attname='id') = '' THEN ALTER TABLE public."pr_track_reports" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY; END IF; END $replica$;
ALTER TABLE public."pr_track_reports" ALTER COLUMN "id" SET NOT NULL;
DO $replica$ BEGIN IF (SELECT attidentity FROM pg_attribute WHERE attrelid='public.pr_track_scans'::regclass AND attname='id') = '' THEN ALTER TABLE public."pr_track_scans" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY; END IF; END $replica$;
ALTER TABLE public."pr_track_scans" ALTER COLUMN "id" SET NOT NULL;
ALTER TABLE public."pr_training_plan_achievements" ALTER COLUMN "profile_id" SET NOT NULL;
ALTER TABLE public."pr_training_plan_achievements" ALTER COLUMN "event_slug" SET NOT NULL;
ALTER TABLE public."pr_training_plan_achievements" ALTER COLUMN "completed_at" SET NOT NULL;
ALTER TABLE public."pr_training_public_checks" ALTER COLUMN "completed_at" SET NOT NULL;
ALTER TABLE public."pr_training_public_checks" ALTER COLUMN "updated_at" SET NOT NULL;
CREATE OR REPLACE VIEW public."actividad_pr_public" WITH (security_invoker=false) AS  SELECT id,
    alumno_id,
    tipo,
    titulo,
    descripcion,
    fecha,
    created_at,
    creado_por_nombre
   FROM actividad_pr
  WHERE COALESCE(eliminado, false) = false AND (lower(COALESCE(tipo, ''::text)) = ANY (ARRAY['deberes'::text, 'cumpleanos'::text, 'cumpleaños'::text, 'entrenamiento'::text, 'publicacion'::text, 'publicación'::text]));
CREATE OR REPLACE VIEW public."pr_activity_summary" WITH (security_invoker=true) AS  WITH bounds AS (
         SELECT (date_trunc('week'::text, (now() AT TIME ZONE 'America/Montevideo'::text)) AT TIME ZONE 'America/Montevideo'::text) AS week_start,
            (date_trunc('month'::text, (now() AT TIME ZONE 'America/Montevideo'::text)) AT TIME ZONE 'America/Montevideo'::text) AS month_start
        )
 SELECT a.alumno_id,
    count(*) FILTER (WHERE a.fecha_inicio >= b.week_start)::integer AS actividades_semana,
    COALESCE(sum(a.distancia_metros) FILTER (WHERE a.fecha_inicio >= b.week_start), 0::numeric) / 1000.0 AS km_semana,
    COALESCE(sum(a.tiempo_movimiento_segundos) FILTER (WHERE a.fecha_inicio >= b.week_start), 0::bigint) AS segundos_semana,
    count(*) FILTER (WHERE a.fecha_inicio >= b.month_start)::integer AS actividades_mes,
    COALESCE(sum(a.distancia_metros) FILTER (WHERE a.fecha_inicio >= b.month_start), 0::numeric) / 1000.0 AS km_mes,
    COALESCE(sum(a.tiempo_movimiento_segundos) FILTER (WHERE a.fecha_inicio >= b.month_start), 0::bigint) AS segundos_mes,
    max(a.fecha_inicio) AS ultima_actividad
   FROM pr_inline_skate_activities a
     CROSS JOIN bounds b
  GROUP BY a.alumno_id;
CREATE OR REPLACE VIEW public."pr_health_snapshot" AS  SELECT now() AS generated_at,
    ( SELECT count(*) AS count
           FROM profiles
          WHERE profiles.estado = 'Activo'::text) AS perfiles_activos,
    ( SELECT count(*) AS count
           FROM pr_strava_connections
          WHERE pr_strava_connections.conectado = true) AS strava_conectados,
    ( SELECT count(*) AS count
           FROM pr_activities
          WHERE COALESCE(pr_activities.eliminada, false) = false AND pr_activities.deporte_strava = 'InlineSkate'::text) AS actividades_inline_validas,
    ( SELECT count(*) AS count
           FROM pr_activities
          WHERE pr_activities.estado_validacion = 'rechazada'::text AND pr_activities.motivo_validacion ~~ 'Excluida automáticamente por control de integridad PR:%'::text) AS anomalias_strava,
    ( SELECT count(*) AS count
           FROM pr_personal_reservas
          WHERE pr_personal_reservas.estado = 'reservada'::text) AS personal_reservadas,
    ( SELECT max(pr_strava_connections.ultima_sincronizacion) AS max
           FROM pr_strava_connections
          WHERE pr_strava_connections.conectado = true) AS ultima_sincronizacion_strava;
ALTER VIEW public."pr_health_snapshot" RESET (security_invoker);
CREATE OR REPLACE VIEW public."pr_inline_skate_activities" WITH (security_invoker=true) AS  SELECT id,
    alumno_id,
    fuente,
    strava_activity_id,
    strava_athlete_id,
    strava_url,
    nombre,
    tipo,
    deporte_strava,
    fecha_inicio,
    zona_horaria,
    distancia_metros,
    tiempo_movimiento_segundos,
    tiempo_total_segundos,
    desnivel_metros,
    velocidad_media_ms,
    velocidad_maxima_ms,
    frecuencia_cardiaca_media,
    frecuencia_cardiaca_maxima,
    cadencia_media,
    calorias,
    esfuerzo_percibido,
    observacion,
    estado_validacion,
    validada_por,
    validada_en,
    motivo_validacion,
    visible_feed,
    es_privada,
    eliminada,
    raw_data,
    creado_en,
    actualizado_en
   FROM pr_activities
  WHERE lower(COALESCE(fuente, ''::text)) = 'strava'::text AND deporte_strava = 'InlineSkate'::text AND eliminada IS NOT TRUE;
CREATE OR REPLACE VIEW public."pr_inline_skate_public_activities" WITH (security_invoker=true) AS  SELECT id,
    alumno_id,
    fuente,
    strava_activity_id,
    strava_url,
    nombre,
    tipo,
    deporte_strava,
    fecha_inicio,
    distancia_metros,
    tiempo_movimiento_segundos,
    tiempo_total_segundos,
    desnivel_metros,
    velocidad_media_ms,
    velocidad_maxima_ms,
    visible_feed,
    es_privada,
    eliminada,
    creado_en,
    actualizado_en
   FROM pr_activities
  WHERE lower(COALESCE(fuente, ''::text)) = 'strava'::text AND deporte_strava = 'InlineSkate'::text AND eliminada IS NOT TRUE AND es_privada IS NOT TRUE AND visible_feed IS NOT FALSE;
CREATE OR REPLACE VIEW public."pr_performance_tomas_calculadas" WITH (security_invoker=true) AS  SELECT id,
    alumno_id,
    numero_toma,
    fecha,
    distancia_km,
    tiempo_segundos,
    devolucion,
    origen,
    observacion_original_id,
    creado_por,
    eliminado,
    created_at,
    updated_at,
    round(tiempo_segundos::numeric / distancia_km, 2) AS ritmo_segundos_km,
    round(distancia_km / (tiempo_segundos::numeric / 3600::numeric), 2) AS velocidad_kmh
   FROM pr_performance_tomas t
  WHERE eliminado = false;
CREATE OR REPLACE VIEW public."pr_personalizadas_health" WITH (security_invoker=true) AS  SELECT now() AS checked_at,
    ( SELECT count(*) AS count
           FROM cuponeras_particulares
          WHERE cuponeras_particulares.clases_disponibles < 0) AS saldos_negativos,
    ( SELECT count(*) AS count
           FROM cuponeras_particulares
          WHERE cuponeras_particulares.clases_disponibles <> (cuponeras_particulares.clases_cargadas - cuponeras_particulares.clases_utilizadas)) AS saldos_inconsistentes,
    ( SELECT count(*) AS count
           FROM cuponeras_particulares
          WHERE cuponeras_particulares.clases_utilizadas > cuponeras_particulares.clases_cargadas) AS sobreconsumos,
    ( SELECT count(*) AS count
           FROM pr_personal_reservas
          WHERE pr_personal_reservas.credito_consumido = true AND pr_personal_reservas.credito_devuelto = true) AS creditos_consumidos_y_devueltos,
    ( SELECT count(*) AS count
           FROM pr_personal_reservas
          WHERE pr_personal_reservas.estado = 'realizada'::text AND COALESCE(pr_personal_reservas.credito_consumido, false) = false) AS realizadas_sin_consumo,
    ( SELECT count(*) AS count
           FROM pr_personal_reservas
          WHERE (pr_personal_reservas.estado = ANY (ARRAY['cancelada'::text, 'reprogramada'::text, 'suspendida'::text])) AND pr_personal_reservas.credito_consumido = true AND COALESCE(pr_personal_reservas.credito_devuelto, false) = false) AS canceladas_sin_devolucion,
    ( SELECT count(*) AS count
           FROM ( SELECT pr_personal_reservas.disponibilidad_id
                   FROM pr_personal_reservas
                  WHERE pr_personal_reservas.estado = ANY (ARRAY['reservada'::text, 'confirmada'::text])
                  GROUP BY pr_personal_reservas.disponibilidad_id
                 HAVING count(*) > 1) d) AS turnos_duplicados_activos;
CREATE OR REPLACE VIEW public."pr_profiles_health" WITH (security_invoker=true) AS  SELECT now() AS checked_at,
    ( SELECT count(*) AS count
           FROM ( SELECT regexp_replace(profiles.documento, '\D'::text, ''::text, 'g'::text) AS doc
                   FROM profiles
                  WHERE length(regexp_replace(COALESCE(profiles.documento, ''::text), '\D'::text, ''::text, 'g'::text)) >= 6
                  GROUP BY (regexp_replace(profiles.documento, '\D'::text, ''::text, 'g'::text))
                 HAVING count(*) > 1) d) AS documentos_duplicados,
    ( SELECT count(*) AS count
           FROM ( SELECT regexp_replace(profiles.telefono, '\D'::text, ''::text, 'g'::text) AS tel
                   FROM profiles
                  WHERE length(regexp_replace(COALESCE(profiles.telefono, ''::text), '\D'::text, ''::text, 'g'::text)) >= 8
                  GROUP BY (regexp_replace(profiles.telefono, '\D'::text, ''::text, 'g'::text))
                 HAVING count(*) > 1) d) AS telefonos_compartidos,
    ( SELECT count(*) AS count
           FROM profiles
          WHERE profiles.auth_migrado = true AND profiles.auth_user_id IS NULL) AS auth_migrado_sin_usuario,
    ( SELECT count(*) AS count
           FROM profiles
          WHERE profiles.auth_user_id IS NOT NULL AND COALESCE(profiles.auth_migrado, false) = false) AS auth_usuario_sin_migrar,
    ( SELECT count(*) AS count
           FROM profiles
          WHERE lower(COALESCE(profiles.estado, ''::text)) = 'pausado'::text AND COALESCE(profiles.participa_como_alumno, false) = true) AS pausados_participando,
    ( SELECT count(*) AS count
           FROM profiles
          WHERE lower(COALESCE(profiles.estado, ''::text)) = 'activo'::text AND COALESCE(profiles.acceso_habilitado, false) = false AND profiles.id !~~ 'tesoreria_%'::text) AS activos_sin_acceso_reales,
    ( SELECT count(*) AS count
           FROM profiles
          WHERE lower(COALESCE(profiles.estado, ''::text)) = 'activo'::text AND COALESCE(profiles.acceso_habilitado, false) = false AND profiles.id ~~ 'tesoreria_%'::text) AS perfiles_solo_tesoreria_sin_acceso;
CREATE OR REPLACE VIEW public."pr_strava_ecosystem_health" AS  SELECT c.alumno_id AS profile_id,
    p.nombre,
    p.apellido,
    c.strava_athlete_id,
    c.conectado,
    c.ultima_sincronizacion,
    c.ultimo_error,
    a.checked_at,
    a.api_activity_count,
    a.api_inline_count,
    a.latest_api_activity_at,
    a.latest_api_activity_name,
    a.latest_api_activity_type,
    a.latest_inline_at,
    a.db_latest_inline_at,
    a.lag_seconds,
    a.status,
    a.details
   FROM pr_strava_connections c
     LEFT JOIN profiles p ON p.id = c.alumno_id
     LEFT JOIN pr_strava_sync_audit a ON a.profile_id = c.alumno_id;
ALTER VIEW public."pr_strava_ecosystem_health" RESET (security_invoker);
CREATE OR REPLACE VIEW public."pr_strava_health" WITH (security_invoker=true) AS  SELECT now() AS checked_at,
    ( SELECT count(*) AS count
           FROM ( SELECT pr_activities.strava_activity_id
                   FROM pr_activities
                  WHERE pr_activities.strava_activity_id IS NOT NULL
                  GROUP BY pr_activities.strava_activity_id
                 HAVING count(*) > 1) d) AS ids_strava_duplicados,
    ( SELECT count(*) AS count
           FROM pr_activities a
             LEFT JOIN profiles p ON p.id = a.alumno_id
          WHERE p.id IS NULL) AS actividades_huerfanas,
    ( SELECT count(*) AS count
           FROM pr_strava_connections c
             LEFT JOIN profiles p ON p.id = c.alumno_id
          WHERE p.id IS NULL) AS conexiones_huerfanas,
    ( SELECT count(*) AS count
           FROM pr_strava_connections
          WHERE pr_strava_connections.conectado = true AND NULLIF(TRIM(BOTH FROM COALESCE(pr_strava_connections.ultimo_error, ''::text)), ''::text) IS NOT NULL) AS conexiones_con_error,
    ( SELECT count(*) AS count
           FROM pr_strava_connections
          WHERE pr_strava_connections.conectado = true AND pr_strava_connections.strava_athlete_id IS NULL) AS conexiones_sin_atleta,
    ( SELECT count(*) AS count
           FROM pr_activities
          WHERE pr_activities.deporte_strava = 'InlineSkate'::text AND COALESCE(pr_activities.eliminada, false) = false AND COALESCE(pr_activities.distancia_metros, 0::numeric) <= 0::numeric) AS inline_sin_distancia,
    ( SELECT count(*) AS count
           FROM pr_activities
          WHERE pr_activities.deporte_strava = 'InlineSkate'::text AND COALESCE(pr_activities.eliminada, false) = false AND COALESCE(pr_activities.velocidad_maxima_ms, 0::numeric) > 30::numeric) AS inline_velocidad_imposible,
    ( SELECT count(*) AS count
           FROM pr_activities
          WHERE pr_activities.deporte_strava = 'InlineSkate'::text AND COALESCE(pr_activities.eliminada, false) = false AND COALESCE(pr_activities.tiempo_total_segundos, 0) > 172800) AS inline_duracion_imposible,
    ( SELECT count(*) AS count
           FROM pr_activities
          WHERE pr_activities.deporte_strava = 'InlineSkate'::text AND COALESCE(pr_activities.eliminada, false) = false AND pr_activities.fecha_inicio >= (date_trunc('month'::text, (now() AT TIME ZONE 'America/Montevideo'::text)) AT TIME ZONE 'America/Montevideo'::text)) AS inline_validas_mes;
CREATE OR REPLACE VIEW public."pr_tesoreria_health" WITH (security_invoker=true) AS  SELECT now() AS checked_at,
    ( SELECT count(*) AS count
           FROM pr_mensualidades m
             LEFT JOIN profiles p ON p.id = m.alumno_id
          WHERE p.id IS NULL) AS mensualidades_huerfanas,
    ( SELECT count(*) AS count
           FROM ( SELECT pr_mensualidades.alumno_id,
                    pr_mensualidades.periodo
                   FROM pr_mensualidades
                  GROUP BY pr_mensualidades.alumno_id, pr_mensualidades.periodo
                 HAVING count(*) > 1) d) AS mensualidades_duplicadas,
    ( SELECT count(*) AS count
           FROM pr_mensualidades
          WHERE pr_mensualidades.estado = 'pagado'::text AND pr_mensualidades.fecha_pago IS NULL) AS pagadas_sin_fecha,
    ( SELECT count(*) AS count
           FROM pr_mensualidades m
             JOIN profiles p ON p.id = m.alumno_id
          WHERE lower(COALESCE(p.estado, ''::text)) = 'pausado'::text AND (m.estado = ANY (ARRAY['pendiente'::text, 'vencido'::text])) AND COALESCE(m.monto, 0::numeric) > 0::numeric) AS deuda_generada_a_pausados,
    ( SELECT count(*) AS count
           FROM pr_mensualidades m
             JOIN profiles p ON p.id = m.alumno_id
          WHERE COALESCE(p.exento_mensualidad, false) = true AND (m.estado = ANY (ARRAY['pendiente'::text, 'vencido'::text])) AND COALESCE(m.monto, 0::numeric) > 0::numeric) AS deuda_generada_a_exentos,
    ( SELECT count(*) AS count
           FROM pr_mensualidades m
             JOIN profiles p ON p.id = m.alumno_id
          WHERE lower(COALESCE(p.estado, ''::text)) = 'pausado'::text AND m.estado = 'vencido'::text AND COALESCE(m.monto, 0::numeric) = 0::numeric) AS pausados_cero_marcados_vencidos,
    ( SELECT count(*) AS count
           FROM pr_mensualidades m
             JOIN profiles p ON p.id = m.alumno_id
          WHERE lower(COALESCE(p.estado, ''::text)) <> 'pausado'::text AND COALESCE(p.exento_mensualidad, false) = false AND m.estado = 'vencido'::text AND COALESCE(m.monto, 0::numeric) = 0::numeric) AS activos_cero_a_revisar;
CREATE OR REPLACE VIEW public."pr_training_completed_feed" WITH (security_invoker=false) AS  SELECT r.id,
    r.profile_id,
    r.task_id,
    r.activity_id,
    r.completed_at,
    r.updated_at,
    t.title AS task_title,
    t.sort_order AS task_number,
    t.event_slug
   FROM pr_training_task_results r
     JOIN pr_training_tasks t ON t.id = r.task_id
  WHERE lower(COALESCE(r.status, ''::text)) = 'completed'::text AND r.completed_at IS NOT NULL AND t.event_slug = 'shifter-marathon-2026'::text AND t.active = true;
CREATE OR REPLACE VIEW public."pr_training_progress_public" WITH (security_invoker=false) AS  SELECT e.profile_id,
    e.category,
    count(t.id)::integer AS total_tasks,
    count(t.id) FILTER (WHERE lower(COALESCE(r.status, ''::text)) = 'completed'::text)::integer AS completed_tasks,
    COALESCE(round(100.0 * count(t.id) FILTER (WHERE lower(COALESCE(r.status, ''::text)) = 'completed'::text)::numeric / NULLIF(count(t.id), 0)::numeric), 0::numeric)::integer AS progress_pct
   FROM pr_training_enrollments e
     JOIN pr_training_tasks t ON t.event_slug = e.event_slug AND t.active = true AND (t.category = e.category OR t.category = 'ALL'::text)
     LEFT JOIN pr_training_task_results r ON r.profile_id = e.profile_id AND r.task_id = t.id
  WHERE e.event_slug = 'shifter-marathon-2026'::text AND e.active = true AND (e.category = ANY (ARRAY['6K'::text, '12K'::text]))
  GROUP BY e.profile_id, e.category;
CREATE OR REPLACE VIEW public."pr_unlock_live_contributions" WITH (security_invoker=false) AS  SELECT c.id AS campaign_id,
    c.slug,
    c.starts_on,
    c.ends_on,
    a.alumno_id,
    COALESCE(NULLIF(TRIM(BOTH FROM (COALESCE(p.nombre, ''::text) || ' '::text) || COALESCE(p.apellido, ''::text)), ''::text), 'Integrante PR'::text) AS nombre,
    p.foto,
    round(sum(a.distancia_metros) / 1000.0, 2) AS km,
    count(*)::integer AS actividades
   FROM pr_unlock_campaigns c
     JOIN pr_inline_skate_activities a ON a.fecha_inicio >= (c.starts_on::timestamp without time zone AT TIME ZONE 'America/Montevideo'::text) AND a.fecha_inicio < ((c.ends_on + 1)::timestamp without time zone AT TIME ZONE 'America/Montevideo'::text)
     LEFT JOIN profiles_public p ON p.id = a.alumno_id
  WHERE c.active = true AND COALESCE(a.eliminada, false) = false AND COALESCE(a.es_privada, false) = false AND COALESCE(a.visible_feed, true) = true AND lower(COALESCE(a.fuente, 'strava'::text)) = 'strava'::text
  GROUP BY c.id, c.slug, c.starts_on, c.ends_on, a.alumno_id, p.nombre, p.apellido, p.foto;
CREATE OR REPLACE VIEW public."profiles_feed" WITH (security_invoker=false) AS  SELECT id,
    nombre,
    apellido,
    foto,
    verificado,
        CASE
            WHEN fecha_nacimiento ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}'::text THEN SUBSTRING(fecha_nacimiento FROM 6 FOR 2)::integer
            ELSE NULL::integer
        END AS cumple_mes,
        CASE
            WHEN fecha_nacimiento ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}'::text THEN SUBSTRING(fecha_nacimiento FROM 9 FOR 2)::integer
            ELSE NULL::integer
        END AS cumple_dia,
    role,
    es_profesor,
    participa_como_alumno
   FROM profiles
  WHERE estado IS DISTINCT FROM 'Inactivo'::text;
CREATE OR REPLACE VIEW public."profiles_public" WITH (security_invoker=false) AS  SELECT id,
    nombre,
    apellido,
    foto,
    verificado
   FROM profiles
  WHERE estado IS DISTINCT FROM 'Inactivo'::text;

