-- Restore original local triggers. External email triggers intentionally omitted.
DROP TRIGGER IF EXISTS "trg_album_comment_notify" ON public."community_album_comments";
CREATE TRIGGER trg_album_comment_notify AFTER INSERT ON community_album_comments FOR EACH ROW EXECUTE FUNCTION community_notify_album_social();
ALTER TABLE public."community_album_comments" ENABLE TRIGGER "trg_album_comment_notify";
DROP TRIGGER IF EXISTS "trg_album_photo" ON public."community_album_media";
CREATE TRIGGER trg_album_photo AFTER INSERT ON community_album_media FOR EACH ROW EXECUTE FUNCTION community_notify();
ALTER TABLE public."community_album_media" ENABLE TRIGGER "trg_album_photo";
DROP TRIGGER IF EXISTS "trg_album" ON public."community_album_members";
CREATE TRIGGER trg_album AFTER INSERT ON community_album_members FOR EACH ROW EXECUTE FUNCTION community_notify();
ALTER TABLE public."community_album_members" ENABLE TRIGGER "trg_album";
DROP TRIGGER IF EXISTS "trg_album_photo_comment_notify" ON public."community_album_photo_comments";
CREATE TRIGGER trg_album_photo_comment_notify AFTER INSERT ON community_album_photo_comments FOR EACH ROW EXECUTE FUNCTION community_notify_album_social();
ALTER TABLE public."community_album_photo_comments" ENABLE TRIGGER "trg_album_photo_comment_notify";
DROP TRIGGER IF EXISTS "trg_album_photo_reaction_notify" ON public."community_album_photo_reactions";
CREATE TRIGGER trg_album_photo_reaction_notify AFTER INSERT ON community_album_photo_reactions FOR EACH ROW EXECUTE FUNCTION community_notify_album_social();
ALTER TABLE public."community_album_photo_reactions" ENABLE TRIGGER "trg_album_photo_reaction_notify";
DROP TRIGGER IF EXISTS "trg_album_reaction_notify" ON public."community_album_reactions";
CREATE TRIGGER trg_album_reaction_notify AFTER INSERT ON community_album_reactions FOR EACH ROW EXECUTE FUNCTION community_notify_album_social();
ALTER TABLE public."community_album_reactions" ENABLE TRIGGER "trg_album_reaction_notify";
DROP TRIGGER IF EXISTS "trg_new_album" ON public."community_albums";
CREATE TRIGGER trg_new_album AFTER INSERT ON community_albums FOR EACH ROW EXECUTE FUNCTION community_notify_new_album();
ALTER TABLE public."community_albums" ENABLE TRIGGER "trg_new_album";
DROP TRIGGER IF EXISTS "trg_comment" ON public."community_post_comments";
CREATE TRIGGER trg_comment AFTER INSERT ON community_post_comments FOR EACH ROW EXECUTE FUNCTION community_notify();
ALTER TABLE public."community_post_comments" ENABLE TRIGGER "trg_comment";
DROP TRIGGER IF EXISTS "trg_reaction" ON public."community_post_reactions";
CREATE TRIGGER trg_reaction AFTER INSERT OR UPDATE ON community_post_reactions FOR EACH ROW EXECUTE FUNCTION community_notify();
ALTER TABLE public."community_post_reactions" ENABLE TRIGGER "trg_reaction";
DROP TRIGGER IF EXISTS "trg_tag" ON public."community_post_tags";
CREATE TRIGGER trg_tag AFTER INSERT ON community_post_tags FOR EACH ROW EXECUTE FUNCTION community_notify();
ALTER TABLE public."community_post_tags" ENABLE TRIGGER "trg_tag";
DROP TRIGGER IF EXISTS "trg_new_post" ON public."community_posts";
CREATE TRIGGER trg_new_post AFTER INSERT ON community_posts FOR EACH ROW EXECUTE FUNCTION community_notify_new_post();
ALTER TABLE public."community_posts" ENABLE TRIGGER "trg_new_post";
DROP TRIGGER IF EXISTS "trg_repost" ON public."community_reposts";
CREATE TRIGGER trg_repost AFTER INSERT ON community_reposts FOR EACH ROW EXECUTE FUNCTION community_notify_repost();
ALTER TABLE public."community_reposts" ENABLE TRIGGER "trg_repost";
DROP TRIGGER IF EXISTS "trg_pr_guard_strava_inline_skate_anomalies" ON public."pr_activities";
CREATE TRIGGER trg_pr_guard_strava_inline_skate_anomalies BEFORE INSERT OR UPDATE ON pr_activities FOR EACH ROW EXECUTE FUNCTION pr_guard_strava_inline_skate_anomalies();
ALTER TABLE public."pr_activities" ENABLE TRIGGER "trg_pr_guard_strava_inline_skate_anomalies";
DROP TRIGGER IF EXISTS "trg_pr_inline_skate_strava_visibility" ON public."pr_activities";
CREATE TRIGGER trg_pr_inline_skate_strava_visibility BEFORE INSERT OR UPDATE OF fuente, deporte_strava, es_privada, eliminada, visible_feed ON pr_activities FOR EACH ROW EXECUTE FUNCTION pr_enforce_inline_skate_strava_visibility();
ALTER TABLE public."pr_activities" ENABLE TRIGGER "trg_pr_inline_skate_strava_visibility";
DROP TRIGGER IF EXISTS "trg_pr_match_shifter_training_activity" ON public."pr_activities";
CREATE TRIGGER trg_pr_match_shifter_training_activity AFTER INSERT OR UPDATE OF nombre, distancia_metros, tiempo_movimiento_segundos, tiempo_total_segundos, eliminada ON pr_activities FOR EACH ROW EXECUTE FUNCTION pr_match_shifter_training_activity();
ALTER TABLE public."pr_activities" ENABLE TRIGGER "trg_pr_match_shifter_training_activity";
DROP TRIGGER IF EXISTS "trg_pr_groups_updated_at" ON public."pr_groups";
CREATE TRIGGER trg_pr_groups_updated_at BEFORE UPDATE ON pr_groups FOR EACH ROW EXECUTE FUNCTION set_pr_groups_updated_at();
ALTER TABLE public."pr_groups" ENABLE TRIGGER "trg_pr_groups_updated_at";
DROP TRIGGER IF EXISTS "trg_pr_unlock_finalize_due" ON public."pr_inline_skate_activities";
CREATE TRIGGER trg_pr_unlock_finalize_due AFTER INSERT OR UPDATE ON pr_inline_skate_activities FOR EACH STATEMENT EXECUTE FUNCTION pr_unlock_finalize_due_campaigns();
DROP TRIGGER IF EXISTS "trg_sync_referral_from_enrollment" ON public."pr_inscripciones_2026";
CREATE TRIGGER trg_sync_referral_from_enrollment AFTER UPDATE OF estado ON pr_inscripciones_2026 FOR EACH ROW EXECUTE FUNCTION sync_referral_from_enrollment();
ALTER TABLE public."pr_inscripciones_2026" ENABLE TRIGGER "trg_sync_referral_from_enrollment";
DROP TRIGGER IF EXISTS "trg_pr_performance_updated_at" ON public."pr_performance";
CREATE TRIGGER trg_pr_performance_updated_at BEFORE UPDATE ON pr_performance FOR EACH ROW EXECUTE FUNCTION set_updated_at();
ALTER TABLE public."pr_performance" ENABLE TRIGGER "trg_pr_performance_updated_at";
DROP TRIGGER IF EXISTS "trg_assign_pr_toma_number" ON public."pr_performance_tomas";
CREATE TRIGGER trg_assign_pr_toma_number BEFORE INSERT ON pr_performance_tomas FOR EACH ROW EXECUTE FUNCTION assign_pr_toma_number();
ALTER TABLE public."pr_performance_tomas" ENABLE TRIGGER "trg_assign_pr_toma_number";
DROP TRIGGER IF EXISTS "trg_pr_performance_tomas_updated_at" ON public."pr_performance_tomas";
CREATE TRIGGER trg_pr_performance_tomas_updated_at BEFORE UPDATE ON pr_performance_tomas FOR EACH ROW EXECUTE FUNCTION set_updated_at();
ALTER TABLE public."pr_performance_tomas" ENABLE TRIGGER "trg_pr_performance_tomas_updated_at";
DROP TRIGGER IF EXISTS "trg_sync_toma3_rollerfeed_post" ON public."pr_performance_tomas";
CREATE TRIGGER trg_sync_toma3_rollerfeed_post AFTER INSERT OR DELETE OR UPDATE ON pr_performance_tomas FOR EACH ROW EXECUTE FUNCTION trigger_sync_toma3_rollerfeed_post();
ALTER TABLE public."pr_performance_tomas" ENABLE TRIGGER "trg_sync_toma3_rollerfeed_post";
DROP TRIGGER IF EXISTS "trg_pr_referral_confirm_timestamp" ON public."pr_referrals";
CREATE TRIGGER trg_pr_referral_confirm_timestamp BEFORE INSERT OR UPDATE OF status ON pr_referrals FOR EACH ROW EXECUTE FUNCTION pr_referral_confirm_timestamp_trigger();
ALTER TABLE public."pr_referrals" ENABLE TRIGGER "trg_pr_referral_confirm_timestamp";
DROP TRIGGER IF EXISTS "trg_pr_referral_rewards" ON public."pr_referrals";
CREATE TRIGGER trg_pr_referral_rewards AFTER INSERT OR UPDATE OF status ON pr_referrals FOR EACH ROW EXECUTE FUNCTION pr_referral_reward_after_trigger();
ALTER TABLE public."pr_referrals" ENABLE TRIGGER "trg_pr_referral_rewards";
DROP TRIGGER IF EXISTS "pr_track_items_sync_profile" ON public."pr_track_items";
CREATE TRIGGER pr_track_items_sync_profile AFTER INSERT OR DELETE OR UPDATE ON pr_track_items FOR EACH ROW EXECUTE FUNCTION pr_track_sync_profile_trigger();
ALTER TABLE public."pr_track_items" ENABLE TRIGGER "pr_track_items_sync_profile";
DROP TRIGGER IF EXISTS "training_enrollment_completion" ON public."pr_training_enrollments";
CREATE TRIGGER training_enrollment_completion AFTER INSERT OR UPDATE ON pr_training_enrollments FOR EACH ROW EXECUTE FUNCTION pr_training_internal.on_plan_enrollment_completion();
ALTER TABLE public."pr_training_enrollments" ENABLE TRIGGER "training_enrollment_completion";
DROP TRIGGER IF EXISTS "sync_training_public_checks" ON public."pr_training_task_results";
CREATE TRIGGER sync_training_public_checks AFTER INSERT OR DELETE OR UPDATE ON pr_training_task_results FOR EACH ROW EXECUTE FUNCTION pr_training_internal.sync_completed_checks();
ALTER TABLE public."pr_training_task_results" ENABLE TRIGGER "sync_training_public_checks";
DROP TRIGGER IF EXISTS "trg_pr_publish_training_completion_to_feed" ON public."pr_training_task_results";
CREATE TRIGGER trg_pr_publish_training_completion_to_feed AFTER INSERT OR UPDATE OF status, completed_at ON pr_training_task_results FOR EACH ROW EXECUTE FUNCTION pr_publish_training_completion_to_feed();
ALTER TABLE public."pr_training_task_results" ENABLE TRIGGER "trg_pr_publish_training_completion_to_feed";
DROP TRIGGER IF EXISTS "trg_training_task_result_to_rollerfeed" ON public."pr_training_task_results";
CREATE TRIGGER trg_training_task_result_to_rollerfeed AFTER INSERT OR DELETE OR UPDATE ON pr_training_task_results FOR EACH ROW EXECUTE FUNCTION sync_training_task_result_to_rollerfeed();
ALTER TABLE public."pr_training_task_results" DISABLE TRIGGER "trg_training_task_result_to_rollerfeed";
DROP TRIGGER IF EXISTS "zz_training_plan_completion" ON public."pr_training_task_results";
CREATE TRIGGER zz_training_plan_completion AFTER INSERT OR UPDATE ON pr_training_task_results FOR EACH ROW EXECUTE FUNCTION pr_training_internal.on_plan_completion();
ALTER TABLE public."pr_training_task_results" ENABLE TRIGGER "zz_training_plan_completion";
DROP TRIGGER IF EXISTS "trg_pr_unlock_publish_winner" ON public."pr_unlock_results";
CREATE TRIGGER trg_pr_unlock_publish_winner AFTER INSERT ON pr_unlock_results FOR EACH ROW EXECUTE FUNCTION pr_unlock_publish_winner();
ALTER TABLE public."pr_unlock_results" ENABLE TRIGGER "trg_pr_unlock_publish_winner";
DROP TRIGGER IF EXISTS "create_community_privacy_after_profile" ON public."profiles";
CREATE TRIGGER create_community_privacy_after_profile AFTER INSERT ON profiles FOR EACH ROW EXECUTE FUNCTION create_default_community_privacy();
ALTER TABLE public."profiles" ENABLE TRIGGER "create_community_privacy_after_profile";
DROP TRIGGER IF EXISTS "proteger_campos_profile_trigger" ON public."profiles";
CREATE TRIGGER proteger_campos_profile_trigger BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION proteger_campos_profile();
ALTER TABLE public."profiles" ENABLE TRIGGER "proteger_campos_profile_trigger";

