-- Original non-personal training catalog; beta IDs generated locally.
INSERT INTO public.pr_training_tasks(title,active,category,rule_type,event_slug,sort_order,description,strava_code,instructions,series_count,target_value,reference_text,recovery_minutes,target_secondary) VALUES
('15 min · De menos a más',true,'ALL','duration_min','shifter-marathon-2026',1,'Patiná 15 minutos continuos. Empezá cómodo y aumentá progresivamente la intensidad. Terminá más fuerte de lo que empezaste, sin salir a fondo desde el comienzo.','PR-SHIFTER-D01','{"mode":"continuous","focus":"progresivo"}'::jsonb,1,15,NULL,NULL,NULL),
('2 × 3K · Ritmo controlado',true,'ALL','series_distance','shifter-marathon-2026',2,'Completá 2 series de 3 km. La primera tiene una referencia de 10 a 12 min y la segunda de 11 a 14 min. Recuperá 5 minutos entre ambas.','PR-SHIFTER-D02','{"mode":"series","series_labels":["PR-SHIFTER-D02-S1 · 3K","PR-SHIFTER-D02-S2 · 3K"]}'::jsonb,2,3000,'S1: 10–12 min · S2: 11–14 min',5,NULL),
('6 × 700 m',true,'ALL','series_distance','shifter-marathon-2026',3,'Completá 6 series de 700 m. Buscá sostener un trabajo parejo y recuperá 2 minutos entre serie y serie.','PR-SHIFTER-D03','{"mode":"series"}'::jsonb,6,700,'Referencia: 1:30–2:00 por serie',2,NULL),
('30 min · Técnica continua',true,'ALL','duration_min','shifter-marathon-2026',4,'Patiná 30 minutos continuos a intensidad tranquila. Priorizá una posición baja, técnica y calidad de patinaje por encima de la velocidad.','PR-SHIFTER-D04','{"mode":"continuous","focus":"tecnica"}'::jsonb,1,30,NULL,NULL,NULL),
('35 min · De menos a más',true,'ALL','duration_min','shifter-marathon-2026',5,'Patiná 35 minutos continuos aumentando progresivamente la intensidad. Control al principio; terminá trabajando más fuerte.','PR-SHIFTER-D05','{"mode":"continuous","focus":"progresivo"}'::jsonb,1,35,NULL,NULL,NULL),
('2 × 4K',true,'ALL','series_distance','shifter-marathon-2026',6,'Completá 2 series de 4 km. Recuperá 5 minutos entre ambas antes de comenzar la segunda.','PR-SHIFTER-D06','{"mode":"series"}'::jsonb,2,4000,NULL,5,NULL),
('12 min · Chill',true,'ALL','duration_min','shifter-marathon-2026',7,'Patiná 12 minutos continuos a ritmo cómodo. Sin perseguir velocidad: soltá, patiná fluido y mantené control.','PR-SHIFTER-D07','{"mode":"continuous","focus":"suave"}'::jsonb,1,12,NULL,NULL,NULL),
('2 × 12 min · Progresivos',true,'ALL','series_duration','shifter-marathon-2026',8,'Hacé 2 series de 12 minutos, ambas de menos a más. Recuperá 5 minutos entre series.','PR-SHIFTER-D08','{"mode":"series","focus":"progresivo"}'::jsonb,2,12,NULL,5,NULL),
('3 × 11 min',true,'ALL','series_duration','shifter-marathon-2026',9,'Completá 3 series de 11 minutos. Recuperá 5 minutos entre cada una.','PR-SHIFTER-D09','{"mode":"series"}'::jsonb,3,11,NULL,5,NULL),
('8 × 700 m',true,'ALL','series_distance','shifter-marathon-2026',10,'Completá 8 series de 700 m. Buscá sostener un trabajo parejo y recuperá 3 minutos entre cada serie.','PR-SHIFTER-D10','{"mode":"series"}'::jsonb,8,700,'Referencia: aproximadamente 2:00 por serie',3,NULL),
('6 × 1K',true,'ALL','series_distance','shifter-marathon-2026',11,'Completá 6 series de 1 km. Recuperá 3 minutos entre cada serie.','PR-SHIFTER-D11','{"mode":"series"}'::jsonb,6,1000,'Referencia: aproximadamente 2:30 por serie',3,NULL),
('40 min · Técnica continua',true,'ALL','duration_min','shifter-marathon-2026',12,'Patiná 40 minutos continuos muy tranquilo. El objetivo es patinar bien: posición, técnica, control y eficiencia. No busques velocidad.','PR-SHIFTER-D12','{"mode":"continuous","focus":"tecnica"}'::jsonb,1,40,NULL,NULL,NULL)
ON CONFLICT(strava_code) DO UPDATE SET title=excluded.title,active=excluded.active,category=excluded.category,rule_type=excluded.rule_type,event_slug=excluded.event_slug,sort_order=excluded.sort_order,description=excluded.description,instructions=excluded.instructions,series_count=excluded.series_count,target_value=excluded.target_value,reference_text=excluded.reference_text,recovery_minutes=excluded.recovery_minutes,target_secondary=excluded.target_secondary;
-- Fictitious beta treasury setup with all outgoing reminders disabled.
INSERT INTO public.pr_tesoreria_config(id,monto_default,enforcement_enabled,reminder_email_enabled) VALUES(1,100,false,false) ON CONFLICT(id) DO UPDATE SET reminder_email_enabled=false,enforcement_enabled=false;

