-- PR Moments + free-form RollerFeed comments.
-- Apply first to a Supabase preview/staging project, never directly to production.

create schema if not exists pr_private;
revoke all on schema pr_private from public, anon;
grant usage on schema pr_private to authenticated;

create or replace function pr_private.current_profile_id()
returns text
language sql
stable
security definer
set search_path = public, auth
as $$
  select p.id::text
  from public.profiles p
  where p.auth_user_id = (select auth.uid())
  limit 1
$$;

create or replace function pr_private.is_moderator()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1 from public.profiles p
    where p.auth_user_id = (select auth.uid())
      and lower(coalesce(p.role, '')) in ('admin', 'profesor')
  )
$$;

revoke all on function pr_private.current_profile_id() from public, anon;
revoke all on function pr_private.is_moderator() from public, anon;
grant execute on function pr_private.current_profile_id() to authenticated;
grant execute on function pr_private.is_moderator() to authenticated;

create table if not exists public.pr_friendships (
  id bigint generated by default as identity primary key,
  requester_profile_id text not null,
  addressee_profile_id text not null,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'blocked')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (requester_profile_id, addressee_profile_id),
  check (requester_profile_id <> addressee_profile_id)
);

create table if not exists public.pr_moments (
  id uuid primary key default gen_random_uuid(),
  profile_id text not null,
  media_type text not null check (media_type in ('text', 'image', 'video')),
  caption text,
  storage_path text,
  visibility text not null default 'all' check (visibility in ('all', 'friends', 'self')),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours'),
  deleted_at timestamptz,
  deleted_by_profile_id text,
  check (char_length(coalesce(caption, '')) <= 2000),
  check ((media_type = 'text' and storage_path is null and nullif(btrim(caption), '') is not null)
      or (media_type in ('image', 'video') and storage_path is not null)),
  check (expires_at > created_at and expires_at <= created_at + interval '24 hours 5 minutes')
);

create table if not exists public.pr_moment_reactions (
  id bigint generated by default as identity primary key,
  moment_id uuid not null references public.pr_moments(id) on delete cascade,
  profile_id text not null,
  reaction text not null check (reaction in ('fire', 'heart', 'skate', 'bolt', 'clap')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (moment_id, profile_id)
);

create table if not exists public.pr_moment_comments (
  id bigint generated by default as identity primary key,
  moment_id uuid not null references public.pr_moments(id) on delete cascade,
  profile_id text not null,
  body text not null check (char_length(btrim(body)) between 1 and 1000),
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_by_profile_id text
);

create table if not exists public.rollerfeed_comments (
  id bigint generated by default as identity primary key,
  feed_key text not null check (char_length(feed_key) between 1 and 250),
  profile_id text not null,
  body text not null check (char_length(btrim(body)) between 1 and 1000),
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_by_profile_id text
);

create index if not exists pr_moments_active_idx on public.pr_moments (expires_at desc) where deleted_at is null;
create index if not exists pr_moments_profile_idx on public.pr_moments (profile_id, created_at desc);
create index if not exists pr_moment_comments_moment_idx on public.pr_moment_comments (moment_id, created_at);
create index if not exists pr_moment_reactions_moment_idx on public.pr_moment_reactions (moment_id);
create index if not exists rollerfeed_comments_feed_idx on public.rollerfeed_comments (feed_key, created_at) where deleted_at is null;

create or replace function pr_private.force_profile_identity()
returns trigger
language plpgsql
security invoker
set search_path = public, pr_private
as $$
begin
  new.profile_id := pr_private.current_profile_id();
  if new.profile_id is null then raise exception 'No linked profile'; end if;
  return new;
end
$$;

drop trigger if exists pr_moments_identity on public.pr_moments;
create trigger pr_moments_identity before insert on public.pr_moments for each row execute function pr_private.force_profile_identity();
drop trigger if exists pr_moment_reactions_identity on public.pr_moment_reactions;
create trigger pr_moment_reactions_identity before insert or update on public.pr_moment_reactions for each row execute function pr_private.force_profile_identity();
drop trigger if exists pr_moment_comments_identity on public.pr_moment_comments;
create trigger pr_moment_comments_identity before insert on public.pr_moment_comments for each row execute function pr_private.force_profile_identity();
drop trigger if exists rollerfeed_comments_identity on public.rollerfeed_comments;
create trigger rollerfeed_comments_identity before insert on public.rollerfeed_comments for each row execute function pr_private.force_profile_identity();

alter table public.pr_friendships enable row level security;
alter table public.pr_moments enable row level security;
alter table public.pr_moment_reactions enable row level security;
alter table public.pr_moment_comments enable row level security;
alter table public.rollerfeed_comments enable row level security;

create policy "friendships participants read" on public.pr_friendships for select to authenticated
using (requester_profile_id = pr_private.current_profile_id() or addressee_profile_id = pr_private.current_profile_id() or pr_private.is_moderator());
create policy "friendships requester creates" on public.pr_friendships for insert to authenticated
with check (requester_profile_id = pr_private.current_profile_id());
create policy "friendships participants update" on public.pr_friendships for update to authenticated
using (requester_profile_id = pr_private.current_profile_id() or addressee_profile_id = pr_private.current_profile_id())
with check (requester_profile_id = pr_private.current_profile_id() or addressee_profile_id = pr_private.current_profile_id());

create policy "visible active moments read" on public.pr_moments for select to authenticated using (
  deleted_at is null and expires_at > now() and (
    profile_id = pr_private.current_profile_id() or visibility = 'all' or
    (visibility = 'friends' and exists (
      select 1 from public.pr_friendships f where f.status = 'accepted' and
      ((f.requester_profile_id = profile_id and f.addressee_profile_id = pr_private.current_profile_id()) or
       (f.addressee_profile_id = profile_id and f.requester_profile_id = pr_private.current_profile_id()))
    )) or pr_private.is_moderator()
  )
);
create policy "owners create moments" on public.pr_moments for insert to authenticated
with check (profile_id = pr_private.current_profile_id());
create policy "owners or moderators update moments" on public.pr_moments for update to authenticated
using (profile_id = pr_private.current_profile_id() or pr_private.is_moderator())
with check (profile_id = pr_private.current_profile_id() or pr_private.is_moderator());
create policy "owners or moderators delete moments" on public.pr_moments for delete to authenticated
using (profile_id = pr_private.current_profile_id() or pr_private.is_moderator());

create policy "visible moment reactions read" on public.pr_moment_reactions for select to authenticated
using (exists (select 1 from public.pr_moments m where m.id = moment_id));
create policy "own reactions create" on public.pr_moment_reactions for insert to authenticated
with check (profile_id = pr_private.current_profile_id() and exists (select 1 from public.pr_moments m where m.id = moment_id));
create policy "own reactions update" on public.pr_moment_reactions for update to authenticated
using (profile_id = pr_private.current_profile_id()) with check (profile_id = pr_private.current_profile_id());
create policy "own reactions delete" on public.pr_moment_reactions for delete to authenticated
using (profile_id = pr_private.current_profile_id() or pr_private.is_moderator());

create policy "visible moment comments read" on public.pr_moment_comments for select to authenticated
using (deleted_at is null and exists (select 1 from public.pr_moments m where m.id = moment_id));
create policy "comments create" on public.pr_moment_comments for insert to authenticated
with check (profile_id = pr_private.current_profile_id() and exists (select 1 from public.pr_moments m where m.id = moment_id));
create policy "comments moderate" on public.pr_moment_comments for update to authenticated
using (profile_id = pr_private.current_profile_id() or pr_private.is_moderator())
with check (profile_id = pr_private.current_profile_id() or pr_private.is_moderator());
create policy "comments delete" on public.pr_moment_comments for delete to authenticated
using (profile_id = pr_private.current_profile_id() or pr_private.is_moderator());

create policy "rollerfeed comments read" on public.rollerfeed_comments for select to authenticated using (deleted_at is null);
create policy "rollerfeed comments create" on public.rollerfeed_comments for insert to authenticated
with check (profile_id = pr_private.current_profile_id());
create policy "rollerfeed comments moderate" on public.rollerfeed_comments for update to authenticated
using (profile_id = pr_private.current_profile_id() or pr_private.is_moderator())
with check (profile_id = pr_private.current_profile_id() or pr_private.is_moderator());
create policy "rollerfeed comments delete" on public.rollerfeed_comments for delete to authenticated
using (profile_id = pr_private.current_profile_id() or pr_private.is_moderator());

grant select, insert, update, delete on public.pr_friendships, public.pr_moments, public.pr_moment_reactions, public.pr_moment_comments, public.rollerfeed_comments to authenticated;
grant usage, select on sequence public.pr_friendships_id_seq to authenticated;
grant usage, select on sequence public.pr_moment_reactions_id_seq to authenticated;
grant usage, select on sequence public.pr_moment_comments_id_seq to authenticated;
grant usage, select on sequence public.rollerfeed_comments_id_seq to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('pr-moments', 'pr-moments', false, 15728640, array['image/jpeg','image/png','image/webp','image/heic','video/mp4','video/quicktime','video/webm'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create policy "moment media owners upload" on storage.objects for insert to authenticated
with check (bucket_id = 'pr-moments' and (storage.foldername(name))[1] = pr_private.current_profile_id());
create policy "moment media visible download" on storage.objects for select to authenticated using (
  bucket_id = 'pr-moments' and exists (
    select 1 from public.pr_moments m where m.storage_path = name
  )
);
create policy "moment media owners update" on storage.objects for update to authenticated
using (bucket_id = 'pr-moments' and (storage.foldername(name))[1] = pr_private.current_profile_id())
with check (bucket_id = 'pr-moments' and (storage.foldername(name))[1] = pr_private.current_profile_id());
create policy "moment media owners delete" on storage.objects for delete to authenticated
using (bucket_id = 'pr-moments' and ((storage.foldername(name))[1] = pr_private.current_profile_id() or pr_private.is_moderator()));
