import { useEffect, useMemo, useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import Header from '../components/Header'
import BottomNav from '../components/BottomNav'
import MessagePopup from '../components/MessagePopup'
import InstallPrompt from '../components/InstallPrompt'
import { useAuth } from '../lib/auth'
import { supabase } from '../lib/supabase'
import { isPRNextPreview } from '../lib/prNext'
const LUCIA_WHATSAPP='59899220929',PR_TIME_ZONE='America/Montevideo'
function montevideoDateParts(date=new Date()){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:PR_TIME_ZONE,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]));return{year:parts.year,month:parts.month,day:parts.day}}function currentTreasuryPeriod(){const{year,month}=montevideoDateParts();return`${year}-${month}-01`}function montevideoDayOfMonth(){return Number(montevideoDateParts().day||0)}function parseExpirationDate(v){if(!v)return null;const d=new Date(`${String(v).slice(0,10)}T23:59:59`);return Number.isNaN(d.getTime())?null:d}function formatExpirationDate(v){const d=parseExpirationDate(v);return d?d.toLocaleDateString('es-UY',{day:'2-digit',month:'long',year:'numeric'}):'Sin fecha registrada'}function shouldBlockAccess(p,e,d){if(!p)return false;if(p.exentoMensualidad||p.role==='admin'||p.role==='profesor')return false;if(p.accesoHabilitado===false)return true;if(!e||!d||montevideoDayOfMonth()<11)return false;if(['pagado','bonificado','acuerdo'].includes(String(d.estado||'').toLowerCase()))return false;const x=parseExpirationDate(d.gracia_hasta||d.vencimiento);return Boolean(x&&x.getTime()<Date.now())}function buildWhatsAppLink(p){const n=`${p?.nombre||''} ${p?.apellido||''}`.trim()||'alumno/a';return`https://wa.me/${LUCIA_WHATSAPP}?text=${encodeURIComponent(`Hola Lucía, soy ${n}. Quisiera regularizar mi mensualidad de Punta Rollers.`)}`}
function AccessBlocked({profile,onLogout,onPublicHome}){return <div className="min-h-[calc(100vh-72px)] px-4 py-8 flex items-center justify-center"><section className="w-full max-w-md rounded-[32px] border border-red-400/20 bg-red-500/10 p-6"><div className="text-3xl">🔒</div><h1 className="font-display text-3xl text-white mt-3">Tu mensualidad está vencida</h1><p className="text-white/55 text-sm mt-4">Hola, {profile?.nombre||'alumno'}. Para volver a usar los servicios privados necesitás regularizarla.</p><p className="mt-3 text-xs text-white/35">Venció el {formatExpirationDate(profile?.mensualidadHasta)}</p><a href={buildWhatsAppLink(profile)} target="_blank" rel="noreferrer" className="btn-gold w-full mt-6 flex justify-center">Regularizar por WhatsApp</a><button onClick={onPublicHome} className="w-full mt-3 py-3 text-white">Ir a la página pública</button><button onClick={onLogout} className="w-full mt-2 py-2 text-white/40 text-xs">Cerrar sesión</button></section></div>}
export default function AppLayout({children,title,showBack=false}){const navigate=useNavigate(),location=useLocation(),{user,logout,updateUser}=useAuth(),[accessProfile,setAccessProfile]=useState(user||null),[checkingAccess,setCheckingAccess]=useState(Boolean(user?.id) && !isPRNextPreview()),[enforcementEnabled,setEnforcementEnabled]=useState(false),[monthlyDue,setMonthlyDue]=useState(null),[dmUnread,setDmUnread]=useState(0),[dmToast,setDmToast]=useState(null),[communityUnread,setCommunityUnread]=useState(0),dmSeenRef=useState(()=>({total:null}))[0]
useEffect(()=>{let active=true;async function check(){if(isPRNextPreview()){setCheckingAccess(false);return}if(!user?.id){setCheckingAccess(false);return}const period=currentTreasuryPeriod(),[{data},{data:c},{data:d}]=await Promise.all([supabase.from('profiles').select('id,role,nombre,apellido,mensualidad_hasta,acceso_habilitado,exento_mensualidad,es_profesor,participa_como_alumno').eq('id',user.id).maybeSingle(),supabase.from('pr_tesoreria_config').select('enforcement_enabled').eq('id',1).maybeSingle(),supabase.from('pr_mensualidades').select('periodo,monto,vencimiento,estado,gracia_hasta,fecha_pago').eq('alumno_id',user.id).eq('periodo',period).maybeSingle()]);if(!active)return;setEnforcementEnabled(Boolean(c?.enforcement_enabled));setMonthlyDue(d||null);if(data){const p={...user,role:data.role||user.role,nombre:data.nombre||user.nombre,apellido:data.apellido||'',mensualidadHasta:data.mensualidad_hasta||'',accesoHabilitado:data.acceso_habilitado!==false,exentoMensualidad:Boolean(data.exento_mensualidad)||['admin','profesor'].includes(data.role)};setAccessProfile(p);updateUser?.(p)}setCheckingAccess(false)}check();const t=setInterval(check,60000);return()=>{active=false;clearInterval(t)}},[user?.id])
useEffect(()=>{if(isPRNextPreview()||!user?.id)return;async function social(){const{count}=await supabase.from('community_notifications').select('id',{count:'exact',head:true}).is('read_at',null);setCommunityUnread(count||0)}social();const ch=supabase.channel(`social-nav-${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'community_notifications',filter:`recipient_id=eq.${user.id}`},social).subscribe();return()=>supabase.removeChannel(ch)},[user?.id])
useEffect(()=>{if(isPRNextPreview()||!user?.id)return;let active=true;async function dm(){const{data,error}=await supabase.rpc('pr_dm_inbox');if(!active||error||!Array.isArray(data))return;const total=data.reduce((s,i)=>s+Number(i.unread_count||0),0),previous=dmSeenRef.total;setDmUnread(total);if(previous!==null&&total>previous&&!location.pathname.startsWith('/app/mensajes')){const n=data.find(i=>Number(i.unread_count||0)>0);if(n){setDmToast({id:n.id,name:[n.other_profile?.nombre,n.other_profile?.apellido].filter(Boolean).join(' ')||'PR Chat',text:n.last_message||'Nuevo mensaje'});setTimeout(()=>setDmToast(null),6000)}}dmSeenRef.total=total}dm();const t=setInterval(dm,5000);return()=>{active=false;clearInterval(t)}},[user?.id,location.pathname])
const accessBlocked=useMemo(()=>!isPRNextPreview()&&shouldBlockAccess(accessProfile,enforcementEnabled,monthlyDue),[accessProfile,enforcementEnabled,monthlyDue]);async function handleLogout(){await logout?.();navigate('/')}return <div className="app-shell pb-24"><Header title={title} showBack={accessBlocked?false:showBack} onBack={()=>navigate(-1)}/><main>{checkingAccess?<div className="min-h-[60vh] grid place-items-center text-white/40 text-xs">Verificando tu acceso…</div>:accessBlocked?<AccessBlocked profile={accessProfile} onLogout={handleLogout} onPublicHome={()=>navigate('/')}/>:children}</main>{!accessBlocked&&<BottomNav/>}{!accessBlocked&&!isPRNextPreview()&&<InstallPrompt/>}{!accessBlocked&&dmToast&&<MessagePopup title={dmToast.name} message={dmToast.text} onClick={()=>navigate(`/app/mensajes?chat=${dmToast.id}`)} onClose={()=>setDmToast(null)}/>} {!accessBlocked&&communityUnread>0&&!location.pathname.startsWith('/app/comunidad')&&<button onClick={()=>navigate('/app/comunidad')} className="fixed bottom-[7.8rem] right-4 z-40 rounded-full border border-violet-300/25 bg-violet-500 px-3 py-2 text-[10px] font-black text-white shadow-xl">👥 {communityUnread}</button>}{dmUnread>0&&!accessBlocked&&!location.pathname.startsWith('/app/mensajes')&&<button onClick={()=>navigate('/app/mensajes')} className="fixed bottom-24 right-4 z-40 rounded-full bg-orange-500 px-3 py-2 text-[10px] font-black text-black">💬 {dmUnread}</button>}</div>}
